import type { Locale, Workspace } from "./schemas";
import { type SignalSource } from "./action-signals";
import { contextProject } from "./work-scope";
import { acrossContextSignals } from "./across-work-signals";

export type ManagementSignal = {
  id: string; group: "decide" | "act" | "check"; priority: number;
  title: string; why: string; action: string; owner: string; dueDate?: string;
  source: { collection: "programs" | "operations"; id: string; recordId?: string; kind?:SignalSource["kind"]; register?:string };
  rule: string; asOf: string; missingEvidence: string[]; confidence: "known" | "insufficient-evidence";
};
/** Rules are product heuristics, never probabilities. Caller supplies the observation day. */
export function managementSignals(workspace: Workspace, locale: Locale, asOf: string): ManagementSignal[] {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(asOf) || !Number.isFinite(Date.parse(asOf)) || new Date(asOf).toISOString().slice(0,10)!==asOf) throw new Error("Invalid signal date");
  const ru = locale === "ru", signals: ManagementSignal[] = [];
  const add = (signal: Omit<ManagementSignal, "asOf">) => signals.push({ ...signal, asOf });
  const scopes=[...workspace.programs.map(row=>({kind:"program" as const,id:row.id})),...workspace.operations.map(row=>({kind:"operation" as const,id:row.id}))];
  const projects=scopes.map(scope=>contextProject(workspace,scope));
  const scopeByKey=new Map(projects.map((project,index)=>[project.id,scopes[index]]));
  for(const {project,signal} of acrossContextSignals(workspace,projects,locale,asOf)) {
    const scope=scopeByKey.get(project.id)!;
    add({id:`${scope.kind}-${scope.id}-${signal.id}`,group:signal.category==="decision"?"decide":signal.category==="review"||signal.category==="control"?"check":"act",priority:signal.severity==="critical"?100:signal.severity==="high"?80:40,title:`${project.name} · ${signal.title}`,why:signal.why,action:signal.action,owner:signal.source?.owner??"",dueDate:signal.dueDate,source:{collection:scope.kind==="program"?"programs":"operations",id:scope.id,recordId:signal.source?.id,kind:signal.source?.kind,register:signal.view},rule:signal.evidence.rule,missingEvidence:signal.evidence.missing,confidence:signal.evidence.missing.length?"insufficient-evidence":"known"});
  }
  for (const program of workspace.programs) {
    const source = { collection: "programs" as const, id: program.id };
    for (const benefit of program.benefits) {
      const missing = [!benefit.owner.trim() ? "owner" : "", !benefit.measurementPlan.trim() ? "measurementPlan" : "", benefit.baseline === undefined ? "baseline" : "", benefit.target === undefined ? "target" : "", !benefit.unit.trim()?"unit":"", benefit.actual===undefined?"actual":"", !benefit.measuredAt?"measuredAt":benefit.measuredAt>asOf?"observation on or before asOf":""].filter(Boolean);
      if (missing.length) add({ id: `benefit-${program.id}-${benefit.id}`, group: "check", priority: 30, title: `${program.name} · ${benefit.name}`, why: ru ? "Недостаточно данных для проверки выгоды программы." : "There is insufficient evidence to review this program benefit.", action: ru ? "Назначить владельца и способ измерения; зафиксировать исходное и целевое значения, единицу и датированное фактическое наблюдение." : "Assign an owner and measurement plan; record baseline, target, unit and dated actual evidence.", owner: benefit.owner, dueDate: benefit.reviewDate, source: { ...source, recordId: benefit.id }, rule: "benefit-evidence: owner + measurementPlan + baseline + target + unit + actual + measuredAt <= asOf required", missingEvidence: missing, confidence: "insufficient-evidence" });
      else if (benefit.reviewDate && benefit.reviewDate <= asOf) add({ id: `benefit-review-${program.id}-${benefit.id}`, group: "check", priority: 40, title: `${program.name} · ${benefit.name}`, why: ru ? "Наступила дата проверки реализации выгоды." : "The benefit realization review is due.", action: ru ? "Проверить фактическое изменение и обновить дату обзора." : "Review the actual change and update the review date.", owner: benefit.owner, dueDate: benefit.reviewDate, source: { ...source, recordId: benefit.id }, rule: "benefit reviewDate <= asOf", missingEvidence: [], confidence: "known" });
    }
    for (const dependency of program.dependencies.filter(row => row.status !== "resolved")) {
      if (dependency.status === "blocked" || (dependency.dueDate && dependency.dueDate < asOf)) add({ id: `program-dependency-${program.id}-${dependency.id}`, group: "decide", priority: 90, title: `${program.name} · ${dependency.description}`, why: ru ? "Межпроектная передача заблокирована или просрочена; общий результат под угрозой." : "A cross-project handoff is blocked or overdue, threatening the shared outcome.", action: ru ? "Согласовать передачу и владельца решения с обоими компонентами." : "Agree the handoff and decision owner with both components.", owner: dependency.owner, dueDate: dependency.dueDate, source: { ...source, recordId: dependency.id }, rule: "dependency status=blocked OR dueDate < asOf, excluding resolved", missingEvidence: dependency.owner ? [] : ["owner"], confidence: "known" });
    }
    for (const conflict of program.resourceConflicts.filter(row => !row.resolution.trim())) add({ id: `conflict-${program.id}-${conflict.id}`, group: "decide", priority: 80, title: `${program.name} · ${conflict.resource}`, why: ru ? "Неразрешённый конфликт общего ресурса задерживает компоненты программы." : "An unresolved shared resource conflict can delay program components.", action: ru ? "Согласовать приоритет и записать решение по распределению ресурса." : "Agree priorities and record the resource allocation decision.", owner: conflict.owner, source: { ...source, recordId: conflict.id }, rule: "resource conflict resolution is empty", missingEvidence: [], confidence: "known" });
  }
  for (const operation of workspace.operations) {
    const source = { collection: "operations" as const, id: operation.id };
    if (operation.demand !== undefined && operation.capacity !== undefined && operation.demand > operation.capacity) add({ id: `capacity-${operation.id}`, group: "decide", priority: 85, title: operation.name, why: ru ? "Спрос превышает указанную мощность в одинаковых единицах и периоде." : "Demand exceeds the recorded capacity in the same unit and period.", action: ru ? "Проверить период измерения; изменить мощность, приоритеты или обязательства." : "Verify the measurement period; adjust capacity, priorities or commitments.", owner: operation.owner, source, rule: `demand (${operation.demand}) > capacity (${operation.capacity}); unit=${operation.demandUnit}`, missingEvidence: operation.demandUnit ? [] : ["demandUnit"], confidence: operation.demandUnit ? "known" : "insufficient-evidence" });
    for (const metric of operation.metrics) {
      const observations = metric.observations.filter(row => row.at <= asOf).toSorted((a,b)=>a.at.localeCompare(b.at));
      const latest = observations.at(-1);
      if (!latest) add({ id: `metric-unknown-${operation.id}-${metric.id}`, group: "check", priority: 20, title: `${operation.name} · ${metric.name}`, why: ru ? "Нет наблюдений на дату обзора. Состояние неизвестно." : "No observations exist as of the review date. Status is unknown.", action: ru ? "Записать измерение с датой и единицей." : "Record a dated observation and unit.", owner: metric.owner, source: { ...source, recordId: metric.id }, rule: "zero observations at or before asOf", missingEvidence: ["observation"], confidence: "insufficient-evidence" });
      else if (metric.direction === "at-least" ? latest.value < metric.target : latest.value > metric.target) add({ id: `metric-breach-${operation.id}-${metric.id}`, group: "act", priority: 75, title: `${operation.name} · ${metric.name}`, why: `${latest.value} ${metric.unit} ${metric.direction === "at-least" ? "<" : ">"} ${metric.target} ${metric.unit} (${latest.at})`, action: ru ? "Проверить причину отклонения и назначить корректирующее действие." : "Investigate the deviation and assign a corrective action.", owner: metric.owner, source: { ...source, recordId: metric.id }, rule: "latest observed value violates target in the configured direction", missingEvidence: [], confidence: "known" });
    }
    for (const control of operation.controls.filter(row => !row.completedAt && row.dueDate <= asOf)) add({ id: `control-${operation.id}-${control.id}`, group: "check", priority: 70, title: `${operation.name} · ${control.name}`, why: ru ? "Обязательная проверка наступила и не отмечена выполненной." : "A required control is due and has no completion evidence.", action: ru ? "Выполнить проверку по инструкции и сохранить дату выполнения." : "Perform the runbook control and record completion.", owner: control.owner, dueDate: control.dueDate, source: { ...source, recordId: control.id }, rule: "control dueDate <= asOf AND completedAt absent", missingEvidence: ["completion"], confidence: "known" });
    for (const incident of operation.incidents.filter(row => !row.resolvedAt)) add({ id: `incident-${operation.id}-${incident.id}`, group: "act", priority: incident.recurring ? 95 : 80, title: `${operation.name} · ${incident.title}`, why: ru ? (incident.recurring ? "Повторяющийся инцидент остаётся открытым." : "Инцидент остаётся открытым.") : (incident.recurring ? "A recurring incident remains unresolved." : "An incident remains unresolved."), action: ru ? "Назначить восстановление и корректирующее действие; проверить повторяемость." : "Assign recovery and corrective action; investigate recurrence.", owner: incident.owner, source: { ...source, recordId: incident.id }, rule: "incident resolvedAt absent; recurring incidents rank higher", missingEvidence: [], confidence: "known" });
  }
  return signals.sort((a,b)=>b.priority-a.priority || (a.dueDate ?? "9999").localeCompare(b.dueDate ?? "9999") || a.id.localeCompare(b.id));
}
