import {test,expect} from '@playwright/test';
import {demoWorkspace} from '../../src/data/demo';
import {route} from './support';
import AxeBuilder from '@axe-core/playwright';
test('guided project context persists and Today opens its exact record',async({page})=>{
 await page.goto(route('/en/workspace/'));await page.getByRole('button',{name:'Create first project'}).click();const d=page.getByRole('dialog');await d.getByLabel('Title',{exact:true}).fill('Operating profile test');await d.getByLabel('Measurable outcome',{exact:true}).fill('Accept the pilot');await d.getByLabel('Owner',{exact:true}).fill('Project lead');await d.getByRole('button',{name:'Next',exact:true}).click();await d.locator('input[name="volatility"]').focus();await page.keyboard.press('End');await d.getByRole('button',{name:'Show recommendations'}).click();await expect(d).toContainText('volatility ≥ 4');await d.getByRole('button',{name:'Create',exact:true}).click();await expect(page.getByRole('heading',{name:'Today',exact:true}).first()).toBeVisible();await page.reload();await expect(page.getByText('First three actions',{exact:true})).toBeVisible();
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('pmwork:workspace:v3')!));expect((stored.workspace??stored).projectSettings[0].context.volatility).toBe(5);
});
test('Today signal opens the referenced risk',async({page})=>{const w=demoWorkspace('en');await page.addInitScript(w=>localStorage.setItem('pmwork:workspace:v3',JSON.stringify(w)),w);await page.goto(route('/en/workspace/?view=overview'));const row=page.locator('.action-list li').filter({hasText:'High exposure'}).first();await row.getByRole('button',{name:'Open record'}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByLabel('Title',{exact:true})).not.toHaveValue('');});
test('intent search returns playbook and scheduling tool',async({page})=>{await page.goto(route('/ru/'));await page.keyboard.press('Control+k');await page.getByRole('searchbox').fill('проект опаздывает');await expect(page.locator('.command-results')).toContainText('Проект опаздывает');await expect(page.locator('.command-results a[href*="tool=cpm"]')).toBeVisible();});
test('deadline input validation and deterministic forecast are accessible',async({page})=>{await page.goto(route('/en/tools/?tool=deadline'));await page.getByRole('button',{name:'Calculate',exact:true}).click();await expect(page.getByRole('status')).toContainText('Check inputs');await page.getByLabel('Completions per full calendar day, including zeros, comma separated').fill(Array(14).fill(1).join(','));const target=new Date(Date.now()+20*86400000).toISOString().slice(0,10);await page.getByLabel('Target date',{exact:true}).fill(target);await page.getByRole('button',{name:'Calculate',exact:true}).click();await expect(page.locator('.tool-output')).toContainText('100.0%');const axe=await new AxeBuilder({page:page as never}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(axe.violations).toEqual([]);});
test('v4 migration preserves project records in browser',async({page})=>{const w={...demoWorkspace('en'),schemaVersion:4};await page.addInitScript(w=>localStorage.setItem('pmwork:workspace:v3',JSON.stringify(w)),w);await page.goto(route('/en/workspace/?view=overview'));await expect(page.locator('.workspace-shell')).toBeVisible();await expect.poll(async()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('pmwork:workspace:v3')!);return (s.workspace??s).schemaVersion})).toBe(5);const stored=await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('pmwork:workspace:v3')!);return (s.workspace??s).workItems.length});expect(stored).toBe(w.workItems.length);});
test('static English document exposes language before scripts',async({request})=>{const response=await request.get(route('/en/workspace/'));expect(await response.text()).toContain('<html lang="en"');});
test('project-connected EVM loads recorded budget and distinguishes missing earned value',async({page})=>{const w=demoWorkspace('en');await page.addInitScript(w=>localStorage.setItem('pmwork:workspace:v3',JSON.stringify(w)),w);await page.goto(route('/en/tools/?tool=evm'));await page.getByRole('button',{name:'Choose project data'}).click();await page.getByRole('button',{name:'Use project data',exact:true}).click();await expect(page.getByLabel('BAC',{exact:true})).toHaveValue(String(w.budgets.filter(x=>x.projectId==='atlas').reduce((s,x)=>s+x.planned,0)));await expect(page.getByLabel('EV',{exact:true})).toHaveValue('0');await expect(page.getByRole('status')).toContainText('enter measured values');});
test('playbook creates a linked issue and opens its editor',async({page})=>{const w=demoWorkspace('en');await page.addInitScript(w=>localStorage.setItem('pmwork:workspace:v3',JSON.stringify(w)),w);await page.goto(route('/en/playbooks/?q=Project%20is%20late'));const card=page.locator('article').first();await card.getByRole('button',{name:'Apply to a project issue'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Issue title').fill('Schedule recovery issue');await dialog.getByRole('button',{name:'Create issue',exact:true}).click();await card.getByRole('link',{name:'Open issue'}).click();await expect(page.getByRole('dialog').getByLabel('Title',{exact:true})).toHaveValue('Schedule recovery issue');});
for(const locale of ['ru','en'])for(const tool of ['deadline','emv','capacity','matrix','ownership','change','calibration'])test(`new tool surface ${locale} ${tool}`,async({page},info)=>{await page.goto(route(`/${locale}/tools/?tool=${tool}`));await expect(page.getByRole('button',{name:locale==='ru'?'Выбрать локальный проект':'Choose local project'})).toBeVisible();expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`test-results/new-tool-${locale}-${tool}-${info.project.name}.png`,fullPage:true});const axe=await new AxeBuilder({page:page as never}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(axe.violations).toEqual([]);});
