import Link from "next/link";
import { ArrowRight,BookOpen,ChartNoAxesCombined,GitBranch,LayoutDashboard,ShieldCheck,Workflow } from "lucide-react";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import type { Locale } from "@/domain/schemas";
import { ui } from "@/content/ui";
import { contentCounts } from "@/content/catalog";
import { PublicHeader } from "@/components/public-header";
import { Footer } from "@/components/footer";
export function generateStaticParams(){return [{locale:"ru"},{locale:"en"}];}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;return {title:locale==="ru"?"PMWORK — операционная система Project Manager":"PMWORK — Project Management Operating System",description:locale==="ru"?"Ведите проекты, backlog, риски, сроки и решения в одной local-first системе.":"Run projects, backlog, risks, schedule, and decisions in one local-first system.",alternates:{canonical:`https://castefeudal.github.io/pmwork/${locale}/`,languages:{ru:"https://castefeudal.github.io/pmwork/ru/",en:"https://castefeudal.github.io/pmwork/en/"}},openGraph:{title:locale==="ru"?"PMWORK — операционная система Project Manager":"PMWORK — Project Management Operating System",description:locale==="ru"?"Практическая local-first система управления проектами.":"A practical local-first project management system.",url:`https://castefeudal.github.io/pmwork/${locale}/`,type:"website"}};}
export default async function Home({params}:{params:Promise<{locale:string}>}){const {locale:raw}=await params;if(raw!=="ru"&&raw!=="en")notFound();const locale=raw as Locale,t=ui(locale),ru=locale==="ru";return <div className="shell"><PublicHeader locale={locale}/><main id="main">
 <section className="hero"><div><p className="eyebrow">{t.hero.eyebrow}</p><h1>{t.hero.title}</h1><p className="lead">{t.hero.lead}</p><div className="button-row"><Link className="button primary" href={`/${locale}/workspace`}>{t.hero.open}<ArrowRight size={18}/></Link><Link className="button secondary" href={`/${locale}/tools#fit`}>{t.hero.choose}</Link></div><div className="trust-line"><span>Local-first</span><span>RU / EN</span><span>WCAG 2.2 AA target</span><span>AI-free</span></div></div>
 <div className="cockpit-preview" aria-label={ru?"Пример интерфейса PMWORK":"PMWORK interface preview"}><div className="cockpit-head"><strong>Atlas launch</strong><span className="status warn">{ru?"Есть риски":"At risk"}</span></div><div className="cockpit-body"><div className="mini-side"><span/><span/><span/><span/><span/></div><div className="mini-main"><div className="metric-grid"><div className="metric"><small>WIP</small><strong>7</strong></div><div className="metric"><small>{ru?"Риски":"Risks"}</small><strong>4</strong></div><div className="metric"><small>SPI</small><strong>0.94</strong></div></div><div className="preview-board"><div className="preview-column"><small>READY · 3</small><div className="preview-card">{ru?"Согласовать scope релиза":"Align release scope"}</div></div><div className="preview-column"><small>IN PROGRESS · 2/3</small><div className="preview-card">{ru?"Миграция каталога":"Catalog migration"}</div><div className="preview-card">{ru?"План приёмки":"Acceptance plan"}</div></div><div className="preview-column"><small>REVIEW · 1</small><div className="preview-card">{ru?"Security review":"Security review"}</div></div></div></div></div></div>
 </section>
 <section className="section"><div className="section-head"><div><p className="eyebrow">UNDERSTAND → DECIDE → DO → CONTROL → LEARN</p><h2>{ru?"Знания становятся работой":"Knowledge becomes work"}</h2></div><p>{ru?"PMWORK связывает объяснение с решением, инструментом и контролем. Risk management — это не статья, а рабочий реестр, matrix, response plan и review cadence с понятным источником.":"PMWORK connects explanation to decision, tool, and control. Risk management is not merely an article: it is a working register, matrix, response plan, and review cadence with a clear source."}</p></div>
 <div className="feature-grid">{[[LayoutDashboard,ru?"Project cockpit":"Project cockpit",ru?"Цели, milestones, blockers, решения и health dimensions без загадочного единого score.":"Objectives, milestones, blockers, decisions, and health dimensions without a mysterious score."],[Workflow,ru?"Work system":"Work system",ru?"Backlog, Kanban, list и timeline с WIP, зависимостями и явными policies.":"Backlog, Kanban, list, and timeline with WIP, dependencies, and explicit policies."],[ShieldCheck,"RAID & governance",ru?"Риски, issues, assumptions, change control и уровни governance под контекст.":"Risks, issues, assumptions, change control, and context-fit governance."],[GitBranch,ru?"Подбор подхода":"Approach fit",ru?"Прозрачная эвристика сравнивает predictive, adaptive, flow и hybrid без магии.":"A transparent heuristic compares predictive, adaptive, flow, and hybrid—no magic."],[ChartNoAxesCombined,ru?"Расчёты":"Calculations",ru?"CPM, PERT, EVM, RICE, WSJF, Little’s Law и Monte Carlo в браузере.":"CPM, PERT, EVM, RICE, WSJF, Little’s Law, and Monte Carlo in-browser."],[BookOpen,ru?"Профессиональная база":"Professional library",`${contentCounts.methods} ${ru?"методов":"methods"}, ${contentCounts.templates} ${ru?"шаблонов":"templates"}, ${contentCounts.playbooks} playbooks, ${contentCounts.glossary} ${ru?"терминов":"terms"}.`]].map(([Icon,title,copy],i)=>{const I=Icon as typeof LayoutDashboard;return <article className="feature" key={String(title)}><span className="num">0{i+1}</span><I size={22}/><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div></section>
 <section className="section"><div className="section-head"><div><p className="eyebrow">Context over dogma</p><h2>{ru?"Подход — это система допущений":"An approach is a system of assumptions"}</h2></div><p>{ru?"Используйте predictive, adaptive, flow или hybrid осмысленно. Governance, planning, delivery cadence и improvement practices можно сочетать, если их operating assumptions не конфликтуют.":"Use predictive, adaptive, flow, or hybrid intentionally. Governance, planning, delivery cadence, and improvement practices can be composed when their operating assumptions do not conflict."}</p></div><div className="method-strip">{["Predictive","Scrum","Kanban","Hybrid","PRINCE2"].map((x,i)=><div key={x}><span className="num">{String(i+1).padStart(2,"0")}</span><strong>{x}</strong><small>{i===0?"control":i===1?"empiricism":i===2?"flow":i===3?"tailoring":"governance"}</small></div>)}</div></section>
 <section className="section"><div className="section-head"><div><p className="eyebrow">PMWORK principles</p><h2>{ru?"Минимально достаточный контроль":"Minimum sufficient control"}</h2></div><div><p><strong>Context over dogma.</strong> {ru?"Нет одной методологии для всех проектов.":"No method fits every project."}</p><p><strong>Value over activity.</strong> {ru?"Выполненные задачи не равны результату.":"Completed tasks are not the outcome."}</p><p><strong>Transparency over bureaucracy.</strong> {ru?"Артефакт нужен, когда помогает решению.":"An artifact matters when it supports a decision."}</p><p><strong>Explicit ownership.</strong> {ru?"Критичная работа, риск и решение имеют владельца.":"Critical work, risks, and decisions have owners."}</p></div></div></section>
 </main><Footer locale={locale}/></div>}
