import type { Locale } from "@/domain/schemas";

export type Bi = { ru: string; en: string };
export const pick = (value: Bi, locale: Locale) => value[locale];
export type Source = {
  id: string;
  title: string;
  organization: string;
  version: string;
  published: string;
  checked: string;
  url: string;
  authority: "Standard" | "Official Guide" | "Practice";
  notes: Bi;
};

export const sources: Source[] = [
  {
    id: "pmbok8",
    title: "PMBOK® Guide and The Standard for Project Management",
    organization: "Project Management Institute",
    version: "8th edition",
    published: "2025",
    checked: "2026-09-05",
    url: "https://www.pmi.org/standards/pmbok",
    authority: "Standard",
    notes: {
      ru: "Официальный стандарт PMI; изложение PMWORK оригинально.",
      en: "Official PMI standard; PMWORK uses original explanations.",
    },
  },
  {
    id: "agile2",
    title: "Agile Practice Guide",
    organization: "Project Management Institute",
    version: "2nd edition",
    published: "2025",
    checked: "2026-09-05",
    url: "https://www.pmi.org/standards/agile",
    authority: "Official Guide",
    notes: {
      ru: "Официальное руководство по контекстному применению адаптивных практик.",
      en: "Official guidance for contextual use of adaptive practices.",
    },
  },
  {
    id: "scrum2020",
    title: "The Scrum Guide",
    organization: "Scrum.org / Scrum Inc.",
    version: "November 2020",
    published: "2020-11",
    checked: "2026-09-05",
    url: "https://scrumguides.org/scrum-guide.html",
    authority: "Official Guide",
    notes: {
      ru: "Актуальная проверенная версия руководства по Scrum.",
      en: "Current verified Scrum Guide version.",
    },
  },
  {
    id: "kanban2025",
    title: "The Kanban Guide",
    organization: "Kanban Guides",
    version: "May 2025",
    published: "2025-05",
    checked: "2026-09-05",
    url: "https://kanbanguides.org/the-kanban-guide/2025.5/",
    authority: "Official Guide",
    notes: {
      ru: "Определяет рабочий процесс, WIP, пропускную способность, возраст рабочих элементов и время цикла.",
      en: "Defines workflow, WIP, throughput, work item age, and cycle time.",
    },
  },
  {
    id: "prince2v7",
    title: "PRINCE2 Project Management",
    organization: "PeopleCert",
    version: "Version 7",
    published: "2023",
    checked: "2026-09-05",
    url: "https://www.peoplecert.org/browse-certifications/project-programme-and-portfolio-management/PRINCE2-2",
    authority: "Official Guide",
    notes: {
      ru: "Официальная страница владельца методики.",
      en: "Official framework owner page.",
    },
  },
  {
    id: "iso21502",
    title:
      "ISO 21502:2020 Project, programme and portfolio management — Guidance on project management",
    organization: "ISO",
    version: "ISO 21502:2020",
    published: "2020",
    checked: "2026-09-05",
    url: "https://www.iso.org/standard/74947.html",
    authority: "Standard",
    notes: {
      ru: "Международный стандарт; полный текст не воспроизводится.",
      en: "International standard; full text is not reproduced.",
    },
  },
  {
    id: "agilemanifesto",
    title: "Manifesto for Agile Software Development",
    organization: "Agile Manifesto authors",
    version: "2001",
    published: "2001",
    checked: "2026-09-05",
    url: "https://agilemanifesto.org/",
    authority: "Official Guide",
    notes: {
      ru: "Первичный источник ценностей и принципов Agile.",
      en: "Primary source for Agile values and principles.",
    },
  },
  {
    id: "wcag22",
    title: "Web Content Accessibility Guidelines",
    organization: "W3C",
    version: "WCAG 2.2",
    published: "2023",
    checked: "2026-09-05",
    url: "https://www.w3.org/TR/WCAG22/",
    authority: "Standard",
    notes: {
      ru: "Целевая планка интерфейса — уровень AA.",
      en: "The interface targets Level AA.",
    },
  },
];

export type Method = {
  slug: string;
  title: Bi;
  summary: Bi;
  origin: Bi;
  principles: Bi[];
  flow: Bi;
  roles: Bi;
  artifacts: Bi;
  cadence: Bi;
  metrics: Bi;
  strengths: Bi;
  limitations: Bi;
  prerequisites: Bi;
  bestFit: Bi;
  poorFit: Bi;
  antiPatterns: Bi;
  tailoring: Bi;
  combinations: Bi;
  checklist: Bi[];
  sourceIds: string[];
  version: string;
  updatedAt: string;
};
const m = (
  slug: string,
  ru: string,
  en: string,
  summaryRu: string,
  summaryEn: string,
  flowRu: string,
  flowEn: string,
  bestRu: string,
  bestEn: string,
  limitsRu: string,
  limitsEn: string,
  sourceIds: string[],
  version = "Practice",
): Method => ({
  slug,
  title: { ru, en },
  summary: { ru: summaryRu, en: summaryEn },
  origin: {
    ru: "Возник как ответ на определённый контекст управления; используйте происхождение для понимания допущений, а не как знак универсальности.",
    en: "Emerged for a specific management context; use its origin to understand assumptions, not as proof of universality.",
  },
  principles: [
    {
      ru: "Явно определить способ принятия решений и поток работы.",
      en: "Make decision rights and work flow explicit.",
    },
    {
      ru: "Подбирать контроль пропорционально риску и неопределённости.",
      en: "Tailor control to risk and uncertainty.",
    },
    {
      ru: "Замыкать цикл план → работа → обратная связь → адаптация.",
      en: "Close the plan → work → feedback → adaptation loop.",
    },
  ],
  flow: { ru: flowRu, en: flowEn },
  roles: {
    ru: "Роли определяются выбранным подходом; владелец результата, руководитель проекта и исполнители должны иметь ясные полномочия.",
    en: "Roles follow the chosen approach; outcome owner, project lead, and delivery team need clear decision rights.",
  },
  artifacts: {
    ru: "Используйте только те артефакты, которые поддерживают решение, координацию, проверку или ответственность.",
    en: "Use only artifacts that support a decision, coordination, verification, or accountability.",
  },
  cadence: {
    ru: "Каденция зависит от скорости обратной связи, стоимости координации и риска задержки.",
    en: "Cadence depends on feedback speed, coordination cost, and delay risk.",
  },
  metrics: {
    ru: "Смотрите на результат, предсказуемость, поток, качество и риск — не на объём активности.",
    en: "Track outcomes, predictability, flow, quality, and risk—not activity volume.",
  },
  strengths: {
    ru: "Даёт общую операционную модель и язык координации, если совпадает с контекстом.",
    en: "Provides a shared operating model and coordination language when context fits.",
  },
  limitations: { ru: limitsRu, en: limitsEn },
  prerequisites: {
    ru: "Общая цель, явные владельцы, доступ к обратной связи и дисциплина обновления рабочих данных.",
    en: "Shared goal, explicit ownership, access to feedback, and discipline in updating work data.",
  },
  bestFit: { ru: bestRu, en: bestEn },
  poorFit: {
    ru: "Среда, где ключевые допущения подхода отсутствуют или конфликтуют с моделью управления.",
    en: "Environments where core assumptions are absent or conflict with governance.",
  },
  antiPatterns: {
    ru: "Механическое выполнение церемоний; показатели как цель; добавление слоёв без удаления лишних.",
    en: "Mechanical ceremonies; metrics as targets; adding layers without removing waste.",
  },
  tailoring: {
    ru: "Начните с минимально достаточной структуры и усиливайте контроль только по наблюдаемой потребности.",
    en: "Start with minimum sufficient structure and add control only for an observed need.",
  },
  combinations: {
    ru: "Комбинируйте управление, планирование и выполнение как отдельные слои; явно фиксируйте конфликты допущений.",
    en: "Combine governance, planning, and execution as separate layers; expose conflicting assumptions.",
  },
  checklist: [
    {
      ru: "Сформулировать ожидаемый результат и ограничения.",
      en: "State the expected outcome and constraints.",
    },
    {
      ru: "Определить владельцев решений и ритм управления.",
      en: "Define decision owners and cadence.",
    },
    {
      ru: "Выбрать минимум артефактов и метрик.",
      en: "Select the minimum artifacts and metrics.",
    },
    {
      ru: "Провести обзор через один рабочий цикл.",
      en: "Review after one working cycle.",
    },
  ],
  sourceIds,
  version,
  updatedAt: "2026-09-05",
});

export const methods: Method[] = [
  m(
    "predictive",
    "Предиктивное управление",
    "Predictive project management",
    "Детальное предварительное планирование и контроль относительно базового плана.",
    "Plan substantial scope in advance and control delivery against a baseline.",
    "Инициация → планирование → исполнение → контроль → закрытие.",
    "Initiate → plan → execute → control → close.",
    "Стабильные границы проекта, формальные согласования, высокая стоимость изменений.",
    "Stable scope, formal approvals, high change cost.",
    "Плохо переносит частую смену требований и позднюю обратную связь.",
    "Handles frequent requirement change and late feedback poorly.",
    ["pmbok8", "iso21502"],
  ),
  m(
    "waterfall",
    "Каскадная модель",
    "Waterfall",
    "Последовательная модель фаз с формализованными переходами.",
    "Sequential phase model with formal transitions.",
    "Требования → проектирование → создание → проверка → переход.",
    "Requirements → design → build → verify → transition.",
    "Повторяемая работа с предсказуемыми интерфейсами и контрольными точками.",
    "Repeatable work with predictable interfaces and gates.",
    "Ошибки предположений обнаруживаются поздно.",
    "Wrong assumptions may surface late.",
    ["iso21502"],
  ),
  m(
    "agile",
    "Гибкий подход",
    "Agile",
    "Система ценностей для адаптивной разработки через частую поставку и обучение.",
    "A value system for adaptive delivery through frequent value and learning.",
    "Короткие циклы: выбрать ценность → сделать → проверить → адаптировать.",
    "Short loops: choose value → deliver → inspect → adapt.",
    "Высокая неопределённость и доступная частая обратная связь.",
    "High uncertainty with frequent accessible feedback.",
    "Без ясной цели и самостоятельной команды превращается в реактивность.",
    "Without a clear goal and empowered team it becomes reactive.",
    ["agilemanifesto", "agile2"],
  ),
  m(
    "hybrid",
    "Гибридный подход",
    "Hybrid",
    "Осмысленное сочетание модели управления и адаптивной поставки результата.",
    "Purposeful combination of governance and adaptive delivery.",
    "Формальные контрольные точки окружают короткие циклы поставки результата.",
    "Formal control points surround short delivery cycles.",
    "Жёсткие внешние ограничения при изменчивом способе достижения результата.",
    "Hard external constraints with an evolving solution path.",
    "Без явных границ превращается в случайную смесь методик.",
    "Without explicit boundaries it becomes random framework soup.",
    ["pmbok8", "agile2"],
  ),
  m(
    "scrum",
    "Scrum",
    "Scrum",
    "Лёгкая методика для сложных продуктов на основе эмпирического подхода.",
    "A lightweight framework for complex products based on empiricism.",
    "Бэклог продукта → планирование спринта → спринт → обзор и ретроспектива → адаптация.",
    "Product Backlog → Sprint Planning → Sprint → Review + Retrospective → adaptation.",
    "Кросс-функциональная команда может создавать пригодный инкремент в каждом спринте.",
    "A cross-functional team can create a usable Increment every Sprint.",
    "Не решает задачи портфеля, договоров и управления автоматически.",
    "Does not automatically solve portfolio, contracts, or governance.",
    ["scrum2020"],
    "Scrum Guide 2020",
  ),
  m(
    "kanban",
    "Kanban",
    "Kanban",
    "Оптимизация потока через явный рабочий процесс, контроль WIP и обратную связь.",
    "Flow optimization through an explicit workflow, WIP control, and feedback.",
    "Определить рабочий процесс → управлять WIP → наблюдать показатели потока → улучшать.",
    "Define workflow → control WIP → observe flow metrics → improve.",
    "Непрерывный поток разнородной работы и потребность сократить задержки.",
    "Continuous heterogeneous work where reducing delay matters.",
    "Доска без WIP и регулярного разбора потока даёт только визуализацию задач.",
    "A board without WIP control and flow reviews only visualizes tasks.",
    ["kanban2025"],
    "Kanban Guide May 2025",
  ),
  m(
    "scrumban",
    "Скрамбан",
    "Scrumban",
    "Ритм Scrum с практиками потока Kanban и эволюционным улучшением.",
    "Scrum cadence combined with Kanban flow practices and evolutionary improvement.",
    "Цель спринта и обзоры сохраняются; WIP, вытягивание и показатели потока управляют исполнением.",
    "Sprint goal and reviews remain; WIP, pull, and flow metrics govern execution.",
    "Команда Scrum испытывает перегрузку, перенос незавершённой или внеплановую работу.",
    "A Scrum team faces overload, carry-over, or interrupt work.",
    "Название не заменяет явного определения рабочего процесса.",
    "The label does not replace an explicit Definition of Workflow.",
    ["scrum2020", "kanban2025"],
  ),
  m(
    "lean",
    "Бережливый подход",
    "Lean",
    "Управление ценностью, потоком, качеством и устранением потерь.",
    "Manage value, flow, quality, and waste elimination.",
    "Определить ценность → описать поток → устранить ограничения → непрерывно улучшать.",
    "Define value → map flow → remove constraints → improve continuously.",
    "Повторяемые потоки создания ценности и измеримые задержки.",
    "Repeatable value streams with observable delays.",
    "Локальная экономия может повредить системному результату.",
    "Local optimization can harm the system outcome.",
    ["kanban2025"],
  ),
  m(
    "xp",
    "Экстремальное программирование",
    "Extreme Programming",
    "Инженерные практики для быстрой и устойчивой поставки программного обеспечения.",
    "Engineering practices for rapid, sustainable software delivery.",
    "Малые выпуски, тесты, непрерывная интеграция, парная работа и рефакторинг.",
    "Small releases, tests, continuous integration, pair work, refactoring.",
    "Команды разработки с частыми изменениями и сильной инженерной дисциплиной.",
    "Software teams with frequent change and strong engineering discipline.",
    "Практики требуют квалификации и не заменяют продуктового направления.",
    "Practices require skill and do not replace product direction.",
    ["agilemanifesto"],
  ),
  m(
    "prince2",
    "PRINCE2",
    "PRINCE2",
    "Структурированный метод управления через принципы, практики, процессы и адаптацию к контексту.",
    "Structured project management through principles, practices, processes, and tailoring.",
    "Экономическое обоснование и управление по стадиям с определёнными решениями.",
    "Continued business justification and management by stages with defined decisions.",
    "Организации с формальной моделью управления и ясной ответственностью.",
    "Organizations needing formal governance and clear accountability.",
    "Плохая адаптация создаёт документную нагрузку без улучшения контроля.",
    "Poor tailoring creates document load without better control.",
    ["prince2v7"],
    "PRINCE2 7",
  ),
  m(
    "cpm",
    "Метод критического пути",
    "Critical Path Method",
    "Сетевая модель графика, показывающая цепочку без общего временного резерва.",
    "A schedule network model identifying the chain with no total float.",
    "Зависимости и длительности → прямой проход → обратный проход → временной резерв.",
    "Dependencies + durations → forward pass → backward pass → float.",
    "Проекты с зависимыми операциями и достаточно стабильными оценками.",
    "Projects with dependent activities and reasonably stable estimates.",
    "Результат зависит от качества зависимостей и оценок.",
    "Output is only as good as dependencies and estimates.",
    ["pmbok8"],
  ),
  m(
    "critical-chain",
    "Критическая цепь",
    "Critical Chain",
    "Планирование с учётом ресурсных ограничений и общих резервов.",
    "Planning that considers resource constraints and aggregate buffers.",
    "График с ресурсами → критическая цепь → проектный и питающие резервы → контроль резервов.",
    "Resource-level schedule → critical chain → project/feeding buffers → buffer control.",
    "Мультипроектная среда с конкуренцией за ограниченные ресурсы.",
    "Multi-project environments competing for constrained resources.",
    "Некорректные резервы маскируют плохие исходные данные.",
    "Poorly designed buffers can mask weak inputs.",
    ["pmbok8"],
  ),
  m(
    "stage-gate",
    "Этапно-контрольная модель",
    "Stage-Gate",
    "Инвестиционные решения между стадиями развития инициативы.",
    "Investment decisions between stages of initiative development.",
    "Работа этапа → пакет подтверждений → решение: продолжить, приостановить, доработать или остановить.",
    "Stage work → evidence package → gate decision: go/hold/recycle/stop.",
    "Высокая стоимость следующей стадии и необходимость выбора на уровне портфеля.",
    "High next-stage cost and portfolio choices.",
    "Контрольные точки становятся формальностью, если решение об остановке невозможно.",
    "Gates become theater when stopping is impossible.",
    ["pmbok8"],
  ),
  m(
    "lean-startup",
    "Бережливый стартап",
    "Lean Startup",
    "Проверка бизнес-гипотез через цикл «создать — измерить — изучить».",
    "Testing business hypotheses through build–measure–learn.",
    "Гипотеза → минимальный эксперимент → подтверждения → смена или сохранение курса.",
    "Hypothesis → minimum experiment → evidence → pivot/persevere.",
    "Новый продукт с высокой рыночной неопределённостью.",
    "New products with high market uncertainty.",
    "Минимально жизнеспособный продукт (MVP) могут принять за низкокачественный конечный продукт.",
    "An MVP can be mistaken for a low-quality final product.",
    ["agile2"],
  ),
  m(
    "design-thinking",
    "Дизайн-мышление",
    "Design Thinking",
    "Исследование потребностей людей и формирование решения.",
    "Human-centered exploration and solution framing.",
    "Понять людей → определить проблему → создать идеи → сделать прототип → проверить; возвраты между этапами ожидаемы.",
    "Empathize → define → ideate → prototype → test; loops are expected.",
    "Нечёткая проблема и необходимость понять поведение пользователя.",
    "Ambiguous problem requiring user understanding.",
    "Генерация идей без поставки результата и подтверждений не создаёт ценность.",
    "Ideation without delivery and evidence creates no outcome.",
    ["agile2"],
  ),
  m(
    "scaling",
    "Масштабирование: SAFe, LeSS, DA",
    "Scaling: SAFe, LeSS, DA",
    "Нейтральная карта подходов координации нескольких команд.",
    "A neutral map of approaches for coordinating multiple teams.",
    "Синхронизация стратегии, архитектуры, поставки результата и обратной связи различается по методике.",
    "Strategy, architecture, delivery, and feedback synchronization varies by framework.",
    "Реальная межкомандная связанность, которую нельзя устранить проще.",
    "Real cross-team coupling that cannot be removed more simply.",
    "Масштабная методика усиливает существующую сложность и не исправляет слабые команды.",
    "A scaling framework amplifies complexity and does not repair weak teams.",
    ["agile2"],
  ),
];

export type Template = {
  slug: string;
  title: Bi;
  category: string;
  purpose: Bi;
  when: Bi;
  fields: Bi[];
  guidance: Bi;
  antiPattern: Bi;
};
const tf = {
  strategy: [
    { ru: "Контекст и решение", en: "Context and decision" },
    { ru: "Ожидаемый результат", en: "Expected outcome" },
    { ru: "Критерий успеха", en: "Success measure" },
    { ru: "Владелец", en: "Owner" },
  ],
  plan: [
    { ru: "Границы проекта", en: "Scope / boundaries" },
    { ru: "Контрольные точки и даты", en: "Milestones and dates" },
    { ru: "Зависимости", en: "Dependencies" },
    { ru: "Риски и допущения", en: "Risks and assumptions" },
  ],
  log: [
    { ru: "ID и дата", en: "ID and date" },
    { ru: "Описание", en: "Description" },
    { ru: "Владелец", en: "Owner" },
    { ru: "Статус и следующее действие", en: "Status and next action" },
  ],
  meeting: [
    { ru: "Цель встречи", en: "Meeting purpose" },
    { ru: "Подготовка", en: "Preparation" },
    { ru: "Повестка и временные рамки", en: "Agenda and timeboxes" },
    { ru: "Решения и действия", en: "Decisions and actions" },
  ],
  control: [
    { ru: "Базовый план / ожидание", en: "Baseline / expectation" },
    { ru: "Факт", en: "Actual" },
    { ru: "Отклонение", en: "Variance" },
    { ru: "Решение и владелец", en: "Decision and owner" },
  ],
};
const template = (
  slug: string,
  ru: string,
  en: string,
  category: keyof typeof tf,
  purposeRu: string,
  purposeEn: string,
  extra: Bi[] = [],
): Template => ({
  slug,
  title: { ru, en },
  category,
  purpose: { ru: purposeRu, en: purposeEn },
  when: {
    ru: "Используйте, когда артефакт помогает принять решение, синхронизировать участников или подтвердить результат.",
    en: "Use when the artifact supports a decision, aligns participants, or verifies an outcome.",
  },
  fields: [...tf[category], ...extra],
  guidance: {
    ru: "Заполняйте до уровня, достаточного для следующего управленческого действия. Удалите секции, которые ничего не меняют.",
    en: "Complete only to the depth needed for the next management action. Remove sections that change nothing.",
  },
  antiPattern: {
    ru: "Документ обновляется ради отчётности, но не используется в решениях.",
    en: "The document is maintained for reporting but never used in decisions.",
  },
});

export const templates: Template[] = [
  template(
    "project-charter",
    "Устав проекта",
    "Project Charter",
    "strategy",
    "Согласовать полномочия, цель и границы проекта.",
    "Align authority, purpose, and project boundaries.",
    [
      { ru: "Входит / не входит в границы", en: "Scope in / out" },
      { ru: "Бюджетный диапазон", en: "Budget envelope" },
    ],
  ),
  template(
    "business-case-lite",
    "Краткое экономическое обоснование",
    "Business Case Lite",
    "strategy",
    "Проверить, стоит ли инициатива инвестиций.",
    "Check whether the initiative deserves investment.",
  ),
  template(
    "business-case",
    "Бизнес-кейс",
    "Business Case",
    "strategy",
    "Сравнить варианты, выгоды, затраты и риски.",
    "Compare options, benefits, costs, and risks.",
    [
      {
        ru: "Опции и NPV/ROI при уместности",
        en: "Options and NPV/ROI where applicable",
      },
    ],
  ),
  template(
    "project-brief",
    "Бриф проекта",
    "Project Brief",
    "strategy",
    "Дать команде краткий общий контекст.",
    "Give the team concise shared context.",
  ),
  template(
    "project-plan",
    "План проекта",
    "Project Plan",
    "plan",
    "Объединить способ исполнения и контроля.",
    "Unify the delivery and control approach.",
  ),
  template(
    "scope-statement",
    "Описание границ проекта",
    "Scope Statement",
    "plan",
    "Сделать границы и исключения явными.",
    "Make boundaries and exclusions explicit.",
  ),
  template(
    "wbs",
    "Иерархическая структура работ (WBS)",
    "Work Breakdown Structure",
    "plan",
    "Декомпозировать 100% согласованного объёма работ на результаты поставки и рабочие пакеты.",
    "Decompose 100% of agreed scope into deliverables and work packages.",
  ),
  template(
    "requirements-register",
    "Реестр требований",
    "Requirements Register",
    "log",
    "Связать требования с источником, приоритетом и проверкой.",
    "Connect requirements to source, priority, and validation.",
  ),
  template(
    "backlog-item",
    "Элемент бэклога",
    "Backlog Item",
    "log",
    "Сформулировать единицу работы достаточно ясно для решения.",
    "Define a work item clearly enough for a decision.",
  ),
  template(
    "user-story",
    "Пользовательская история",
    "User Story",
    "strategy",
    "Зафиксировать пользователя, потребность и ценность без подмены требования форматом.",
    "Capture user, need, and value without letting the format replace the requirement.",
  ),
  template(
    "acceptance-criteria",
    "Критерии приёмки",
    "Acceptance Criteria",
    "control",
    "Сделать проверку результата однозначной.",
    "Make outcome verification unambiguous.",
  ),
  template(
    "definition-ready",
    "Критерии готовности к работе",
    "Definition of Ready",
    "control",
    "Установить минимальные условия для начала работы.",
    "Set minimum conditions for starting work.",
  ),
  template(
    "definition-done",
    "Критерии готовности",
    "Definition of Done",
    "control",
    "Установить общий уровень качества завершённой работы.",
    "Set a shared quality bar for completed work.",
  ),
  template(
    "milestone-plan",
    "План контрольных точек",
    "Milestone Plan",
    "plan",
    "Показать значимые точки результата и решений.",
    "Show meaningful outcome and decision points.",
  ),
  template(
    "roadmap",
    "Дорожная карта",
    "Project Roadmap",
    "plan",
    "Связать темы, измеримые результаты и выпуски во времени.",
    "Connect themes, outcomes, and releases over time.",
  ),
  template(
    "release-plan",
    "План релиза",
    "Release Plan",
    "plan",
    "Согласовать границы выпуска, готовность и решение о запуске.",
    "Align release scope, readiness, and go/no-go.",
  ),
  template(
    "sprint-goal",
    "Цель спринта",
    "Sprint Goal",
    "strategy",
    "Дать спринту единую цель вместо набора несвязанных рабочих элементов.",
    "Give a Sprint one goal rather than unrelated items.",
  ),
  template(
    "risk-register",
    "Реестр рисков",
    "Risk Register",
    "log",
    "Управлять неопределённостями до того, как они станут проблемами.",
    "Manage uncertainties before they become issues.",
  ),
  template(
    "raid-log",
    "Журнал RAID",
    "RAID Log",
    "log",
    "Вести риски, допущения, проблемы и зависимости в единой контрольной точке.",
    "Maintain risks, assumptions, issues, and dependencies in one control point.",
  ),
  template(
    "issue-log",
    "Журнал проблем",
    "Issue Log",
    "log",
    "Назначить действия по уже возникшим проблемам.",
    "Assign action for problems already occurring.",
  ),
  template(
    "assumption-log",
    "Журнал допущений",
    "Assumption Log",
    "log",
    "Проверять утверждения, на которых держится план.",
    "Test the assumptions the plan relies on.",
  ),
  template(
    "dependency-log",
    "Журнал зависимостей",
    "Dependency Log",
    "log",
    "Управлять внешними и внутренними блокирующими связями.",
    "Manage external and internal blocking relationships.",
  ),
  template(
    "decision-log",
    "Журнал решений",
    "Decision Log",
    "log",
    "Сохранить контекст и последствия ключевых решений.",
    "Preserve context and consequences of key decisions.",
  ),
  template(
    "stakeholder-register",
    "Реестр заинтересованных сторон",
    "Stakeholder Register",
    "log",
    "Понять ожидания и нужную вовлечённость участников.",
    "Understand stakeholder expectations and needed engagement.",
  ),
  template(
    "stakeholder-matrix",
    "Матрица заинтересованных сторон",
    "Stakeholder Matrix",
    "strategy",
    "Спланировать коммуникацию с учётом влияния и заинтересованности.",
    "Plan proportionate communication by influence and interest.",
  ),
  template(
    "raci",
    "RACI",
    "RACI",
    "control",
    "Снять неоднозначность ответственности за результаты поставки и решения.",
    "Remove ambiguity in accountability for deliverables and decisions.",
  ),
  template(
    "communication-plan",
    "План коммуникаций",
    "Communication Plan",
    "plan",
    "Определить кому, зачем, что, когда и кем сообщается.",
    "Define who needs what information, why, when, and from whom.",
  ),
  template(
    "meeting-agenda",
    "Повестка встречи",
    "Meeting Agenda",
    "meeting",
    "Подготовить решение или синхронизацию с ясным результатом.",
    "Prepare a decision or alignment session with a clear output.",
  ),
  template(
    "meeting-minutes",
    "Протокол встречи",
    "Meeting Minutes",
    "meeting",
    "Зафиксировать решения, действия и владельцев.",
    "Record decisions, actions, and owners.",
  ),
  template(
    "kickoff",
    "Стартовая встреча",
    "Kickoff",
    "meeting",
    "Синхронизировать цель, роли, способ работы и ближайший шаг.",
    "Align purpose, roles, way of working, and next step.",
  ),
  template(
    "status-report",
    "Статус-отчёт",
    "Status Report",
    "control",
    "Сфокусировать заинтересованные стороны на изменениях и решениях.",
    "Focus stakeholders on changes and decisions.",
  ),
  template(
    "steering-pack",
    "Пакет для руководящего комитета",
    "Steering Committee Pack",
    "control",
    "Подготовить управленческие решения без операционного шума.",
    "Prepare governance decisions without operational noise.",
  ),
  template(
    "change-request",
    "Запрос на изменение",
    "Change Request",
    "control",
    "Оценить последствия изменения до согласования.",
    "Assess change impact before approval.",
  ),
  template(
    "change-log",
    "Журнал изменений",
    "Change Log",
    "log",
    "Сохранить историю изменений границ проекта и базового плана.",
    "Preserve scope and baseline change history.",
  ),
  template(
    "quality-plan",
    "План качества",
    "Quality Plan",
    "plan",
    "Определить цели качества, проверки и условия приёмки.",
    "Define quality goals, checks, and acceptance.",
  ),
  template(
    "acceptance-checklist",
    "Чек-лист приёмки",
    "Test / Acceptance Checklist",
    "control",
    "Не пропустить проверяемые условия готовности.",
    "Avoid missing verifiable readiness conditions.",
  ),
  template(
    "capacity-plan",
    "План доступной мощности",
    "Capacity Plan",
    "plan",
    "Сопоставить доступную мощность с плановой работой.",
    "Match available capacity to planned work.",
  ),
  template(
    "resource-plan",
    "Ресурсный план",
    "Resource Plan",
    "plan",
    "Выявить перегрузку, пробелы и конфликты распределения ресурсов.",
    "Expose overload, gaps, and allocation conflicts.",
  ),
  template(
    "budget-tracker",
    "Трекер бюджета",
    "Budget Tracker",
    "control",
    "Сравнивать план, факт, обязательства и прогноз.",
    "Compare baseline, actual, committed, and forecast.",
  ),
  template(
    "vendor-evaluation",
    "Оценка поставщика",
    "Vendor Evaluation",
    "control",
    "Сравнить поставщиков по явным критериям и рискам.",
    "Compare vendors against explicit criteria and risks.",
  ),
  template(
    "procurement-tracker",
    "Трекер закупок",
    "Procurement Tracker",
    "log",
    "Управлять результатами поставки, сроками и зависимостями поставщиков.",
    "Manage vendor deliverables, dates, and dependencies.",
  ),
  template(
    "retrospective",
    "Ретроспектива",
    "Retrospective",
    "meeting",
    "Выбрать одно-два проверяемых улучшения способа работы.",
    "Choose one or two testable improvements to the way of working.",
  ),
  template(
    "lessons-learned",
    "Извлечённые уроки",
    "Lessons Learned",
    "strategy",
    "Превратить опыт в рекомендацию для следующего контекста.",
    "Turn experience into a recommendation for the next context.",
  ),
  template(
    "postmortem",
    "Разбор инцидента",
    "Postmortem",
    "meeting",
    "Без обвинений разобрать последствия, причины и предотвращение повторения.",
    "Review impact, causes, and prevention without blame.",
  ),
  template(
    "handover",
    "Чек-лист передачи",
    "Handover Checklist",
    "control",
    "Передать ответственность, знания, доступы и незавершённые вопросы.",
    "Transfer ownership, knowledge, access, and unresolved items.",
  ),
  template(
    "closure-report",
    "Отчёт о закрытии",
    "Closure Report",
    "control",
    "Зафиксировать приёмку, показатели и дальнейшее измерение выгод.",
    "Record acceptance, performance, and future benefits measurement.",
  ),
  template(
    "closure-checklist",
    "Чек-лист закрытия",
    "Project Closure Checklist",
    "control",
    "Закрыть договоры, финансы, архивы, передачу ответственности и извлечённые уроки.",
    "Close contracts, finance, archives, handover, and lessons.",
  ),
];

export type Playbook = {
  slug: string;
  title: Bi;
  diagnose: Bi[];
  immediate: Bi[];
  next: Bi[];
  stabilize: Bi[];
  prevent: Bi[];
  metrics: Bi[];
  antiPatterns: Bi[];
};
const pb = (
  slug: string,
  ru: string,
  en: string,
  signalRu: string,
  signalEn: string,
  actionRu: string,
  actionEn: string,
  metricRu: string,
  metricEn: string,
): Playbook => ({
  slug,
  title: { ru, en },
  diagnose: [
    { ru: signalRu, en: signalEn },
    {
      ru: "Отделите наблюдаемый факт от интерпретации и найдите ограничение системы.",
      en: "Separate observed fact from interpretation and identify the system constraint.",
    },
  ],
  immediate: [
    { ru: actionRu, en: actionEn },
    {
      ru: "Назначьте одного владельца следующего решения и срок проверки.",
      en: "Assign one owner for the next decision and a review date.",
    },
  ],
  next: [
    {
      ru: "В следующий рабочий цикл соберите минимальные данные, перепланируйте затронутую работу и сообщите последствия.",
      en: "In the next working cycle, collect minimum evidence, replan affected work, and communicate impact.",
    },
  ],
  stabilize: [
    {
      ru: "Сократите активную работу, сделайте приоритеты и зависимости явными, восстановите ритм контроля.",
      en: "Reduce active work, expose priorities and dependencies, and restore a control cadence.",
    },
  ],
  prevent: [
    {
      ru: "Добавьте раннее условие срабатывания, владельца и регулярный обзор — не новый отчёт ради отчёта.",
      en: "Add an early trigger, owner, and regular review—not another report for its own sake.",
    },
  ],
  metrics: [
    { ru: metricRu, en: metricEn },
    {
      ru: "Возраст блокировок и время до решения.",
      en: "Blocker age and time to decision.",
    },
  ],
  antiPatterns: [
    {
      ru: "Обещать новую дату до анализа причин и компромиссов.",
      en: "Promise a new date before analyzing causes and trade-offs.",
    },
    {
      ru: "Увеличивать параллельную работу, чтобы создать видимость скорости.",
      en: "Increase parallel work to create an appearance of speed.",
    },
  ],
});

export const playbooks: Playbook[] = [
  pb(
    "project-late",
    "Проект опаздывает",
    "Project is late",
    "Контрольные точки системно сдвигаются; критическая цепочка не ясна.",
    "Milestones move repeatedly; the critical chain is unclear.",
    "Заморозьте новые обязательства, пересчитайте критический путь и отделите устранимую задержку от уже понесённой.",
    "Freeze new commitments, recalculate the critical path, and separate recoverable from sunk delay.",
    "Прогноз контрольной точки и общий временной резерв.",
    "Milestone forecast and total float.",
  ),
  pb(
    "fixed-deadline",
    "Дедлайн нельзя сдвинуть",
    "Deadline cannot move",
    "Дата внешне фиксирована, но границы проекта и допущения о качестве не пересмотрены.",
    "The date is externally fixed but scope and quality assumptions remain unchanged.",
    "Зафиксируйте дату как ограничение; предложите варианты по объёму работ, последовательности, ресурсам и принятию риска.",
    "Treat the date as a constraint; offer options across scope, sequence, resources, and risk acceptance.",
    "Диаграмма прироста объёма работ и критерии готовности.",
    "Scope burn-up and readiness criteria.",
  ),
  pb(
    "scope-growth",
    "Границы проекта постоянно расширяются",
    "Scope keeps growing",
    "Новые запросы поступают без оценки влияния и решения об исключении другой работы.",
    "Requests enter without impact assessment or removal decisions.",
    "Создайте границу изменений: каждое добавление получает оценку влияния и компенсирующий компромисс.",
    "Create a change boundary: every addition gets impact analysis and a compensating trade-off.",
    "Добавленный и исключённый объём работ, отклонение сроков.",
    "Scope added/removed and schedule variance.",
  ),
  pb(
    "unclear-requirements",
    "Требования неясны",
    "Requirements are unclear",
    "Команда спорит о решении, не понимая пользователя, измеримого результата или условий приёмки.",
    "The team debates solutions without a shared user, outcome, or acceptance view.",
    "Выберите самый рискованный вопрос и проведите короткий цикл исследования и проверки.",
    "Choose the riskiest question and run a short discovery/validation loop.",
    "Доля проверенных допущений.",
    "Assumption validation rate.",
  ),
  pb(
    "changing-priorities",
    "Заинтересованная сторона меняет приоритеты",
    "Stakeholder changes priorities",
    "Приоритет меняется чаще, чем команда может завершать работу.",
    "Priority changes faster than the team can finish work.",
    "Согласуйте ритм принятия решений и цену переключения; новые срочные элементы должны явно вытеснять текущие.",
    "Agree a decision cadence and switching cost; new urgent items explicitly displace current work.",
    "Доля прерываний и объём брошенной работы.",
    "Interrupt rate and abandoned work.",
  ),
  pb(
    "sponsor-unavailable",
    "Спонсор недоступен",
    "Sponsor unavailable",
    "Решения выходят за допустимые отклонения и остаются без ответственного владельца.",
    "Decisions exceed tolerance and lack an accountable owner.",
    "Соберите пакет решения: вопрос, варианты, рекомендация, срок и последствие бездействия.",
    "Prepare a decision pack: question, options, recommendation, deadline, consequence of no decision.",
    "Задержка принятия решений.",
    "Decision latency.",
  ),
  pb(
    "team-overloaded",
    "Команда перегружена",
    "Team overloaded",
    "Распределённая нагрузка превышает доступную мощность, WIP растёт, время цикла ухудшается.",
    "Allocation exceeds capacity, WIP grows, and cycle time deteriorates.",
    "Остановите старт новой работы и завершите/снимите часть WIP.",
    "Stop starting work and finish or remove part of WIP.",
    "WIP, возраст рабочих элементов и динамика переработок.",
    "WIP, work item age, overtime trend.",
  ),
  pb(
    "key-person",
    "Ключевой человек недоступен",
    "Key person unavailable",
    "Знания или полномочия согласования сосредоточены в одной точке.",
    "Knowledge or approval is concentrated in one person.",
    "Разделите блокирующую и неблокирующую работу; назначьте временного владельца решения.",
    "Separate blocking from non-blocking work; assign a temporary decision owner.",
    "Фактор незаменимости и возраст блокировки.",
    "Bus factor and blocked age.",
  ),
  pb(
    "missed-commitments",
    "Команда не выполняет обязательства",
    "Team misses commitments",
    "Перенос незавершённой работы повторяется, но планирование не меняется.",
    "Carry-over repeats while planning remains unchanged.",
    "Сравните спрос, доступную мощность, срочные задачи и размер элементов; уменьшите пакет и объём обязательств.",
    "Compare demand, capacity, interrupts, and item size; reduce batch and commitment.",
    "Надёжность обязательств и размер рабочего элемента.",
    "Commitment reliability and item size.",
  ),
  pb(
    "too-much-wip",
    "Слишком много WIP",
    "Too much WIP",
    "Много начато, мало завершено; возраст незавершённой работы растёт.",
    "Much is started, little is finished; aging rises.",
    "Временно снизьте лимиты WIP, объедините команду вокруг старейших элементов и запретите скрытые очереди.",
    "Temporarily lower WIP limits, swarm on oldest items, and expose hidden queues.",
    "WIP, пропускная способность, время цикла и возраст элементов.",
    "WIP, throughput, cycle time, age.",
  ),
  pb(
    "all-high-priority",
    "Всё имеет высокий приоритет",
    "Everything is high priority",
    "Метка приоритета не меняет последовательность решений.",
    "Priority labels do not change decision sequence.",
    "Попросите ранжированный порядок и выберите критерий стоимости задержки.",
    "Require rank order and choose a cost-of-delay criterion.",
    "Количество одновременных приоритетов.",
    "Number of concurrent priorities.",
  ),
  pb(
    "backlog-chaos",
    "Бэклог превратился в хаос",
    "Backlog is chaos",
    "Элементы дублируются, устарели и не имеют измеримого результата или владельца.",
    "Items are duplicated, stale, and lack outcome or owner.",
    "Архивируйте устаревшие элементы, объедините дубликаты и выделите горизонт готовности на 1–2 цикла.",
    "Archive stale items, merge duplicates, and define a ready horizon of 1–2 cycles.",
    "Возраст бэклога и доля готовых элементов.",
    "Backlog age and ready ratio.",
  ),
  pb(
    "estimation-wrong",
    "Оценки системно ошибочны",
    "Estimation is consistently wrong",
    "Ошибка направлена в одну сторону и не учитывается в прогнозе.",
    "Error is directional and ignored in forecasts.",
    "Сегментируйте типы работ, сравните прогноз с фактом, используйте диапазоны.",
    "Segment work types, compare forecast to actual, and use ranges.",
    "Распределение ошибки прогноза.",
    "Forecast error distribution.",
  ),
  pb(
    "no-goal",
    "У проекта нет ясной цели",
    "Project has no clear goal",
    "Есть список результатов, но неизвестно, какое изменение считается успехом.",
    "There is an output list but no defined successful change.",
    "Остановите детальное планирование и согласуйте проблему, измеримый результат, метрику и владельца.",
    "Pause detailed planning and align problem, outcome, measure, and owner.",
    "Метрика результата и согласованность решения.",
    "Outcome measure and decision alignment.",
  ),
  pb(
    "no-owner",
    "У проекта нет владельца",
    "Project has no owner",
    "Никто не может согласовать компромисс или подтвердить результат.",
    "No one can make trade-offs or accept the outcome.",
    "Эскалируйте пробел в управлении; назначьте ответственного спонсора до принятия новых обязательств.",
    "Escalate the governance gap; assign an accountable sponsor before new commitments.",
    "Решения без владельца.",
    "Unowned decisions.",
  ),
  pb(
    "client-unhappy",
    "Клиент недоволен",
    "Client dissatisfaction",
    "Эмоциональная оценка не разложена на разрывы в ожиданиях, качестве, сроках или коммуникации.",
    "Emotional feedback is not decomposed into expectation, quality, timing, or communication gaps.",
    "Признайте последствия, уточните наблюдаемые разрывы, согласуйте восстановительные действия и контрольную встречу.",
    "Acknowledge impact, clarify observable gaps, agree recovery actions and a check-in.",
    "Открытые разрывы и проверка уверенности.",
    "Open gaps and confidence check.",
  ),
  pb(
    "stakeholder-conflict",
    "Конфликт заинтересованных сторон",
    "Stakeholder conflict",
    "У сторон разные интересы, критерии или права принятия решений.",
    "Parties have different interests, criteria, or decision rights.",
    "Отделите позиции от интересов; согласуйте критерии и владельца решения.",
    "Separate positions from interests; agree criteria and decision owner.",
    "Задержка решений и число повторно открытых решений.",
    "Decision latency and reopened decisions.",
  ),
  pb(
    "no-authority",
    "У руководителя проекта нет полномочий",
    "PM has no authority",
    "Ожидания ответственности выше предоставленных прав принятия решений.",
    "Accountability expectations exceed granted decision rights.",
    "Сделайте разрыв явным: какие решения нужны, кто их принимает и каков маршрут эскалации.",
    "Expose the gap: decisions needed, decision owners, and escalation path.",
    "Число эскалаций и время ожидания.",
    "Escalations and waiting time.",
  ),
  pb(
    "cross-team-block",
    "Межкомандная зависимость блокирует",
    "Cross-team dependency blocks delivery",
    "У зависимости нет владельцев с обеих сторон, даты или условий приёмки.",
    "The dependency lacks bilateral owner, date, or acceptance.",
    "Согласуйте связь: результат предшественника, потребность преемника, владельцев с обеих сторон, дату и запасной вариант.",
    "Create a handshake: predecessor output, successor need, owners on both sides, date, fallback.",
    "Возраст зависимости и доля нарушений.",
    "Dependency age and breach rate.",
  ),
  pb(
    "vendor-late",
    "Поставщик опаздывает",
    "External vendor is late",
    "Договорная контрольная точка нарушена, но влияние и альтернативы не просчитаны.",
    "A contract milestone slipped without quantified impact or alternatives.",
    "Подтвердите факты, влияние на критический путь, план восстановления и договорную эскалацию.",
    "Confirm facts, critical-path impact, recovery plan, and contractual escalation.",
    "Отклонение контрольных точек поставщика.",
    "Vendor milestone variance.",
  ),
  pb(
    "high-risk-release",
    "Релиз высокого риска",
    "High-risk release",
    "Масштаб возможных последствий высок, готовность и откат не подтверждены.",
    "Blast radius is high and rollback/readiness are unproven.",
    "Определите критерии запуска или остановки, владельца отката, мониторинг и поэтапное расширение.",
    "Define go/no-go criteria, rollback owner, monitoring, and staged exposure.",
    "Пробелы готовности и время восстановления.",
    "Readiness gaps and recovery time.",
  ),
  pb(
    "budget-overrun",
    "Бюджет превышен",
    "Budget overrun",
    "Факт и обязательства выше базового плана без нового прогноза.",
    "Actual/committed costs exceed baseline without a new forecast.",
    "Разделите отклонение на ставку, объём, границы работ и сроки; пересчитайте EAC и варианты.",
    "Split variance into rate, volume, scope, and timing; recalculate EAC and options.",
    "CPI, EAC, VAC.",
    "CPI, EAC, VAC.",
  ),
  pb(
    "unknown-budget",
    "Бюджет неизвестен",
    "Unknown budget",
    "Нет владельца затрат, базового плана или доступного диапазона решений.",
    "There is no cost owner, baseline, or decision range.",
    "Соберите категории затрат, обязательства и диапазон; назначьте владельца финансовых данных.",
    "Collect cost categories, commitments, and range; assign financial data ownership.",
    "Покрытие прогноза.",
    "Forecast coverage.",
  ),
  pb(
    "health-unclear",
    "Состояние проекта неясно",
    "Project health is unclear",
    "Одна субъективная оценка скрывает разные измерения.",
    "One subjective score hides different dimensions.",
    "Оцените сроки, объём работ, бюджет, риски, блокировки, доступную мощность и согласованность отдельно по явным правилам.",
    "Assess schedule, scope, budget, risk, blockers, capacity, and alignment separately with rules.",
    "Неизвестные измерения состояния.",
    "Unknown health dimensions.",
  ),
  pb(
    "too-many-meetings",
    "Слишком много встреч",
    "Too many meetings",
    "Встречи расходуют доступную мощность, не создавая уникальных решений или результатов.",
    "Meetings consume capacity without unique decisions or outputs.",
    "Отмените встречи без владельца и результата; объедините сведения о состоянии в асинхронном документе.",
    "Cancel meetings without an owner/output; consolidate status in an async artifact.",
    "Часы встреч и результативность решений.",
    "Meeting hours and decision yield.",
  ),
  pb(
    "useless-meetings",
    "Встречи бесполезны",
    "No useful meetings",
    "Повестка описывает темы, а не решения; действия не отслеживаются.",
    "The agenda lists topics, not decisions; actions are not tracked.",
    "Перепишите повестку как вопросы и решения, добавьте материалы для предварительного чтения и владельца протокола.",
    "Rewrite the agenda as questions/decisions; add a pre-read and minutes owner.",
    "Закрытые действия и решения на встречу.",
    "Actions closed and decisions per meeting.",
  ),
  pb(
    "retro-no-change",
    "Ретро ничего не меняет",
    "Retrospective changes nothing",
    "Действия слишком общие, без владельца и последующей проверки.",
    "Actions are vague, unowned, and never reviewed.",
    "Выберите один наблюдаемый эксперимент, владельца, срок и ожидаемый сигнал.",
    "Choose one observable experiment, owner, date, and expected signal.",
    "Выполнение действий по улучшению.",
    "Improvement action completion.",
  ),
  pb(
    "fear",
    "Команда скрывает проблемы",
    "Team is afraid to surface problems",
    "Плохие новости появляются поздно; обсуждение ищет виновного.",
    "Bad news arrives late; discussions seek blame.",
    "Лидер первым признаёт неопределённость; разберите систему и защитите раннюю эскалацию.",
    "Leader names uncertainty first; examine the system and protect early escalation.",
    "Время до выявления проблемы и анонимная проверка психологической безопасности.",
    "Time to surface and anonymous safety pulse.",
  ),
  pb(
    "bad-status",
    "Статус-отчёты бесполезны",
    "Status reports are useless",
    "Отчёт перечисляет действия, но не изменения, прогноз или решения.",
    "The report lists activity but not change, forecast, or decisions.",
    "Оставьте: что изменилось, прогноз, главные риски, требуемые решения и помощь.",
    "Keep only: what changed, forecast, top risks, decisions/help needed.",
    "Результативность решений и актуальность отчёта.",
    "Decision yield and report freshness.",
  ),
  pb(
    "heavy-governance",
    "Модель управления слишком тяжёлая",
    "Governance too heavy",
    "Задержка согласования выше снижения риска; данные дублируются.",
    "Approval latency exceeds risk reduction; data is duplicated.",
    "Свяжите каждую контрольную точку с риском или решением; удалите артефакты без потребителя.",
    "Map every gate to a risk/decision; remove artifacts without a consumer.",
    "Срок согласования.",
    "Approval lead time.",
  ),
  pb(
    "no-governance",
    "Модель управления отсутствует",
    "Governance nonexistent",
    "Нет допустимых отклонений, прав принятия решений или эскалации.",
    "There are no tolerances, decision rights, or escalation paths.",
    "Определите спонсора, три ключевых решения, пороговые значения и ритм обзора.",
    "Define sponsor, three key decisions, thresholds, and review cadence.",
    "Неразрешённые исключения.",
    "Unresolved exceptions.",
  ),
  pb(
    "agile-no-plan",
    "Agile используют как отказ от планирования",
    "Agile is used as excuse for no planning",
    "Нет цели продукта, прогноза, зависимостей или критериев готовности.",
    "There is no product goal, forecast, dependencies, or readiness view.",
    "Создайте адаптивный план: цель, упорядоченный бэклог, ближайшее обязательство и диапазон прогноза.",
    "Create an adaptive plan: goal, ordered backlog, near-term commitment, forecast range.",
    "Прогресс цели и диапазон прогноза.",
    "Goal progress and forecast range.",
  ),
  pb(
    "waterfall-change",
    "Каскадная модель при изменчивых требованиях",
    "Waterfall where requirements change",
    "Темп изменений выше мощности формального контроля; обратная связь приходит поздно.",
    "Change rate exceeds formal control capacity; feedback arrives late.",
    "Сохраните необходимые контрольные точки, но перенесите исследование решения в короткие циклы проверки.",
    "Keep necessary gates but move solution discovery into short validation loops.",
    "Срок прохождения изменения и объём переделок.",
    "Change lead time and rework.",
  ),
  pb(
    "framework-soup",
    "Гибридный подход стал смесью методик",
    "Hybrid became framework soup",
    "Практики конфликтуют, роли дублируются, ритм управления перегружен.",
    "Practices conflict, roles duplicate, and cadence is overloaded.",
    "Разделите управление, планирование и поставку результата; для каждой практики назовите проблему, владельца и правило остановки.",
    "Separate governance/planning/delivery; name the problem, owner, and stop rule for each practice.",
    "Процессная нагрузка и конфликтующие правила.",
    "Process load and conflicting policies.",
  ),
  pb(
    "rescue",
    "Спасти проект",
    "Project needs rescue",
    "Цель, объём работ, ответственность, сроки и уверенность расходятся.",
    "Objective, scope, ownership, schedule, and confidence diverge.",
    "Остановить новые обязательства. Стабилизировать факты и безопасность. Перепланировать варианты. Согласовать решение. Провести короткий цикл подтверждения.",
    "Stop new commitments. Stabilize facts and safety. Replan options. Align a decision. Deliver a short proof cycle.",
    "Критические блокировки, возраст решений и уверенность в прогнозе.",
    "Critical blockers, decision age, forecast confidence.",
  ),
  pb(
    "handover",
    "Передать проект",
    "Project handover",
    "Неявные знания, доступы и незавершённая работа не имеют нового владельца.",
    "Tacit knowledge, access, and unresolved work lack a new owner.",
    "Составьте карту передачи: решения, риски, контакты, артефакты, доступы и ближайшие 30 дней.",
    "Build a handover map: decisions, risks, contacts, artifacts, access, next 30 days.",
    "Принятые результаты передачи.",
    "Accepted handover items.",
  ),
  pb(
    "join-midway",
    "Руководитель проекта подключается в середине",
    "PM joins project midway",
    "Документы расходятся с реальностью, история решений скрыта.",
    "Documents differ from reality and decision history is hidden.",
    "Проведите обзор подтверждений: спонсор, команда, заказчик, план, поток, риски и решения.",
    "Run an evidence tour: sponsor, team, customer, plan, flow, risks, decisions.",
    "Число снятых неопределённостей за неделю.",
    "Unknowns retired per week.",
  ),
  pb(
    "close-failing",
    "Закрыть неуспешный проект",
    "Closing a failing project",
    "Стоимость продолжения превышает ожидаемую ценность, но уже понесённые затраты влияют на решение.",
    "Continuation cost exceeds expected value but sunk cost biases the decision.",
    "Подготовьте обоснование остановки, защитите людей и данные, определите передачу, уроки и остаточные обязательства.",
    "Prepare a stop case, protect people/data, define handover and lessons, and name residual obligations.",
    "Закрытые остаточные обязательства.",
    "Residual obligations closed.",
  ),
  pb(
    "start-zero",
    "Начать проект с нуля",
    "Starting project from zero",
    "Есть идея, но нет владельца проблемы, измеримого результата или ограничений.",
    "There is an idea but no problem owner, outcome, or constraints.",
    "Согласуйте проблему, спонсора, метрику результата, границы и первую проверку неопределённости.",
    "Align problem, sponsor, outcome measure, boundaries, and the first uncertainty test.",
    "Время до первого подтверждённого вывода.",
    "Time to first validated learning.",
  ),
];

export const knowledgeDomains: Bi[] = [
  { ru: "Основы", en: "Fundamentals" },
  { ru: "Управление и полномочия", en: "Governance" },
  { ru: "Ценность", en: "Value" },
  { ru: "Содержание проекта", en: "Scope" },
  { ru: "Требования", en: "Requirements" },
  { ru: "Сроки", en: "Schedule" },
  { ru: "Стоимость", en: "Cost" },
  { ru: "Риски", en: "Risk" },
  { ru: "Качество", en: "Quality" },
  { ru: "Ресурсы", en: "Resources" },
  { ru: "Команда", en: "Team" },
  { ru: "Лидерство", en: "Leadership" },
  { ru: "Заинтересованные стороны", en: "Stakeholders" },
  { ru: "Коммуникации", en: "Communication" },
  { ru: "Закупки", en: "Procurement" },
  { ru: "Изменения", en: "Change" },
  { ru: "Создание результата", en: "Delivery" },
  { ru: "Agile", en: "Agile" },
  { ru: "Поток", en: "Flow" },
  { ru: "Измерение", en: "Measurement" },
  { ru: "Прогнозирование", en: "Forecasting" },
  { ru: "Восстановление проекта", en: "Project Recovery" },
  { ru: "Закрытие", en: "Closure" },
  { ru: "PMO", en: "PMO" },
  { ru: "Основы программ", en: "Program basics" },
  { ru: "Основы портфелей", en: "Portfolio basics" },
];

export { glossary } from "./glossary-seed.ts";
import { glossary } from "./glossary-seed.ts";

export const contentCounts = {
  methods: methods.length,
  templates: templates.length,
  playbooks: playbooks.length,
  glossary: glossary.length,
  knowledge: knowledgeDomains.length,
};
