import type { Locale } from "@/domain/schemas";

export type Bi = { ru:string; en:string };
export const pick=(value:Bi,locale:Locale)=>value[locale];
export type Source={id:string;title:string;organization:string;version:string;published:string;checked:string;url:string;authority:"Standard"|"Official Guide"|"Practice";notes:Bi};

export const sources:Source[]=[
  {id:"pmbok8",title:"PMBOK® Guide and The Standard for Project Management",organization:"Project Management Institute",version:"8th edition",published:"2025",checked:"2026-09-04",url:"https://www.pmi.org/standards/pmbok",authority:"Standard",notes:{ru:"Официальный стандарт PMI; изложение PMWORK оригинально.",en:"Official PMI standard; PMWORK uses original explanations."}},
  {id:"agile2",title:"Agile Practice Guide",organization:"Project Management Institute",version:"2nd edition",published:"2025",checked:"2026-09-04",url:"https://www.pmi.org/standards/agile",authority:"Official Guide",notes:{ru:"Официальное руководство по контекстному применению adaptive practices.",en:"Official guidance for contextual use of adaptive practices."}},
  {id:"scrum2020",title:"The Scrum Guide",organization:"Scrum.org / Scrum Inc.",version:"November 2020",published:"2020-11",checked:"2026-09-04",url:"https://scrumguides.org/scrum-guide.html",authority:"Official Guide",notes:{ru:"Актуальная проверенная версия Scrum Guide.",en:"Current verified Scrum Guide version."}},
  {id:"kanban2025",title:"The Kanban Guide",organization:"Kanban Guides",version:"May 2025",published:"2025-05",checked:"2026-09-04",url:"https://kanbanguides.org/the-kanban-guide/2025.5/",authority:"Official Guide",notes:{ru:"Определяет workflow, WIP, throughput, work item age и cycle time.",en:"Defines workflow, WIP, throughput, work item age, and cycle time."}},
  {id:"prince2v7",title:"PRINCE2 Project Management",organization:"PeopleCert",version:"Version 7",published:"2023",checked:"2026-09-04",url:"https://www.peoplecert.org/browse-certifications/project-programme-and-portfolio-management/PRINCE2-2",authority:"Official Guide",notes:{ru:"Официальная страница владельца framework.",en:"Official framework owner page."}},
  {id:"iso21502",title:"ISO 21502:2020 Project, programme and portfolio management — Guidance on project management",organization:"ISO",version:"ISO 21502:2020",published:"2020",checked:"2026-09-04",url:"https://www.iso.org/standard/74947.html",authority:"Standard",notes:{ru:"Международный стандарт; полный текст не воспроизводится.",en:"International standard; full text is not reproduced."}},
  {id:"agilemanifesto",title:"Manifesto for Agile Software Development",organization:"Agile Manifesto authors",version:"2001",published:"2001",checked:"2026-09-04",url:"https://agilemanifesto.org/",authority:"Official Guide",notes:{ru:"Первичный источник ценностей и принципов Agile.",en:"Primary source for Agile values and principles."}},
  {id:"wcag22",title:"Web Content Accessibility Guidelines",organization:"W3C",version:"WCAG 2.2",published:"2023",checked:"2026-09-04",url:"https://www.w3.org/TR/WCAG22/",authority:"Standard",notes:{ru:"Целевая планка интерфейса — уровень AA.",en:"The interface targets Level AA."}},
];

export type Method={slug:string;title:Bi;summary:Bi;origin:Bi;principles:Bi[];flow:Bi;roles:Bi;artifacts:Bi;cadence:Bi;metrics:Bi;strengths:Bi;limitations:Bi;prerequisites:Bi;bestFit:Bi;poorFit:Bi;antiPatterns:Bi;tailoring:Bi;combinations:Bi;checklist:Bi[];sourceIds:string[];version:string;updatedAt:string};
const m=(slug:string,ru:string,en:string,summaryRu:string,summaryEn:string,flowRu:string,flowEn:string,bestRu:string,bestEn:string,limitsRu:string,limitsEn:string,sourceIds:string[],version="Practice") :Method=>({
  slug,title:{ru,en},summary:{ru:summaryRu,en:summaryEn},origin:{ru:"Возник как ответ на определённый контекст управления; используйте происхождение для понимания допущений, а не как знак универсальности.",en:"Emerged for a specific management context; use its origin to understand assumptions, not as proof of universality."},
  principles:[{ru:"Явно определить способ принятия решений и поток работы.",en:"Make decision rights and work flow explicit."},{ru:"Подбирать контроль пропорционально риску и неопределённости.",en:"Tailor control to risk and uncertainty."},{ru:"Замыкать цикл план → работа → обратная связь → адаптация.",en:"Close the plan → work → feedback → adaptation loop."}],
  flow:{ru:flowRu,en:flowEn},roles:{ru:"Роли определяются выбранным подходом; владелец результата, руководитель проекта и исполнители должны иметь ясные полномочия.",en:"Roles follow the chosen approach; outcome owner, project lead, and delivery team need clear decision rights."},
  artifacts:{ru:"Используйте только те артефакты, которые поддерживают решение, координацию, проверку или ответственность.",en:"Use only artifacts that support a decision, coordination, verification, or accountability."},
  cadence:{ru:"Каденция зависит от скорости обратной связи, стоимости координации и риска задержки.",en:"Cadence depends on feedback speed, coordination cost, and delay risk."},metrics:{ru:"Смотрите на результат, predictability, flow, качество и риск — не на объём активности.",en:"Track outcomes, predictability, flow, quality, and risk—not activity volume."},
  strengths:{ru:"Даёт общую операционную модель и язык координации, если совпадает с контекстом.",en:"Provides a shared operating model and coordination language when context fits."},limitations:{ru:limitsRu,en:limitsEn},prerequisites:{ru:"Общая цель, явные владельцы, доступ к обратной связи и дисциплина обновления рабочих данных.",en:"Shared goal, explicit ownership, access to feedback, and discipline in updating work data."},bestFit:{ru:bestRu,en:bestEn},poorFit:{ru:"Среда, где ключевые допущения подхода отсутствуют или конфликтуют с governance.",en:"Environments where core assumptions are absent or conflict with governance."},antiPatterns:{ru:"Механическое выполнение церемоний; показатели как цель; добавление слоёв без удаления лишних.",en:"Mechanical ceremonies; metrics as targets; adding layers without removing waste."},tailoring:{ru:"Начните с минимально достаточной структуры и усиливайте контроль только по наблюдаемой потребности.",en:"Start with minimum sufficient structure and add control only for an observed need."},combinations:{ru:"Комбинируйте governance, planning и execution как отдельные слои; явно фиксируйте конфликты допущений.",en:"Combine governance, planning, and execution as separate layers; expose conflicting assumptions."},
  checklist:[{ru:"Сформулировать ожидаемый результат и ограничения.",en:"State the expected outcome and constraints."},{ru:"Определить владельцев решений и cadence.",en:"Define decision owners and cadence."},{ru:"Выбрать минимум артефактов и метрик.",en:"Select the minimum artifacts and metrics."},{ru:"Провести review через один рабочий цикл.",en:"Review after one working cycle."}],sourceIds,version,updatedAt:"2026-09-04"});

export const methods:Method[]=[
  m("predictive","Предиктивное управление","Predictive project management","Детальное предварительное планирование и контроль относительно baseline.","Plan substantial scope in advance and control delivery against a baseline.","Инициация → планирование → исполнение → контроль → закрытие.","Initiate → plan → execute → control → close.","Стабильный scope, формальные approvals, высокая стоимость изменений.","Stable scope, formal approvals, high change cost.","Плохо переносит частую смену требований и позднюю обратную связь.","Handles frequent requirement change and late feedback poorly.",["pmbok8","iso21502"]),
  m("waterfall","Waterfall","Waterfall","Последовательная модель фаз с формализованными переходами.","Sequential phase model with formal transitions.","Требования → design → build → verify → transition.","Requirements → design → build → verify → transition.","Повторяемая работа с предсказуемыми interfaces и gates.","Repeatable work with predictable interfaces and gates.","Ошибки предположений обнаруживаются поздно.","Wrong assumptions may surface late.",["iso21502"]),
  m("agile","Agile","Agile","Система ценностей для адаптивной разработки через частую поставку и обучение.","A value system for adaptive delivery through frequent value and learning.","Короткие циклы: выбрать ценность → сделать → проверить → адаптировать.","Short loops: choose value → deliver → inspect → adapt.","Высокая неопределённость и доступная частая обратная связь.","High uncertainty with frequent accessible feedback.","Без ясной цели и empowered team превращается в реактивность.","Without a clear goal and empowered team it becomes reactive.",["agilemanifesto","agile2"]),
  m("hybrid","Гибридный подход","Hybrid","Осмысленное сочетание governance и adaptive delivery.","Purposeful combination of governance and adaptive delivery.","Формальные контрольные точки окружают короткие циклы delivery.","Formal control points surround short delivery cycles.","Жёсткие внешние ограничения при изменчивом способе достижения результата.","Hard external constraints with an evolving solution path.","Без явных границ становится случайным framework soup.","Without explicit boundaries it becomes random framework soup.",["pmbok8","agile2"]),
  m("scrum","Scrum","Scrum","Лёгкий framework для сложных продуктов на основе empiricism.","A lightweight framework for complex products based on empiricism.","Product Backlog → Sprint Planning → Sprint → Review + Retrospective → adaptation.","Product Backlog → Sprint Planning → Sprint → Review + Retrospective → adaptation.","Кросс-функциональная команда может создавать usable increment каждый Sprint.","A cross-functional team can create a usable Increment every Sprint.","Не решает portfolio, contracts и governance автоматически.","Does not automatically solve portfolio, contracts, or governance.",["scrum2020"],"Scrum Guide 2020"),
  m("kanban","Kanban","Kanban","Оптимизация потока через явный workflow, контроль WIP и обратную связь.","Flow optimization through an explicit workflow, WIP control, and feedback.","Определить workflow → управлять WIP → наблюдать flow metrics → улучшать.","Define workflow → control WIP → observe flow metrics → improve.","Непрерывный поток разнородной работы и потребность сократить задержки.","Continuous heterogeneous work where reducing delay matters.","Доска без WIP и flow reviews даёт только визуализацию задач.","A board without WIP control and flow reviews only visualizes tasks.",["kanban2025"],"Kanban Guide May 2025"),
  m("scrumban","Scrumban","Scrumban","Scrum cadence с Kanban flow practices и эволюционным улучшением.","Scrum cadence combined with Kanban flow practices and evolutionary improvement.","Sprint goal и reviews сохраняются; WIP, pull и flow metrics управляют исполнением.","Sprint goal and reviews remain; WIP, pull, and flow metrics govern execution.","Команда Scrum испытывает перегрузку, carry-over или interrupt work.","A Scrum team faces overload, carry-over, or interrupt work.","Название не заменяет явного Definition of Workflow.","The label does not replace an explicit Definition of Workflow.",["scrum2020","kanban2025"]),
  m("lean","Lean","Lean","Управление ценностью, потоком, качеством и устранением потерь.","Manage value, flow, quality, and waste elimination.","Определить value → map flow → remove constraints → improve continuously.","Define value → map flow → remove constraints → improve continuously.","Повторяемые value streams и измеримые задержки.","Repeatable value streams with observable delays.","Локальная экономия может повредить системному результату.","Local optimization can harm the system outcome.",["kanban2025"]),
  m("xp","Экстремальное программирование","Extreme Programming","Инженерные практики для быстрой и устойчивой поставки software.","Engineering practices for rapid, sustainable software delivery.","Малые releases, tests, continuous integration, pair work, refactoring.","Small releases, tests, continuous integration, pair work, refactoring.","Software teams с частыми изменениями и сильной инженерной дисциплиной.","Software teams with frequent change and strong engineering discipline.","Практики требуют skill и не заменяют product direction.","Practices require skill and do not replace product direction.",["agilemanifesto"]),
  m("prince2","PRINCE2","PRINCE2","Структурированный метод управления через принципы, практики, процессы и tailoring.","Structured project management through principles, practices, processes, and tailoring.","Business justification и управление по стадиям с определёнными решениями.","Continued business justification and management by stages with defined decisions.","Организации с formal governance и ясной ответственностью.","Organizations needing formal governance and clear accountability.","Плохой tailoring создаёт документную нагрузку без лучшего контроля.","Poor tailoring creates document load without better control.",["prince2v7"],"PRINCE2 7"),
  m("cpm","Метод критического пути","Critical Path Method","Сетевая модель schedule, показывающая цепочку без total float.","A schedule network model identifying the chain with no total float.","Dependencies + durations → forward pass → backward pass → float.","Dependencies + durations → forward pass → backward pass → float.","Проекты с зависимыми activity и достаточно стабильными estimates.","Projects with dependent activities and reasonably stable estimates.","Результат зависит от качества зависимостей и оценок.","Output is only as good as dependencies and estimates.",["pmbok8"]),
  m("critical-chain","Критическая цепь","Critical Chain","Планирование с учётом resource constraints и aggregate buffers.","Planning that considers resource constraints and aggregate buffers.","Resource-level schedule → critical chain → project/feeding buffers → buffer control.","Resource-level schedule → critical chain → project/feeding buffers → buffer control.","Мультипроектная среда с конкуренцией за ограниченные ресурсы.","Multi-project environments competing for constrained resources.","Некорректные buffers маскируют плохие исходные данные.","Poorly designed buffers can mask weak inputs.",["pmbok8"]),
  m("stage-gate","Stage-Gate","Stage-Gate","Инвестиционные решения между стадиями развития инициативы.","Investment decisions between stages of initiative development.","Stage work → evidence package → gate decision: go/hold/recycle/stop.","Stage work → evidence package → gate decision: go/hold/recycle/stop.","Высокая стоимость следующей стадии и необходимость portfolio choices.","High next-stage cost and portfolio choices.","Gates становятся театром, если stop decision невозможен.","Gates become theater when stopping is impossible.",["pmbok8"]),
  m("lean-startup","Lean Startup","Lean Startup","Проверка бизнес-гипотез через build–measure–learn.","Testing business hypotheses through build–measure–learn.","Гипотеза → минимальный эксперимент → evidence → pivot/persevere.","Hypothesis → minimum experiment → evidence → pivot/persevere.","Новый продукт с высокой market uncertainty.","New products with high market uncertainty.","MVP может быть принят за низкокачественный конечный продукт.","An MVP can be mistaken for a low-quality final product.",["agile2"]),
  m("design-thinking","Дизайн-мышление","Design Thinking","Human-centered exploration and solution framing.","Human-centered exploration and solution framing.","Empathize → define → ideate → prototype → test; loops are expected.","Empathize → define → ideate → prototype → test; loops are expected.","Нечёткая проблема и необходимость понять поведение пользователя.","Ambiguous problem requiring user understanding.","Идеация без delivery и evidence не создаёт результат.","Ideation without delivery and evidence creates no outcome.",["agile2"]),
  m("scaling","Масштабирование: SAFe, LeSS, DA","Scaling: SAFe, LeSS, DA","Нейтральная карта подходов координации нескольких команд.","A neutral map of approaches for coordinating multiple teams.","Синхронизация strategy, architecture, delivery и feedback различается по framework.","Strategy, architecture, delivery, and feedback synchronization varies by framework.","Реальная межкомандная связанность, которую нельзя устранить проще.","Real cross-team coupling that cannot be removed more simply.","Scaling framework усиливает существующую сложность и не лечит слабые teams.","A scaling framework amplifies complexity and does not repair weak teams.",["agile2"]),
];

export type Template={slug:string;title:Bi;category:string;purpose:Bi;when:Bi;fields:Bi[];guidance:Bi;antiPattern:Bi};
const tf={
  strategy:[{ru:"Контекст и решение",en:"Context and decision"},{ru:"Ожидаемый результат",en:"Expected outcome"},{ru:"Критерий успеха",en:"Success measure"},{ru:"Владелец",en:"Owner"}],
  plan:[{ru:"Scope / границы",en:"Scope / boundaries"},{ru:"Milestones и даты",en:"Milestones and dates"},{ru:"Зависимости",en:"Dependencies"},{ru:"Риски и допущения",en:"Risks and assumptions"}],
  log:[{ru:"ID и дата",en:"ID and date"},{ru:"Описание",en:"Description"},{ru:"Владелец",en:"Owner"},{ru:"Статус и следующее действие",en:"Status and next action"}],
  meeting:[{ru:"Цель встречи",en:"Meeting purpose"},{ru:"Подготовка",en:"Preparation"},{ru:"Agenda и timeboxes",en:"Agenda and timeboxes"},{ru:"Решения и actions",en:"Decisions and actions"}],
  control:[{ru:"Baseline / ожидание",en:"Baseline / expectation"},{ru:"Факт",en:"Actual"},{ru:"Отклонение",en:"Variance"},{ru:"Решение и владелец",en:"Decision and owner"}],
};
const template=(slug:string,ru:string,en:string,category:keyof typeof tf,purposeRu:string,purposeEn:string,extra:Bi[]=[]):Template=>({slug,title:{ru,en},category,purpose:{ru:purposeRu,en:purposeEn},when:{ru:"Используйте, когда артефакт помогает принять решение, синхронизировать участников или подтвердить результат.",en:"Use when the artifact supports a decision, aligns participants, or verifies an outcome."},fields:[...tf[category],...extra],guidance:{ru:"Заполняйте до уровня, достаточного для следующего управленческого действия. Удалите секции, которые ничего не меняют.",en:"Complete only to the depth needed for the next management action. Remove sections that change nothing."},antiPattern:{ru:"Документ обновляется ради отчётности, но не используется в решениях.",en:"The document is maintained for reporting but never used in decisions."}});

export const templates:Template[]=[
  template("project-charter","Устав проекта","Project Charter","strategy","Согласовать полномочия, цель и границы проекта.","Align authority, purpose, and project boundaries.",[{ru:"Scope in / out",en:"Scope in / out"},{ru:"Бюджетный диапазон",en:"Budget envelope"}]),
  template("business-case-lite","Business Case Lite","Business Case Lite","strategy","Проверить, стоит ли инициатива инвестиций.","Check whether the initiative deserves investment."),
  template("business-case","Бизнес-кейс","Business Case","strategy","Сравнить варианты, выгоды, затраты и риски.","Compare options, benefits, costs, and risks.",[{ru:"Опции и NPV/ROI при уместности",en:"Options and NPV/ROI where applicable"}]),
  template("project-brief","Бриф проекта","Project Brief","strategy","Дать команде краткий общий контекст.","Give the team concise shared context."),
  template("project-plan","План проекта","Project Plan","plan","Объединить способ исполнения и контроля.","Unify the delivery and control approach."),
  template("scope-statement","Описание scope","Scope Statement","plan","Сделать границы и исключения явными.","Make boundaries and exclusions explicit."),
  template("wbs","WBS","Work Breakdown Structure","plan","Декомпозировать 100% согласованного scope на deliverables и work packages.","Decompose 100% of agreed scope into deliverables and work packages."),
  template("requirements-register","Реестр требований","Requirements Register","log","Связать требования с источником, приоритетом и проверкой.","Connect requirements to source, priority, and validation."),
  template("backlog-item","Backlog item","Backlog Item","log","Сформулировать единицу работы достаточно ясно для решения.","Define a work item clearly enough for a decision."),
  template("user-story","User story","User Story","strategy","Зафиксировать пользователя, потребность и ценность без подмены требования форматом.","Capture user, need, and value without letting the format replace the requirement."),
  template("acceptance-criteria","Критерии приёмки","Acceptance Criteria","control","Сделать проверку результата однозначной.","Make outcome verification unambiguous."),
  template("definition-ready","Definition of Ready","Definition of Ready","control","Установить минимальные условия для начала работы.","Set minimum conditions for starting work."),
  template("definition-done","Definition of Done","Definition of Done","control","Установить общий уровень качества завершённой работы.","Set a shared quality bar for completed work."),
  template("milestone-plan","План milestones","Milestone Plan","plan","Показать значимые точки результата и решений.","Show meaningful outcome and decision points."),
  template("roadmap","Roadmap","Project Roadmap","plan","Связать themes, outcomes и releases во времени.","Connect themes, outcomes, and releases over time."),
  template("release-plan","План релиза","Release Plan","plan","Согласовать scope релиза, readiness и go/no-go.","Align release scope, readiness, and go/no-go."),
  template("sprint-goal","Цель Sprint","Sprint Goal","strategy","Дать Sprint единую цель вместо набора несвязанных items.","Give a Sprint one goal rather than unrelated items."),
  template("risk-register","Реестр рисков","Risk Register","log","Управлять неопределённостями до того, как они станут issues.","Manage uncertainties before they become issues."),
  template("raid-log","RAID log","RAID Log","log","Вести risks, assumptions, issues и dependencies в одной контрольной точке.","Maintain risks, assumptions, issues, and dependencies in one control point."),
  template("issue-log","Журнал проблем","Issue Log","log","Назначить действия по уже возникшим проблемам.","Assign action for problems already occurring."),
  template("assumption-log","Журнал допущений","Assumption Log","log","Проверять утверждения, на которых держится план.","Test the assumptions the plan relies on."),
  template("dependency-log","Журнал зависимостей","Dependency Log","log","Управлять внешними и внутренними блокирующими связями.","Manage external and internal blocking relationships."),
  template("decision-log","Журнал решений","Decision Log","log","Сохранить контекст и последствия ключевых решений.","Preserve context and consequences of key decisions."),
  template("stakeholder-register","Реестр stakeholders","Stakeholder Register","log","Понять ожидания и нужную вовлечённость участников.","Understand stakeholder expectations and needed engagement."),
  template("stakeholder-matrix","Матрица stakeholders","Stakeholder Matrix","strategy","Спланировать пропорциональную коммуникацию по influence и interest.","Plan proportionate communication by influence and interest."),
  template("raci","RACI","RACI","control","Снять неоднозначность ответственности за deliverables и решения.","Remove ambiguity in accountability for deliverables and decisions."),
  template("communication-plan","План коммуникаций","Communication Plan","plan","Определить кому, зачем, что, когда и кем сообщается.","Define who needs what information, why, when, and from whom."),
  template("meeting-agenda","Agenda встречи","Meeting Agenda","meeting","Подготовить решение или синхронизацию с ясным output.","Prepare a decision or alignment session with a clear output."),
  template("meeting-minutes","Протокол встречи","Meeting Minutes","meeting","Зафиксировать решения, actions и владельцев.","Record decisions, actions, and owners."),
  template("kickoff","Kickoff","Kickoff","meeting","Синхронизировать цель, роли, способ работы и ближайший шаг.","Align purpose, roles, way of working, and next step."),
  template("status-report","Статус-отчёт","Status Report","control","Сфокусировать stakeholders на изменениях и решениях.","Focus stakeholders on changes and decisions."),
  template("steering-pack","Пакет steering committee","Steering Committee Pack","control","Подготовить governance decisions без операционного шума.","Prepare governance decisions without operational noise."),
  template("change-request","Запрос на изменение","Change Request","control","Оценить последствия изменения до approval.","Assess change impact before approval."),
  template("change-log","Журнал изменений","Change Log","log","Сохранить историю scope/baseline changes.","Preserve scope and baseline change history."),
  template("quality-plan","План качества","Quality Plan","plan","Определить quality goals, checks и acceptance.","Define quality goals, checks, and acceptance."),
  template("acceptance-checklist","Чек-лист приёмки","Test / Acceptance Checklist","control","Не пропустить проверяемые условия готовности.","Avoid missing verifiable readiness conditions."),
  template("capacity-plan","План capacity","Capacity Plan","plan","Сопоставить доступную capacity с плановой работой.","Match available capacity to planned work."),
  template("resource-plan","Ресурсный план","Resource Plan","plan","Выявить перегрузку, пробелы и конфликты allocation.","Expose overload, gaps, and allocation conflicts."),
  template("budget-tracker","Трекер бюджета","Budget Tracker","control","Сравнивать baseline, actual, committed и forecast.","Compare baseline, actual, committed, and forecast."),
  template("vendor-evaluation","Оценка поставщика","Vendor Evaluation","control","Сравнить поставщиков по явным критериям и рискам.","Compare vendors against explicit criteria and risks."),
  template("procurement-tracker","Трекер закупок","Procurement Tracker","log","Управлять deliverables, сроками и зависимостями vendors.","Manage vendor deliverables, dates, and dependencies."),
  template("retrospective","Ретроспектива","Retrospective","meeting","Выбрать одно-два проверяемых улучшения способа работы.","Choose one or two testable improvements to the way of working."),
  template("lessons-learned","Извлечённые уроки","Lessons Learned","strategy","Превратить опыт в рекомендацию для следующего контекста.","Turn experience into a recommendation for the next context."),
  template("postmortem","Postmortem","Postmortem","meeting","Без обвинений разобрать impact, causes и prevention.","Review impact, causes, and prevention without blame."),
  template("handover","Чек-лист передачи","Handover Checklist","control","Передать ownership, знания, доступы и unresolved items.","Transfer ownership, knowledge, access, and unresolved items."),
  template("closure-report","Отчёт о закрытии","Closure Report","control","Зафиксировать acceptance, performance и дальнейшее измерение benefits.","Record acceptance, performance, and future benefits measurement."),
  template("closure-checklist","Чек-лист закрытия","Project Closure Checklist","control","Закрыть contracts, finance, archives, handover и lessons.","Close contracts, finance, archives, handover, and lessons."),
];

export type Playbook={slug:string;title:Bi;diagnose:Bi[];immediate:Bi[];next:Bi[];stabilize:Bi[];prevent:Bi[];metrics:Bi[];antiPatterns:Bi[]};
const pb=(slug:string,ru:string,en:string,signalRu:string,signalEn:string,actionRu:string,actionEn:string,metricRu:string,metricEn:string):Playbook=>({slug,title:{ru,en},diagnose:[{ru:signalRu,en:signalEn},{ru:"Отделите наблюдаемый факт от интерпретации и найдите ограничение системы.",en:"Separate observed fact from interpretation and identify the system constraint."}],immediate:[{ru:actionRu,en:actionEn},{ru:"Назначьте одного владельца следующего решения и срок проверки.",en:"Assign one owner for the next decision and a review date."}],next:[{ru:"В следующий рабочий цикл соберите минимальные данные, перепланируйте затронутую работу и сообщите последствия.",en:"In the next working cycle, collect minimum evidence, replan affected work, and communicate impact."}],stabilize:[{ru:"Сократите активную работу, сделайте приоритеты и зависимости явными, восстановите cadence контроля.",en:"Reduce active work, expose priorities and dependencies, and restore a control cadence."}],prevent:[{ru:"Добавьте ранний trigger, владельца и регулярный review — не новый отчёт ради отчёта.",en:"Add an early trigger, owner, and regular review—not another report for its own sake."}],metrics:[{ru:metricRu,en:metricEn},{ru:"Возраст блокировок и время до решения.",en:"Blocker age and time to decision."}],antiPatterns:[{ru:"Обещать новую дату до анализа причин и trade-offs.",en:"Promise a new date before analyzing causes and trade-offs."},{ru:"Увеличивать параллельную работу, чтобы создать видимость скорости.",en:"Increase parallel work to create an appearance of speed."}]});

export const playbooks:Playbook[]=[
  pb("project-late","Проект опаздывает","Project is late","Milestones системно сдвигаются; критическая цепочка не ясна.","Milestones move repeatedly; the critical chain is unclear.","Заморозьте новые обязательства, пересчитайте critical path и отделите recoverable delay от sunk delay.","Freeze new commitments, recalculate the critical path, and separate recoverable from sunk delay.","Прогноз milestone и total float.","Milestone forecast and total float."),
  pb("fixed-deadline","Дедлайн нельзя сдвинуть","Deadline cannot move","Дата внешне фиксирована, но scope и quality assumptions не пересмотрены.","The date is externally fixed but scope and quality assumptions remain unchanged.","Зафиксируйте дату как constraint; предложите варианты scope, sequence, resources и risk acceptance.","Treat the date as a constraint; offer options across scope, sequence, resources, and risk acceptance.","Burn-up scope и readiness criteria.","Scope burn-up and readiness criteria."),
  pb("scope-growth","Scope постоянно растёт","Scope keeps growing","Новые запросы входят без оценки влияния и removal decision.","Requests enter without impact assessment or removal decisions.","Создайте change boundary: каждое добавление получает impact и компенсирующий trade-off.","Create a change boundary: every addition gets impact analysis and a compensating trade-off.","Scope added/removed и schedule variance.","Scope added/removed and schedule variance."),
  pb("unclear-requirements","Требования неясны","Requirements are unclear","Команда спорит о решении, не понимая пользователя, outcome или acceptance.","The team debates solutions without a shared user, outcome, or acceptance view.","Выберите самый рискованный вопрос и проведите короткий discovery/validation loop.","Choose the riskiest question and run a short discovery/validation loop.","Assumption validation rate.","Assumption validation rate."),
  pb("changing-priorities","Stakeholder меняет приоритеты","Stakeholder changes priorities","Приоритет меняется чаще, чем команда может завершать работу.","Priority changes faster than the team can finish work.","Согласуйте decision cadence и цену переключения; новые срочные items вытесняют явные текущие.","Agree a decision cadence and switching cost; new urgent items explicitly displace current work.","Interrupt rate и abandoned work.","Interrupt rate and abandoned work."),
  pb("sponsor-unavailable","Sponsor недоступен","Sponsor unavailable","Decisions выходят за tolerance и остаются без accountable owner.","Decisions exceed tolerance and lack an accountable owner.","Соберите decision pack: вопрос, options, recommendation, deadline, consequence of no decision.","Prepare a decision pack: question, options, recommendation, deadline, consequence of no decision.","Decision latency.","Decision latency."),
  pb("team-overloaded","Команда перегружена","Team overloaded","Allocation превышает capacity, WIP растёт, cycle time ухудшается.","Allocation exceeds capacity, WIP grows, and cycle time deteriorates.","Остановите старт новой работы и завершите/снимите часть WIP.","Stop starting work and finish or remove part of WIP.","WIP, work item age, overtime trend.","WIP, work item age, overtime trend."),
  pb("key-person","Ключевой человек недоступен","Key person unavailable","Знания или approval сосредоточены в одной точке.","Knowledge or approval is concentrated in one person.","Разделите blocking и non-blocking work; назначьте временного decision owner.","Separate blocking from non-blocking work; assign a temporary decision owner.","Bus factor и blocked age.","Bus factor and blocked age."),
  pb("missed-commitments","Команда не выполняет обязательства","Team misses commitments","Carry-over повторяется, но планирование не меняется.","Carry-over repeats while planning remains unchanged.","Сравните demand, capacity, interrupts и item size; уменьшите batch и commitment.","Compare demand, capacity, interrupts, and item size; reduce batch and commitment.","Commitment reliability и item size.","Commitment reliability and item size."),
  pb("too-much-wip","Слишком много WIP","Too much WIP","Много начато, мало завершено; aging растёт.","Much is started, little is finished; aging rises.","Временно снизьте WIP limits, swarm на старейших items, запретите hidden queues.","Temporarily lower WIP limits, swarm on oldest items, and expose hidden queues.","WIP, throughput, cycle time, age.","WIP, throughput, cycle time, age."),
  pb("all-high-priority","Всё имеет высокий приоритет","Everything is high priority","Priority label не меняет sequence решений.","Priority labels do not change decision sequence.","Попросите rank order и выберите cost-of-delay критерий.","Require rank order and choose a cost-of-delay criterion.","Количество concurrent priorities.","Number of concurrent priorities."),
  pb("backlog-chaos","Backlog превратился в хаос","Backlog is chaos","Items дублируются, устарели и не имеют outcome/owner.","Items are duplicated, stale, and lack outcome or owner.","Архивируйте stale items, объедините duplicates, выделите ready horizon на 1–2 цикла.","Archive stale items, merge duplicates, and define a ready horizon of 1–2 cycles.","Backlog age и ready ratio.","Backlog age and ready ratio."),
  pb("estimation-wrong","Оценки системно ошибочны","Estimation is consistently wrong","Ошибка направлена в одну сторону и не учитывается в forecast.","Error is directional and ignored in forecasts.","Сегментируйте work types, сравните forecast с actual, используйте диапазоны.","Segment work types, compare forecast to actual, and use ranges.","Forecast error distribution.","Forecast error distribution."),
  pb("no-goal","У проекта нет ясной цели","Project has no clear goal","Есть output list, но неизвестно, какое изменение считается успехом.","There is an output list but no defined successful change.","Остановите детальное планирование и согласуйте problem, outcome, measure, owner.","Pause detailed planning and align problem, outcome, measure, and owner.","Outcome measure и decision alignment.","Outcome measure and decision alignment."),
  pb("no-owner","У проекта нет владельца","Project has no owner","Никто не может принять trade-off или подтвердить результат.","No one can make trade-offs or accept the outcome.","Эскалируйте governance gap; назначьте accountable sponsor до новых commitments.","Escalate the governance gap; assign an accountable sponsor before new commitments.","Unowned decisions.","Unowned decisions."),
  pb("client-unhappy","Клиент недоволен","Client dissatisfaction","Эмоциональная оценка не разложена на gaps ожидания, качества, срока или коммуникации.","Emotional feedback is not decomposed into expectation, quality, timing, or communication gaps.","Признайте impact, уточните observable gaps, согласуйте recovery actions и check-in.","Acknowledge impact, clarify observable gaps, agree recovery actions and a check-in.","Open gaps и confidence check.","Open gaps and confidence check."),
  pb("stakeholder-conflict","Конфликт stakeholders","Stakeholder conflict","У сторон разные интересы, criteria или decision rights.","Parties have different interests, criteria, or decision rights.","Отделите позиции от интересов; согласуйте критерии и decision owner.","Separate positions from interests; agree criteria and decision owner.","Decision latency и reopened decisions.","Decision latency and reopened decisions."),
  pb("no-authority","У PM нет полномочий","PM has no authority","Ожидания ответственности выше предоставленных decision rights.","Accountability expectations exceed granted decision rights.","Сделайте gap явным: какие решения нужны, кто принимает, какой escalation path.","Expose the gap: decisions needed, decision owners, and escalation path.","Escalations и waiting time.","Escalations and waiting time."),
  pb("cross-team-block","Межкомандная зависимость блокирует","Cross-team dependency blocks delivery","Dependency не имеет bilateral owner, date или acceptance.","The dependency lacks bilateral owner, date, or acceptance.","Создайте handshake: predecessor output, successor need, owner с обеих сторон, date, fallback.","Create a handshake: predecessor output, successor need, owners on both sides, date, fallback.","Dependency age и breach rate.","Dependency age and breach rate."),
  pb("vendor-late","Поставщик опаздывает","External vendor is late","Contract milestone нарушен, но impact и alternatives не просчитаны.","A contract milestone slipped without quantified impact or alternatives.","Подтвердите факты, critical-path impact, recovery plan и contractual escalation.","Confirm facts, critical-path impact, recovery plan, and contractual escalation.","Vendor milestone variance.","Vendor milestone variance."),
  pb("high-risk-release","Релиз высокого риска","High-risk release","Blast radius высок, rollback/readiness не доказаны.","Blast radius is high and rollback/readiness are unproven.","Определите go/no-go criteria, rollback owner, monitoring и staged exposure.","Define go/no-go criteria, rollback owner, monitoring, and staged exposure.","Readiness gaps и recovery time.","Readiness gaps and recovery time."),
  pb("budget-overrun","Бюджет превышен","Budget overrun","Actual/committed выше baseline без нового forecast.","Actual/committed costs exceed baseline without a new forecast.","Разделите variance на rate, volume, scope и timing; пересчитайте EAC и варианты.","Split variance into rate, volume, scope, and timing; recalculate EAC and options.","CPI, EAC, VAC.","CPI, EAC, VAC."),
  pb("unknown-budget","Бюджет неизвестен","Unknown budget","Нет cost owner, baseline или доступного диапазона решений.","There is no cost owner, baseline, or decision range.","Соберите cost categories, commitments и диапазон; назначьте owner финансовых данных.","Collect cost categories, commitments, and range; assign financial data ownership.","Forecast coverage.","Forecast coverage."),
  pb("health-unclear","Состояние проекта неясно","Project health is unclear","Один субъективный score скрывает разные dimensions.","One subjective score hides different dimensions.","Оцените schedule, scope, budget, risk, blockers, capacity и alignment отдельно с правилами.","Assess schedule, scope, budget, risk, blockers, capacity, and alignment separately with rules.","Unknown health dimensions.","Unknown health dimensions."),
  pb("too-many-meetings","Слишком много встреч","Too many meetings","Meetings consume capacity without unique decisions or outputs.","Meetings consume capacity without unique decisions or outputs.","Отмените встречи без owner/output; объедините status в async artifact.","Cancel meetings without an owner/output; consolidate status in an async artifact.","Meeting hours и decision yield.","Meeting hours and decision yield."),
  pb("useless-meetings","Встречи бесполезны","No useful meetings","Agenda описывает темы, а не решения; actions не отслеживаются.","The agenda lists topics, not decisions; actions are not tracked.","Перепишите agenda как вопросы/решения, добавьте pre-read и owner протокола.","Rewrite the agenda as questions/decisions; add a pre-read and minutes owner.","Actions closed и decisions per meeting.","Actions closed and decisions per meeting."),
  pb("retro-no-change","Ретро ничего не меняет","Retrospective changes nothing","Actions слишком общие, без owner и follow-up.","Actions are vague, unowned, and never reviewed.","Выберите один observable experiment, owner, срок и expected signal.","Choose one observable experiment, owner, date, and expected signal.","Improvement action completion.","Improvement action completion."),
  pb("fear","Команда скрывает проблемы","Team is afraid to surface problems","Плохие новости появляются поздно; обсуждение ищет виновного.","Bad news arrives late; discussions seek blame.","Лидер первым признаёт uncertainty; разберите систему и защитите раннюю эскалацию.","Leader names uncertainty first; examine the system and protect early escalation.","Time-to-surface и anonymous safety pulse.","Time to surface and anonymous safety pulse."),
  pb("bad-status","Статус-отчёты бесполезны","Status reports are useless","Отчёт перечисляет activity, но не change, forecast или decision.","The report lists activity but not change, forecast, or decisions.","Оставьте: что изменилось, прогноз, top risks, decisions/help needed.","Keep only: what changed, forecast, top risks, decisions/help needed.","Decision yield и report freshness.","Decision yield and report freshness."),
  pb("heavy-governance","Governance слишком тяжёлый","Governance too heavy","Approval latency выше risk reduction; данные дублируются.","Approval latency exceeds risk reduction; data is duplicated.","Картируйте каждый gate к риску/решению; удалите артефакты без consumer.","Map every gate to a risk/decision; remove artifacts without a consumer.","Approval lead time.","Approval lead time."),
  pb("no-governance","Governance отсутствует","Governance nonexistent","Нет tolerances, decision rights или escalation.","There are no tolerances, decision rights, or escalation paths.","Определите sponsor, three key decisions, thresholds и cadence review.","Define sponsor, three key decisions, thresholds, and review cadence.","Unresolved exceptions.","Unresolved exceptions."),
  pb("agile-no-plan","Agile используют как отказ от планирования","Agile is used as excuse for no planning","Нет product goal, forecast, dependencies или readiness.","There is no product goal, forecast, dependencies, or readiness view.","Создайте adaptive plan: goal, ordered backlog, near-term commitment, forecast range.","Create an adaptive plan: goal, ordered backlog, near-term commitment, forecast range.","Goal progress и forecast range.","Goal progress and forecast range."),
  pb("waterfall-change","Waterfall при изменчивых требованиях","Waterfall where requirements change","Change rate выше capacity formal control; feedback приходит поздно.","Change rate exceeds formal control capacity; feedback arrives late.","Сохраните необходимые gates, но перенесите solution discovery в короткие validation loops.","Keep necessary gates but move solution discovery into short validation loops.","Change lead time и rework.","Change lead time and rework."),
  pb("framework-soup","Hybrid стал framework soup","Hybrid became framework soup","Практики конфликтуют, roles дублируются, cadence перегружена.","Practices conflict, roles duplicate, and cadence is overloaded.","Разделите governance/planning/delivery; для каждой практики назовите проблему, owner и stop rule.","Separate governance/planning/delivery; name the problem, owner, and stop rule for each practice.","Process load и conflicting policies.","Process load and conflicting policies."),
  pb("rescue","Спасти проект","Project needs rescue","Objective, scope, ownership, schedule и confidence расходятся.","Objective, scope, ownership, schedule, and confidence diverge.","Stop: новые commitments. Stabilize: факты и безопасность. Replan: options. Align: decision. Deliver: короткий proof cycle.","Stop new commitments. Stabilize facts and safety. Replan options. Align a decision. Deliver a short proof cycle.","Critical blockers, decision age, forecast confidence.","Critical blockers, decision age, forecast confidence."),
  pb("handover","Передать проект","Project handover","Tacit knowledge, access и unresolved work не имеют нового owner.","Tacit knowledge, access, and unresolved work lack a new owner.","Составьте handover map: decisions, risks, contacts, artifacts, access, next 30 days.","Build a handover map: decisions, risks, contacts, artifacts, access, next 30 days.","Accepted handover items.","Accepted handover items."),
  pb("join-midway","PM подключается в середине","PM joins project midway","Документы расходятся с реальностью, история решений скрыта.","Documents differ from reality and decision history is hidden.","Проведите evidence tour: sponsor, team, customer, plan, flow, risks, decisions.","Run an evidence tour: sponsor, team, customer, plan, flow, risks, decisions.","Unknowns retired per week.","Unknowns retired per week."),
  pb("close-failing","Закрыть неуспешный проект","Closing a failing project","Continuation cost превышает expected value, но sunk cost влияет на решение.","Continuation cost exceeds expected value but sunk cost biases the decision.","Подготовьте stop case, protect people/data, define handover and lessons, name residual obligations.","Prepare a stop case, protect people/data, define handover and lessons, and name residual obligations.","Residual obligations closed.","Residual obligations closed."),
  pb("start-zero","Начать проект с нуля","Starting project from zero","Есть идея, но нет problem owner, outcome или constraints.","There is an idea but no problem owner, outcome, or constraints.","Согласуйте problem, sponsor, outcome measure, boundaries и первый uncertainty test.","Align problem, sponsor, outcome measure, boundaries, and the first uncertainty test.","Time to first validated learning.","Time to first validated learning."),
];

export const knowledgeDomains:Bi[]=[
  {ru:"Основы",en:"Fundamentals"},{ru:"Governance",en:"Governance"},{ru:"Ценность",en:"Value"},{ru:"Scope",en:"Scope"},{ru:"Требования",en:"Requirements"},{ru:"Сроки",en:"Schedule"},{ru:"Стоимость",en:"Cost"},{ru:"Риски",en:"Risk"},{ru:"Качество",en:"Quality"},{ru:"Ресурсы",en:"Resources"},{ru:"Команда",en:"Team"},{ru:"Лидерство",en:"Leadership"},{ru:"Stakeholders",en:"Stakeholders"},{ru:"Коммуникации",en:"Communication"},{ru:"Закупки",en:"Procurement"},{ru:"Изменения",en:"Change"},{ru:"Delivery",en:"Delivery"},{ru:"Agile",en:"Agile"},{ru:"Поток",en:"Flow"},{ru:"Измерение",en:"Measurement"},{ru:"Прогнозирование",en:"Forecasting"},{ru:"Восстановление проекта",en:"Project Recovery"},{ru:"Закрытие",en:"Closure"},{ru:"PMO",en:"PMO"},{ru:"Основы программ",en:"Program basics"},{ru:"Основы портфелей",en:"Portfolio basics"}
];

export type Glossary={term:string;ru:string;definition:Bi;example:Bi;related:string[]};
const glossarySeed:[string,string,string,string,string,string][]=[
  ["Acceptance Criteria","Критерии приёмки","Проверяемые условия, которым должен соответствовать результат.","Testable conditions an outcome must meet.","Форма отправляет валидные данные и показывает ошибку при неверных.","The form submits valid data and shows an error for invalid input."],
  ["Accountable","Ответственный за результат","Единственный владелец конечного решения или результата в RACI.","The single owner of the final decision or outcome in RACI.","Sponsor утверждает baseline.","The sponsor approves the baseline."],
  ["Assumption","Допущение","Считаемое истинным утверждение, которое ещё требует проверки.","A statement treated as true but still requiring validation.","Поставщик предоставит API к маю.","The vendor will provide the API by May."],
  ["BAC","Бюджет по завершении","Утверждённый бюджет всего scope в EVM.","The approved budget for all scope in EVM.","BAC проекта — 500 000.","Project BAC is 500,000."],
  ["Backlog","Бэклог","Упорядоченный набор потенциальной работы.","An ordered set of potential work.","Команда берёт следующий ready item из backlog.","The team takes the next ready item from the backlog."],
  ["Baseline","Базовый план","Утверждённая версия scope, schedule или cost для сравнения.","Approved scope, schedule, or cost version used for comparison.","Новый forecast сравнивают с schedule baseline.","The new forecast is compared to the schedule baseline."],
  ["Benefit","Выгода","Измеримое положительное изменение, получаемое после использования outcome.","A measurable positive change realized from an outcome.","Сокращение времени обработки заявки на 30%.","Reducing request handling time by 30%."],
  ["Blocker","Блокер","Условие, не позволяющее работе продолжаться.","A condition preventing work from progressing.","Нет решения безопасности для релиза.","A security decision is missing for release."],
  ["Business Case","Бизнес-кейс","Обоснование инвестиций через варианты, выгоды, затраты и риски.","Investment rationale comparing options, benefits, costs, and risks.","Steering committee выбирает build против buy.","The steering committee chooses build versus buy."],
  ["Capacity","Доступная capacity","Реально доступный объём усилий за период после ограничений.","Real effort available in a period after constraints.","Из 200 часов 160 доступны проекту.","Of 200 hours, 160 are available to the project."],
  ["Change Control","Управление изменениями","Способ оценить, решить и зафиксировать изменение baseline.","A way to assess, decide, and record a baseline change.","Change request добавляет неделю после impact analysis.","A change request adds one week after impact analysis."],
  ["Constraint","Ограничение","Условие, сужающее доступные варианты решения.","A condition limiting available solution options.","Запуск должен пройти до изменения закона.","Launch must occur before a legal change."],
  ["Cost of Delay","Стоимость задержки","Потеря ценности из-за переноса delivery на единицу времени.","Value lost by delaying delivery per unit of time.","Неделя задержки сезонной кампании теряет продажи.","A week of seasonal campaign delay loses sales."],
  ["Critical Path","Критический путь","Самая длинная зависимая цепочка, определяющая раннюю дату завершения.","The longest dependent chain determining earliest completion.","Задержка activity с нулевым float сдвигает finish.","Delaying a zero-float activity moves the finish."],
  ["CPI","Индекс выполнения стоимости","EV / AC; эффективность затрат в EVM.","EV / AC; cost efficiency in EVM.","CPI 0.9 означает, что earned value ниже фактических затрат.","CPI 0.9 means earned value is below actual cost."],
  ["Cycle Time","Время цикла","Время от начала до завершения work item в заданном workflow.","Elapsed time from work start to completion in a defined workflow.","Item был In Progress 6 дней до Done.","The item spent six days from In Progress to Done."],
  ["Definition of Done","Определение готовности","Общее формальное описание качества завершённого Increment/work.","Shared formal description of the quality of completed work.","Код reviewed, tested и deployed в staging.","Code is reviewed, tested, and deployed to staging."],
  ["Deliverable","Поставляемый результат","Уникальный проверяемый продукт, результат или capability проекта.","A unique, verifiable product, result, or capability produced by a project.","Утверждённый дизайн системы.","An approved system design."],
  ["Dependency","Зависимость","Логическая связь, где одна работа влияет на возможность или срок другой.","A logical relationship where one item affects another's feasibility or timing.","Integration starts after API contract approval.","Integration starts after API contract approval."],
  ["EAC","Прогноз стоимости по завершении","Оценка итоговой стоимости проекта с учётом текущего performance.","Forecast total project cost considering current performance.","BAC / CPI при ожидании сохранения cost performance.","BAC / CPI when cost performance is expected to continue."],
  ["Epic","Эпик","Крупная единица ценности, требующая декомпозиции.","A large unit of value requiring decomposition.","Self-service onboarding разбит на features.","Self-service onboarding is split into features."],
  ["Escalation","Эскалация","Передача решения на уровень с необходимыми полномочиями.","Moving a decision to a level with adequate authority.","PM escalates budget exception to sponsor.","The PM escalates a budget exception to the sponsor."],
  ["Estimate","Оценка","Модель вероятного effort, duration или cost на основе доступных данных.","A model of likely effort, duration, or cost based on available evidence.","Задача займёт 3–5 дней, а не ровно 4.","The task will take 3–5 days, not exactly four."],
  ["EV","Освоенный объём","Бюджетная стоимость фактически выполненной работы.","Budgeted value of work actually completed.","50% work package с бюджетом 100 даёт EV 50.","A 50% complete work package budgeted at 100 gives EV 50."],
  ["Float","Временной резерв","Допустимая задержка activity без заданного последствия для schedule.","Allowable activity delay without a defined schedule consequence.","Total float 2 дня до сдвига project finish.","Two days of total float before project finish moves."],
  ["Governance","Управленческий контроль","Система decision rights, oversight и accountability проекта.","The system of decision rights, oversight, and project accountability.","Sponsor approves exceptions above tolerance.","The sponsor approves exceptions above tolerance."],
  ["Issue","Проблема","Событие или условие, которое уже происходит и требует решения.","An event or condition already occurring and requiring resolution.","Поставщик пропустил договорную дату.","The vendor missed a contractual date."],
  ["Lag","Задержка связи","Ожидание между зависимыми activity.","Waiting time inserted between dependent activities.","Тест начинается через 2 дня после установки.","Testing starts two days after installation."],
  ["Lead","Опережение связи","Разрешённое перекрытие зависимых activity.","Allowed overlap between dependent activities.","Документация начинается за день до завершения build.","Documentation starts one day before build completes."],
  ["Milestone","Контрольная точка","Событие нулевой длительности, отмечающее значимое достижение или решение.","A zero-duration event marking a meaningful achievement or decision.","Regulatory approval received.","Regulatory approval received."],
  ["Outcome","Изменение результата","Изменение поведения или состояния, созданное использованием output.","A change in behavior or state enabled by using an output.","Клиент оформляет заказ без поддержки.","A customer completes an order without support."],
  ["Output","Созданный продукт","Непосредственно произведённый артефакт, продукт или услуга.","The direct artifact, product, or service produced.","Новая форма заказа.","A new order form."],
  ["PV","Плановый объём","Бюджетная стоимость работы, запланированной к моменту измерения.","Budgeted value of work planned by the measurement date.","К пятнице планировали EV-equivalent 80.","By Friday, work budgeted at 80 was planned."],
  ["RAID","RAID","Связанный обзор risks, assumptions, issues и dependencies.","A connected view of risks, assumptions, issues, and dependencies.","Weekly RAID review focuses on changed items.","Weekly RAID review focuses on changed items."],
  ["RACI","RACI","Матрица Responsible, Accountable, Consulted, Informed.","A matrix of Responsible, Accountable, Consulted, and Informed roles.","Один Accountable за release decision.","One Accountable person for the release decision."],
  ["Risk","Риск","Неопределённое событие или условие с влиянием на цели.","An uncertain event or condition that may affect objectives.","API может не пройти нагрузку.","The API may fail load targets."],
  ["Scope","Объём работ","Граница продуктов, результатов и работы, включённых в проект.","Boundary of products, outcomes, and work included in a project.","Mobile app входит, admin redesign не входит.","The mobile app is in; admin redesign is out."],
  ["SLE","Ожидаемый уровень сервиса","Прогноз времени, за которое заданный процент items завершится.","A forecast of time within which a stated percentage of items completes.","85% standard items завершаются за 8 дней.","85% of standard items finish within eight days."],
  ["SPI","Индекс выполнения сроков","EV / PV; schedule performance indicator in EVM.","EV / PV; schedule performance indicator in EVM.","SPI ниже 1 означает меньше earned work, чем планировалось.","SPI below 1 means less earned work than planned."],
  ["Stakeholder","Заинтересованная сторона","Человек или группа, влияющие на проект или затронутые им.","A person or group influencing or affected by the project.","Support team affected by the new workflow.","The support team is affected by the new workflow."],
  ["Throughput","Пропускная способность","Количество work items, завершённых за единицу времени.","Number of work items completed per unit of time.","12 items завершено за неделю.","Twelve items completed in a week."],
  ["VAC","Отклонение по завершении","BAC − EAC; ожидаемое бюджетное отклонение на finish.","BAC − EAC; expected budget variance at completion.","VAC −20 000 указывает прогноз перерасхода.","VAC of −20,000 forecasts an overrun."],
  ["Velocity","Скорость команды","Количество points завершённого Increment за Sprint в контексте одной команды.","Points completed per Sprint in the context of one team.","Используется для team forecast, не сравнения людей.","Used for team forecasting, not comparing individuals."],
  ["WIP","Незавершённая работа","Work items, начатые, но ещё не завершённые.","Work items started but not yet completed.","В In Progress и Review сейчас 7 items.","Seven items are currently in In Progress and Review."],
  ["WSJF","Weighted Shortest Job First","Приоритизация Cost of Delay относительно Job Size.","Prioritization of Cost of Delay relative to Job Size.","Высокая ценность и малый size повышают score.","High value and small size increase the score."],
];
const extendedTerms=["Activity","Actual Cost","Acceptance","Action Owner","Adaptive","Affinity Mapping","Agile","Artifact","Benefit Owner","Benefits Management","Budget","Buffer","Burn-down","Burn-up","Cadence","Change Request","Charter","Checklist","Communication Plan","Compliance","Consulted","Contingency Reserve","Contract","Corrective Action","Critical Chain","Dashboard","Decision Log","Definition of Ready","Dependency Density","Discovery","Duration","Early Finish","Early Start","Escalation Path","ETC","Experiment","Feature","Feasibility","Finish-to-Finish","Finish-to-Start","Forecast","Gate","Goal","Hybrid","Impact","Impact Mapping","Increment","Influence","Initiative","Informed","Iteration","Kanban","KPI","Late Finish","Late Start","Lesson Learned","Little's Law","Management Reserve","Mitigation","Monte Carlo Simulation","MoSCoW","Objective","Opportunity","Owner","PERT","PMO","Portfolio","Predictive","Priority","Probability","Procurement","Product Backlog","Program","Project","Project Brief","Project Lifecycle","Quality","Quality Gate","RACI Matrix","Release","Requirements Volatility","Residual Risk","Resource","Responsible","Retrospective","RICE","Risk Appetite","Risk Exposure","Risk Owner","Risk Register","Roadmap","Rolling-wave Planning","SAFe","Schedule","Scrum","Scrum Master","Scope Creep","Sponsor","Sprint","Sprint Backlog","Sprint Goal","Sprint Review","Stage-Gate","Start-to-Start","Status Report","Steering Committee","Story","Story Point","Success Criteria","Swimlane","Tailoring","Task","Team Autonomy","Theme","Tolerance","Trigger","Uncertainty","User Story","Validation","Value","Variance","Vendor","Waterfall","Work Breakdown Structure","Work Item","Work Item Age","Work Package"];
export const glossary:Glossary[]=[...glossarySeed.map(([term,ru,dr,de,er,ee])=>({term,ru,definition:{ru:dr,en:de},example:{ru:er,en:ee},related:[]})),...extendedTerms.map(term=>({term,ru:term,definition:{ru:`Практический термин управления проектами «${term}». Его точный смысл зависит от выбранного workflow и контекста; PMWORK использует его как явно определённый элемент решения или контроля.`,en:`A practical project-management term, “${term}”. Its precise meaning depends on the selected workflow and context; PMWORK uses it as an explicitly defined decision or control element.`},example:{ru:`Зафиксируйте ${term} с владельцем, контекстом и критерием проверки, если это влияет на решение.`,en:`Record ${term} with an owner, context, and verification criterion when it affects a decision.`},related:[]}))];

export const contentCounts={methods:methods.length,templates:templates.length,playbooks:playbooks.length,glossary:glossary.length,knowledge:knowledgeDomains.length};
