import type { Bi } from "./catalog";
export type Glossary = {
  term: string;
  ru: string;
  definition: Bi;
  example: Bi;
  related: string[];
};
const glossarySeed: [string, string, string, string, string, string][] = [
  [
    "Acceptance Criteria",
    "Критерии приёмки",
    "Проверяемые условия, которым должен соответствовать результат.",
    "Testable conditions an outcome must meet.",
    "Форма отправляет валидные данные и показывает ошибку при неверных.",
    "The form submits valid data and shows an error for invalid input.",
  ],
  [
    "Accountable",
    "Ответственный за результат",
    "Единственный владелец конечного решения или результата в RACI.",
    "The single owner of the final decision or outcome in RACI.",
    "Спонсор утверждает базовый план.",
    "The sponsor approves the baseline.",
  ],
  [
    "Assumption",
    "Допущение",
    "Считаемое истинным утверждение, которое ещё требует проверки.",
    "A statement treated as true but still requiring validation.",
    "Поставщик предоставит API к маю.",
    "The vendor will provide the API by May.",
  ],
  [
    "BAC",
    "Бюджет по завершении",
    "Утверждённый бюджет всего объёма работ в EVM.",
    "The approved budget for all scope in EVM.",
    "BAC проекта — 500 000.",
    "Project BAC is 500,000.",
  ],
  [
    "Backlog",
    "Бэклог",
    "Упорядоченный набор потенциальной работы.",
    "An ordered set of potential work.",
    "Команда берёт следующий готовый элемент из бэклога.",
    "The team takes the next ready item from the backlog.",
  ],
  [
    "Baseline",
    "Базовый план",
    "Утверждённая версия объёма работ, сроков или стоимости для сравнения.",
    "Approved scope, schedule, or cost version used for comparison.",
    "Новый прогноз сравнивают с базовым планом сроков.",
    "The new forecast is compared to the schedule baseline.",
  ],
  [
    "Benefit",
    "Выгода",
    "Измеримое положительное изменение, получаемое после использования результата проекта.",
    "A measurable positive change realized from an outcome.",
    "Сокращение времени обработки заявки на 30%.",
    "Reducing request handling time by 30%.",
  ],
  [
    "Blocker",
    "Блокер",
    "Условие, не позволяющее работе продолжаться.",
    "A condition preventing work from progressing.",
    "Нет решения безопасности для релиза.",
    "A security decision is missing for release.",
  ],
  [
    "Business Case",
    "Бизнес-кейс",
    "Обоснование инвестиций через варианты, выгоды, затраты и риски.",
    "Investment rationale comparing options, benefits, costs, and risks.",
    "Руководящий комитет выбирает между созданием и покупкой.",
    "The steering committee chooses build versus buy.",
  ],
  [
    "Capacity",
    "Доступная мощность",
    "Реально доступный объём усилий за период после ограничений.",
    "Real effort available in a period after constraints.",
    "Из 200 часов 160 доступны проекту.",
    "Of 200 hours, 160 are available to the project.",
  ],
  [
    "Change Control",
    "Управление изменениями",
    "Способ оценить, решить и зафиксировать изменение базового плана.",
    "A way to assess, decide, and record a baseline change.",
    "Запрос на изменение добавляет неделю после анализа влияния.",
    "A change request adds one week after impact analysis.",
  ],
  [
    "Constraint",
    "Ограничение",
    "Условие, сужающее доступные варианты решения.",
    "A condition limiting available solution options.",
    "Запуск должен пройти до изменения закона.",
    "Launch must occur before a legal change.",
  ],
  [
    "Cost of Delay",
    "Стоимость задержки",
    "Потеря ценности из-за задержки поставки результата на единицу времени.",
    "Value lost by delaying delivery per unit of time.",
    "Неделя задержки сезонной кампании теряет продажи.",
    "A week of seasonal campaign delay loses sales.",
  ],
  [
    "Critical Path",
    "Критический путь",
    "Самая длинная зависимая цепочка, определяющая раннюю дату завершения.",
    "The longest dependent chain determining earliest completion.",
    "Задержка операции с нулевым резервом сдвигает завершение.",
    "Delaying a zero-float activity moves the finish.",
  ],
  [
    "CPI",
    "Индекс выполнения стоимости",
    "EV / AC; эффективность затрат в EVM.",
    "EV / AC; cost efficiency in EVM.",
    "CPI 0,9 означает, что освоенный объём ниже фактических затрат.",
    "CPI 0.9 means earned value is below actual cost.",
  ],
  [
    "Cycle Time",
    "Время цикла",
    "Время от начала до завершения рабочего элемента в заданном процессе.",
    "Elapsed time from work start to completion in a defined workflow.",
    "Элемент находился в работе 6 дней до завершения.",
    "The item spent six days from In Progress to Done.",
  ],
  [
    "Definition of Done",
    "Определение готовности",
    "Общее формальное описание качества завершённого инкремента или работы.",
    "Shared formal description of the quality of completed work.",
    "Код проверен, протестирован и развёрнут в тестовой среде.",
    "Code is reviewed, tested, and deployed to staging.",
  ],
  [
    "Deliverable",
    "Поставляемый результат",
    "Уникальный проверяемый продукт, результат или возможность проекта.",
    "A unique, verifiable product, result, or capability produced by a project.",
    "Утверждённый дизайн системы.",
    "An approved system design.",
  ],
  [
    "Dependency",
    "Зависимость",
    "Логическая связь, где одна работа влияет на возможность или срок другой.",
    "A logical relationship where one item affects another's feasibility or timing.",
    "Интеграция начинается после согласования контракта API.",
    "Integration starts after API contract approval.",
  ],
  [
    "EAC",
    "Прогноз стоимости по завершении",
    "Оценка итоговой стоимости проекта с учётом текущей результативности.",
    "Forecast total project cost considering current performance.",
    "BAC / CPI при ожидании сохранения эффективности затрат.",
    "BAC / CPI when cost performance is expected to continue.",
  ],
  [
    "Epic",
    "Эпик",
    "Крупная единица ценности, требующая декомпозиции.",
    "A large unit of value requiring decomposition.",
    "Самостоятельное подключение разбито на функциональные возможности.",
    "Self-service onboarding is split into features.",
  ],
  [
    "Escalation",
    "Эскалация",
    "Передача решения на уровень с необходимыми полномочиями.",
    "Moving a decision to a level with adequate authority.",
    "Руководитель проекта передаёт бюджетное исключение спонсору.",
    "The PM escalates a budget exception to the sponsor.",
  ],
  [
    "Estimate",
    "Оценка",
    "Модель вероятных трудозатрат, длительности или стоимости на основе доступных данных.",
    "A model of likely effort, duration, or cost based on available evidence.",
    "Задача займёт 3–5 дней, а не ровно 4.",
    "The task will take 3–5 days, not exactly four.",
  ],
  [
    "EV",
    "Освоенный объём",
    "Бюджетная стоимость фактически выполненной работы.",
    "Budgeted value of work actually completed.",
    "Выполнение 50% пакета работ с бюджетом 100 даёт EV 50.",
    "A 50% complete work package budgeted at 100 gives EV 50.",
  ],
  [
    "Float",
    "Временной резерв",
    "Допустимая задержка операции без заданного последствия для графика.",
    "Allowable activity delay without a defined schedule consequence.",
    "Общий резерв составляет 2 дня до сдвига завершения проекта.",
    "Two days of total float before project finish moves.",
  ],
  [
    "Governance",
    "Управленческий контроль",
    "Система прав принятия решений, надзора и ответственности в проекте.",
    "The system of decision rights, oversight, and project accountability.",
    "Спонсор согласует исключения выше допустимого отклонения.",
    "The sponsor approves exceptions above tolerance.",
  ],
  [
    "Issue",
    "Проблема",
    "Событие или условие, которое уже происходит и требует решения.",
    "An event or condition already occurring and requiring resolution.",
    "Поставщик пропустил договорную дату.",
    "The vendor missed a contractual date.",
  ],
  [
    "Lag",
    "Задержка связи",
    "Ожидание между зависимыми операциями.",
    "Waiting time inserted between dependent activities.",
    "Тест начинается через 2 дня после установки.",
    "Testing starts two days after installation.",
  ],
  [
    "Lead",
    "Опережение связи",
    "Разрешённое перекрытие зависимых операций.",
    "Allowed overlap between dependent activities.",
    "Документация начинается за день до завершения разработки.",
    "Documentation starts one day before build completes.",
  ],
  [
    "Milestone",
    "Контрольная точка",
    "Событие нулевой длительности, отмечающее значимое достижение или решение.",
    "A zero-duration event marking a meaningful achievement or decision.",
    "Получено согласование регулирующего органа.",
    "Regulatory approval received.",
  ],
  [
    "Outcome",
    "Изменение результата",
    "Изменение поведения или состояния, созданное использованием результата.",
    "A change in behavior or state enabled by using an output.",
    "Клиент оформляет заказ без поддержки.",
    "A customer completes an order without support.",
  ],
  [
    "Output",
    "Созданный продукт",
    "Непосредственно произведённый артефакт, продукт или услуга.",
    "The direct artifact, product, or service produced.",
    "Новая форма заказа.",
    "A new order form.",
  ],
  [
    "PV",
    "Плановый объём",
    "Бюджетная стоимость работы, запланированной к моменту измерения.",
    "Budgeted value of work planned by the measurement date.",
    "К пятнице планировали освоенный объём, эквивалентный 80.",
    "By Friday, work budgeted at 80 was planned.",
  ],
  [
    "RAID",
    "RAID",
    "Связанный обзор рисков, допущений, проблем и зависимостей.",
    "A connected view of risks, assumptions, issues, and dependencies.",
    "Еженедельный обзор RAID сосредоточен на изменившихся записях.",
    "Weekly RAID review focuses on changed items.",
  ],
  [
    "RACI",
    "RACI",
    "Матрица исполнителей, ответственных за итог, консультантов и информируемых участников.",
    "A matrix of Responsible, Accountable, Consulted, and Informed roles.",
    "За решение о выпуске отвечает один участник.",
    "One Accountable person for the release decision.",
  ],
  [
    "Risk",
    "Риск",
    "Неопределённое событие или условие с влиянием на цели.",
    "An uncertain event or condition that may affect objectives.",
    "API может не пройти нагрузку.",
    "The API may fail load targets.",
  ],
  [
    "Scope",
    "Объём работ",
    "Граница продуктов, результатов и работы, включённых в проект.",
    "Boundary of products, outcomes, and work included in a project.",
    "Мобильное приложение входит, переработка панели администратора не входит.",
    "The mobile app is in; admin redesign is out.",
  ],
  [
    "SLE",
    "Ожидаемый уровень сервиса",
    "Прогноз времени, за которое завершится заданный процент элементов.",
    "A forecast of time within which a stated percentage of items completes.",
    "85% стандартных элементов завершаются за 8 дней.",
    "85% of standard items finish within eight days.",
  ],
  [
    "SPI",
    "Индекс выполнения сроков",
    "EV / PV; показатель соблюдения сроков в методе освоенного объёма (EVM).",
    "EV / PV; schedule performance indicator in EVM.",
    "SPI ниже 1 означает меньший освоенный объём, чем планировалось.",
    "SPI below 1 means less earned work than planned.",
  ],
  [
    "Stakeholder",
    "Заинтересованная сторона",
    "Человек или группа, влияющие на проект или затронутые им.",
    "A person or group influencing or affected by the project.",
    "Новый рабочий процесс затрагивает команду поддержки.",
    "The support team is affected by the new workflow.",
  ],
  [
    "Throughput",
    "Пропускная способность",
    "Количество рабочих элементов, завершённых за единицу времени.",
    "Number of work items completed per unit of time.",
    "12 элементов завершено за неделю.",
    "Twelve items completed in a week.",
  ],
  [
    "VAC",
    "Отклонение по завершении",
    "BAC − EAC; ожидаемое бюджетное отклонение при завершении.",
    "BAC − EAC; expected budget variance at completion.",
    "VAC −20 000 указывает прогноз перерасхода.",
    "VAC of −20,000 forecasts an overrun.",
  ],
  [
    "Velocity",
    "Скорость команды",
    "Количество баллов завершённого инкремента за спринт в контексте одной команды.",
    "Points completed per Sprint in the context of one team.",
    "Используется для командного прогноза, а не сравнения людей.",
    "Used for team forecasting, not comparing individuals.",
  ],
  [
    "WIP",
    "Незавершённая работа",
    "Рабочие элементы, начатые, но ещё не завершённые.",
    "Work items started but not yet completed.",
    "В статусах «В работе» и «На проверке» сейчас 7 элементов.",
    "Seven items are currently in In Progress and Review.",
  ],
  [
    "WSJF",
    "Weighted Shortest Job First",
    "Приоритизация Cost of Delay относительно Job Size.",
    "Prioritization of Cost of Delay relative to Job Size.",
    "Высокая ценность и малый размер повышают оценку.",
    "High value and small size increase the score.",
  ],
];
const g = (
  term: string,
  ru: string,
  dr: string,
  de: string,
  er: string,
  ee: string,
  related: string[] = [],
): Glossary => ({
  term,
  ru,
  definition: { ru: dr, en: de },
  example: { ru: er, en: ee },
  related,
});
const extendedGlossary: Glossary[] = [
  g(
    "Activity",
    "Операция",
    "Элемент расписания с длительностью, ресурсами и зависимостями.",
    "A schedule element with duration, resources, and dependencies.",
    "Тестирование занимает три дня после готовности сборки.",
    "Testing takes three days after the build is ready.",
  ),
  g(
    "Actual Cost",
    "Фактическая стоимость",
    "Реальные затраты на выполненную работу к дате измерения.",
    "The real cost incurred for work performed by the measurement date.",
    "Фактическая стоимость включает счета подрядчика и часы внутренней команды.",
    "AC includes contractor invoices and internal team hours.",
  ),
  g(
    "Acceptance",
    "Приёмка",
    "Формальное подтверждение, что результат соответствует согласованным критериям.",
    "Formal confirmation that a deliverable meets agreed criteria.",
    "Владелец продукта принимает инкремент после проверки сценариев.",
    "The Product Owner accepts the increment after scenario checks.",
  ),
  g(
    "Action Owner",
    "Владелец действия",
    "Человек, отвечающий за выполнение конкретного действия к сроку.",
    "The person accountable for completing a specific action by its due date.",
    "Владелец восстановительного действия сообщает результат в пятницу.",
    "The recovery-action owner reports the result on Friday.",
  ),
  g(
    "Adaptive",
    "Адаптивный подход",
    "Подход, уточняющий решение короткими циклами на основе обратной связи.",
    "An approach that refines the solution in short cycles using feedback.",
    "Команда проверяет гипотезу каждые две недели.",
    "The team tests a hypothesis every two weeks.",
  ),
  g(
    "Affinity Mapping",
    "Аффинити-группировка",
    "Группировка множества наблюдений по естественно возникающим темам.",
    "Grouping many observations into naturally emerging themes.",
    "Интервью пользователей собрали в темы подключения и доверия.",
    "User-interview notes were grouped into onboarding and trust themes.",
  ),
  g(
    "Agile",
    "Agile",
    "Набор ценностей и принципов адаптивной разработки, а не единый процесс.",
    "A set of values and principles for adaptive development, not one process.",
    "Команда сокращает цикл обратной связи вместо механического копирования церемоний.",
    "The team shortens feedback loops instead of copying ceremonies mechanically.",
  ),
  g(
    "Artifact",
    "Артефакт",
    "Проверяемый рабочий объект, фиксирующий информацию, решение или результат.",
    "A verifiable work object that records information, a decision, or an outcome.",
    "Журнал решений хранит принятое решение и его обоснование.",
    "The decision log stores the decision and its rationale.",
  ),
  g(
    "Benefit Owner",
    "Владелец выгоды",
    "Роль, отвечающая за достижение и измерение выгоды после поставки результата.",
    "The role accountable for realizing and measuring a benefit after delivery.",
    "Директор операций измеряет сокращение времени обработки.",
    "The operations director measures the reduction in handling time.",
  ),
  g(
    "Benefits Management",
    "Управление выгодами",
    "Определение, планирование, измерение и поддержание ожидаемых выгод.",
    "Identifying, planning, measuring, and sustaining expected benefits.",
    "План выгод связывает новый процесс с экономией часов.",
    "The benefits plan links the new process to hours saved.",
  ),
  g(
    "Budget",
    "Бюджет",
    "Утверждённое распределение денежных ресурсов по категориям и периодам.",
    "The approved allocation of money across categories and periods.",
    "Бюджет разделён на разработку, лицензии и резерв.",
    "The budget is split into development, licenses, and reserve.",
  ),
  g(
    "Buffer",
    "Буфер",
    "Явный запас времени или мощности для защиты обязательства от вариации.",
    "Explicit time or capacity reserved to protect a commitment from variation.",
    "Резерв выпуска поглощает вариацию интеграционных работ.",
    "The release buffer absorbs integration-work variation.",
  ),
  g(
    "Burn-down",
    "Диаграмма сгорания",
    "График оставшегося объёма работы во времени.",
    "A chart of remaining work over time.",
    "Линия показывает 34 балла, оставшихся в спринте.",
    "The line shows 34 points remaining in the Sprint.",
  ),
  g(
    "Burn-up",
    "Диаграмма нарастания",
    "График выполненного объёма и общей границы работ во времени.",
    "A chart of completed work and total scope over time.",
    "Рост верхней линии показывает добавление объёма работ.",
    "A rising scope line reveals added scope.",
  ),
  g(
    "Cadence",
    "Каденция",
    "Регулярный ритм планирования, поставки результата, обзора или принятия решений.",
    "A regular rhythm for planning, delivery, review, or decisions.",
    "Управленческий обзор проходит каждый второй четверг.",
    "The steering review occurs every second Thursday.",
  ),
  g(
    "Change Request",
    "Запрос на изменение",
    "Формализованное предложение изменить утверждённый базовый план после оценки влияния.",
    "A formal proposal to change an approved baseline after impact assessment.",
    "Запрос добавляет новый рынок и две недели к сроку.",
    "The request adds a market and two weeks to the schedule.",
  ),
  g(
    "Charter",
    "Устав проекта",
    "Краткое разрешение проекта: цель, полномочия, границы и ключевые стороны.",
    "A concise authorization defining purpose, authority, boundaries, and key parties.",
    "Спонсор утверждает устав до детального планирования.",
    "The sponsor approves the charter before detailed planning.",
  ),
  g(
    "Checklist",
    "Чек-лист",
    "Список проверок для снижения риска пропуска в повторяемом процессе.",
    "A list of checks that reduces omissions in a repeatable process.",
    "Контрольный список выпуска требует владельца отката и мониторинга.",
    "The release checklist requires a rollback owner and monitoring.",
  ),
  g(
    "Communication Plan",
    "План коммуникаций",
    "Карта аудиторий, целей, форматов, частоты, владельцев и сигналов успеха.",
    "A map of audiences, purposes, formats, cadence, owners, and success signals.",
    "Спонсор ежемесячно получает краткую записку для решения, команда — ежедневные сигналы потока.",
    "The sponsor gets a monthly decision brief; the team gets daily flow signals.",
  ),
  g(
    "Compliance",
    "Соответствие требованиям",
    "Выполнение обязательных правовых, нормативных, договорных или внутренних требований.",
    "Meeting mandatory legal, regulatory, contractual, or internal requirements.",
    "Выпуск хранит подтверждение прохождения проверки конфиденциальности.",
    "The release retains evidence of privacy review.",
  ),
  g(
    "Consulted",
    "Консультируемый",
    "Роль RACI, чьё мнение запрашивают до выполнения или решения.",
    "The RACI role whose input is requested before work or a decision.",
    "Специалистов по безопасности консультируют до выбора архитектуры.",
    "Security is consulted before the architecture is selected.",
  ),
  g(
    "Contingency Reserve",
    "Резерв на известные риски",
    "Время или деньги в базовом плане для идентифицированных неопределённостей.",
    "Time or money within the baseline for identified uncertainty.",
    "В базовый план стоимости включён резерв на миграционные дефекты.",
    "The cost baseline includes reserve for migration defects.",
  ),
  g(
    "Contract",
    "Договор",
    "Юридически обязательное соглашение об объёме работ, цене, сроках, ответственности и изменениях.",
    "A legally binding agreement on scope, price, dates, responsibilities, and change.",
    "Договор фиксирует условия приёмки и ответственность за задержку.",
    "The contract defines acceptance and delay responsibility.",
  ),
  g(
    "Corrective Action",
    "Корректирующее действие",
    "Действие, возвращающее ожидаемую результативность к согласованному плану или допустимому отклонению.",
    "An action intended to return performance to the agreed plan or tolerance.",
    "Команда перераспределяет доступную мощность для восстановления контрольной точки.",
    "The team reallocates capacity to recover the milestone.",
  ),
  g(
    "Critical Chain",
    "Критическая цепь",
    "Подход к расписанию, учитывающий зависимость работ и ограничивающих ресурсов с буферами.",
    "A scheduling approach that considers task and constrained-resource dependencies using buffers.",
    "Один специалист создаёт ресурсное ограничение для двух веток.",
    "One specialist creates a resource constraint across two branches.",
  ),
  g(
    "Dashboard",
    "Дашборд",
    "Сжатое представление сигналов, необходимых конкретной аудитории для решения.",
    "A concise view of signals a specific audience needs to decide.",
    "Панель спонсора показывает прогноз, главные риски и решения.",
    "The sponsor dashboard shows forecast, top risks, and decisions.",
  ),
  g(
    "Decision Log",
    "Журнал решений",
    "Реестр вопросов, вариантов, критериев, решений, обоснований и последствий.",
    "A register of questions, options, criteria, decisions, rationale, and consequences.",
    "Журнал объясняет, почему выбрали создание вместо покупки.",
    "The log explains why build was chosen over buy.",
  ),
  g(
    "Definition of Ready",
    "Определение готовности к началу",
    "Локальное правило минимальных условий, при которых элемент можно осознанно начать.",
    "A local policy defining minimum conditions for intentionally starting an item.",
    "История готова, когда известны цель, критерии и зависимости.",
    "A story is ready when its goal, criteria, and dependencies are known.",
  ),
  g(
    "Dependency Density",
    "Плотность зависимостей",
    "Степень связанности работы с внешними командами, системами и решениями.",
    "The degree to which work depends on external teams, systems, and decisions.",
    "Пять межкомандных передач делают плотность зависимостей высокой.",
    "Five cross-team handoffs make dependency density high.",
  ),
  g(
    "Discovery",
    "Исследование решения",
    "Работа по снижению неопределённости проблемы, потребности и жизнеспособного решения.",
    "Work that reduces uncertainty about the problem, need, and viable solution.",
    "Прототип проверяет, понимает ли клиент новый поток работы.",
    "A prototype tests whether customers understand the new flow.",
  ),
  g(
    "Duration",
    "Длительность",
    "Календарное рабочее время между началом и завершением операции.",
    "Working time between an activity's start and finish.",
    "Длительность тестирования — четыре рабочих дня.",
    "Testing duration is four working days.",
  ),
  g(
    "Early Finish",
    "Раннее окончание",
    "Самая ранняя возможная дата завершения операции по прямому проходу.",
    "The earliest possible activity finish calculated by the forward pass.",
    "Раннее завершение равно раннему началу плюс длительность.",
    "EF equals Early Start plus duration.",
  ),
  g(
    "Early Start",
    "Раннее начало",
    "Самая ранняя возможная дата начала операции с учётом предшественников.",
    "The earliest possible activity start given predecessor constraints.",
    "Интеграция стартует после максимального раннего завершения предшественников.",
    "Integration starts after the maximum predecessor EF.",
  ),
  g(
    "Escalation Path",
    "Маршрут эскалации",
    "Заранее определённая последовательность уровней решения при превышении полномочий или допустимого отклонения.",
    "A predefined sequence of decision levels when authority or tolerance is exceeded.",
    "Отклонение стоимости выше 10% передаётся руководящему комитету.",
    "Cost variance above 10% goes to the steering committee.",
  ),
  g(
    "ETC",
    "Оценка до завершения",
    "Прогноз дополнительных затрат, необходимых для оставшейся работы.",
    "The forecast additional cost required to complete remaining work.",
    "Оценка до завершения пересчитана снизу вверх после изменения объёма работ.",
    "ETC is re-estimated bottom-up after the scope change.",
  ),
  g(
    "Experiment",
    "Эксперимент",
    "Ограниченная проверка гипотезы с ожидаемым сигналом и правилом решения.",
    "A bounded hypothesis test with an expected signal and decision rule.",
    "Пилот на 50 клиентах проверяет принятие нового процесса.",
    "A 50-customer pilot tests adoption of the new process.",
  ),
  g(
    "Feature",
    "Функция продукта",
    "Целостная возможность, создающая наблюдаемую ценность пользователю или бизнесу.",
    "A coherent capability that creates observable user or business value.",
    "Самостоятельное восстановление пароля — функциональная возможность.",
    "Self-service password recovery is a feature.",
  ),
  g(
    "Feasibility",
    "Осуществимость",
    "Реалистичность решения с учётом технологии, времени, денег, операций и ограничений.",
    "The viability of a solution given technology, time, money, operations, and constraints.",
    "Исследовательская задача подтверждает, что API выдержит требуемую нагрузку.",
    "A spike confirms the API can sustain required load.",
  ),
  g(
    "Finish-to-Finish",
    "Окончание–окончание",
    "Связь, при которой преемник не может завершиться раньше предшественника.",
    "A relationship where the successor cannot finish before the predecessor.",
    "Редактура не завершится раньше написания текста.",
    "Editing cannot finish before writing finishes.",
  ),
  g(
    "Finish-to-Start",
    "Окончание–начало",
    "Связь, при которой преемник начинается после завершения предшественника.",
    "A relationship where the successor starts after the predecessor finishes.",
    "Миграция начинается после утверждения схемы.",
    "Migration starts after schema approval.",
  ),
  g(
    "Forecast",
    "Прогноз",
    "Текущая вероятностная или сценарная оценка будущего результата на основе подтверждений.",
    "A current probabilistic or scenario estimate of a future result based on evidence.",
    "Прогноз P85 показывает диапазон готовности выпуска.",
    "A P85 forecast shows the release-completion range.",
  ),
  g(
    "Gate",
    "Контрольные ворота",
    "Точка, где уполномоченные лица решают продолжить, изменить, остановить или отложить работу.",
    "A point where authorized people decide to continue, change, stop, or defer work.",
    "Контрольная точка запуска проверяет готовность и возможность отката.",
    "The go/no-go gate checks readiness and rollback.",
  ),
  g(
    "Goal",
    "Цель",
    "Желаемое направление или состояние, которое фокусирует решения и работу.",
    "A desired direction or state that focuses decisions and work.",
    "Цель спринта объединяет элементы вокруг одной проверяемой ценности.",
    "The Sprint Goal unites items around one testable value.",
  ),
  g(
    "Hybrid",
    "Гибридный подход",
    "Осознанная композиция практик с совместимыми допущениями из разных подходов.",
    "An intentional composition of practices with compatible assumptions from different approaches.",
    "Поэтапное управление сочетается с поставкой по Kanban внутри этапа.",
    "Stage governance is combined with Kanban delivery within a stage.",
  ),
  g(
    "Impact",
    "Влияние",
    "Масштаб последствий события, решения, риска или изменения для целей.",
    "The magnitude of consequences an event, decision, risk, or change has on objectives.",
    "Отказ оплаты сильно влияет на выручку.",
    "Payment failure has high revenue impact.",
  ),
  g(
    "Impact Mapping",
    "Карта влияния",
    "Визуальная связь цели, действующих лиц, нужных изменений поведения и результатов поставки.",
    "A visual link between a goal, actors, behavior changes, and deliverables.",
    "Цель удержания связывают с поведением новичка и экспериментами по подключению.",
    "A retention goal is linked to newcomer behavior and onboarding experiments.",
  ),
  g(
    "Increment",
    "Инкремент",
    "Интегрированная проверяемая часть продукта, соответствующая критериям готовности.",
    "An integrated, verifiable piece of product meeting the Definition of Done.",
    "Инкремент доступен в тестовой среде и проходит приёмочные испытания.",
    "The increment is available on staging and passes acceptance tests.",
  ),
  g(
    "Influence",
    "Влияние заинтересованной стороны",
    "Способность заинтересованной стороны менять решения, ресурсы или успех проекта.",
    "A stakeholder's ability to affect decisions, resources, or project success.",
    "Регулятор имеет высокое влияние независимо от ежедневного интереса.",
    "A regulator has high influence regardless of daily interest.",
  ),
  g(
    "Initiative",
    "Инициатива",
    "Крупное стратегическое направление, объединяющее несколько измеримых результатов или эпиков.",
    "A large strategic effort grouping multiple outcomes or epics.",
    "Инициатива самообслуживания включает подключение, оплату и поддержку.",
    "The self-service initiative includes onboarding, billing, and support.",
  ),
  g(
    "Informed",
    "Информируемый",
    "Роль RACI, которую уведомляют о ходе или решении без запроса согласования.",
    "The RACI role kept updated without being asked for approval.",
    "Службу поддержки информируют о дате выпуска и известных ограничениях.",
    "Support is informed of the release date and known limitations.",
  ),
  g(
    "Iteration",
    "Итерация",
    "Ограниченный период или цикл, завершающийся проверяемым результатом и обучением.",
    "A bounded period or cycle ending with a verifiable result and learning.",
    "Двухнедельная итерация завершается демонстрацией и обзором данных.",
    "A two-week iteration ends with a demo and data review.",
  ),
  g(
    "Kanban",
    "Канбан",
    "Метод управления потоком через визуализацию, явные правила, лимиты WIP и циклы обратной связи.",
    "A flow-management method using visualization, explicit policies, WIP limits, and feedback loops.",
    "Команда ограничивает статус «На проверке» двумя элементами и измеряет время цикла.",
    "The team limits Review to two items and measures cycle time.",
  ),
  g(
    "KPI",
    "Ключевой показатель",
    "Метрика, отражающая критически важный аспект достижения цели, а не любую активность.",
    "A metric reflecting a critical aspect of goal achievement, not any activity.",
    "KPI подключения — доля пользователей, достигших первой ценности.",
    "The onboarding KPI is the share of users reaching first value.",
  ),
  g(
    "Late Finish",
    "Позднее окончание",
    "Самая поздняя дата завершения операции без нарушения выбранной конечной даты.",
    "The latest an activity may finish without violating the selected completion date.",
    "Позднее завершение вычисляют обратным проходом от завершающей контрольной точки.",
    "LF is calculated backward from the finish milestone.",
  ),
  g(
    "Late Start",
    "Позднее начало",
    "Самая поздняя дата начала операции без нарушения выбранной конечной даты.",
    "The latest an activity may start without violating the selected completion date.",
    "Позднее начало равно позднему завершению минус длительность.",
    "LS equals Late Finish minus duration.",
  ),
  g(
    "Lesson Learned",
    "Извлечённый урок",
    "Подтверждённый вывод из опыта с рекомендацией для будущего поведения.",
    "An evidence-backed insight from experience with a recommendation for future behavior.",
    "Ранний контрактный тест снижает объём переделок интеграции.",
    "An early contract test reduces integration rework.",
  ),
  g(
    "Little's Law",
    "Закон Литтла",
    "Для стабильной системы средний WIP равен пропускной способности, умноженной на время цикла.",
    "For a stable system, average WIP equals throughput multiplied by cycle time.",
    "При WIP 12 и пропускной способности 3 время цикла составляет около 4 периодов.",
    "With WIP 12 and throughput 3, cycle time is about four periods.",
  ),
  g(
    "Management Reserve",
    "Управленческий резерв",
    "Бюджет вне базового плана стоимости для неизвестных неопределённостей под управленческим контролем.",
    "Budget outside the cost baseline for unknown uncertainty under management control.",
    "Спонсор разрешает использование резерва после выявления нового системного риска.",
    "The sponsor authorizes reserve use after a new systemic risk.",
  ),
  g(
    "Mitigation",
    "Снижение риска",
    "Действия, уменьшающие вероятность или негативное влияние угрозы до её реализации.",
    "Actions reducing the probability or negative impact of a threat before it occurs.",
    "Нагрузочный тест снижает вероятность отказа при запуске.",
    "Load testing reduces launch-failure probability.",
  ),
  g(
    "Monte Carlo Simulation",
    "Моделирование Монте-Карло",
    "Многократная выборка из исторических или заданных распределений для диапазона исходов.",
    "Repeated sampling from historical or specified distributions to estimate outcome ranges.",
    "Пять тысяч прогонов дают прогнозы завершения P50 и P85.",
    "Five thousand runs produce P50 and P85 completion forecasts.",
  ),
  g(
    "MoSCoW",
    "MoSCoW",
    "Классификация «обязательно», «следует», «можно» и «не сейчас» для границы конкретного периода или релиза.",
    "Must, Should, Could, and Won't classification for a specific period or release boundary.",
    "«Не сейчас» означает не в этом релизе, а не никогда.",
    "Won't means not in this release, not never.",
  ),
  g(
    "Objective",
    "Измеримая цель",
    "Конкретное желаемое состояние, направляющее выбор результатов и метрик.",
    "A specific desired state guiding deliverables and measures.",
    "Сократить медианное время подключения с 20 до 10 минут.",
    "Reduce median onboarding time from 20 to 10 minutes.",
  ),
  g(
    "Opportunity",
    "Положительный риск",
    "Неопределённое событие, которое может улучшить достижение целей.",
    "An uncertain event that may improve achievement of objectives.",
    "Партнёр может дать бесплатный канал привлечения.",
    "A partner may provide a free acquisition channel.",
  ),
  g(
    "Owner",
    "Владелец",
    "Названный человек с ясной ответственностью и достаточными полномочиями для результата.",
    "A named person with clear accountability and sufficient authority for an outcome.",
    "Владелец риска отслеживает условие срабатывания и запускает реагирование.",
    "The risk owner monitors the trigger and starts the response.",
  ),
  g(
    "PERT",
    "PERT",
    "Трёхточечная оценка ожидаемой длительности: (O + 4M + P) / 6.",
    "A three-point expected-duration estimate: (O + 4M + P) / 6.",
    "Оценки 3, 5 и 10 дают ожидаемое значение 5,5.",
    "Estimates of 3, 5, and 10 give an expected value of 5.5.",
  ),
  g(
    "PMO",
    "Проектный офис",
    "Функция, развивающая модель управления, организационные возможности, информацию о портфеле и поддержку поставки результата.",
    "A function supporting governance, capability, portfolio information, and delivery.",
    "Проектный офис стандартизирует данные для решений, а не только шаблоны.",
    "The PMO standardizes decision data, not only templates.",
  ),
  g(
    "Portfolio",
    "Портфель",
    "Совокупность инвестиций, управляемых для стратегического выбора и баланса ресурсов.",
    "A collection of investments managed for strategic choice and resource balance.",
    "Портфель прекращает проект с низкой ценностью ради более сильного.",
    "The portfolio stops a low-value project to fund a stronger one.",
  ),
  g(
    "Predictive",
    "Предиктивный подход",
    "Подход с заранее определяемым базовым объёмом работ и плановым контролем изменений.",
    "An approach using an up-front scope baseline and planned change control.",
    "Строительный этап исполняется по утверждённому базовому плану сроков.",
    "The construction phase follows an approved schedule baseline.",
  ),
  g(
    "Priority",
    "Приоритет",
    "Относительный порядок работы по ценности, срочности, риску и ограничениям.",
    "The relative order of work based on value, urgency, risk, and constraints.",
    "Обязательное нормативное исправление важнее косметического улучшения.",
    "A regulatory fix ranks above a cosmetic improvement.",
  ),
  g(
    "Probability",
    "Вероятность",
    "Оценка шанса наступления неопределённого события в заданном горизонте.",
    "An estimate of an uncertain event occurring within a defined horizon.",
    "Команда оценивает 3 из 5 на следующий квартал.",
    "The team rates it 3 of 5 for the next quarter.",
  ),
  g(
    "Procurement",
    "Закупки",
    "Получение товаров или услуг извне через выбор, договор и контроль поставщика.",
    "Obtaining external goods or services through selection, contracting, and supplier control.",
    "Запрос предложений сравнивает поставщиков по полной стоимости и риску поставки.",
    "The RFP compares vendors on total cost and delivery risk.",
  ),
  g(
    "Product Backlog",
    "Бэклог продукта",
    "Упорядоченный изменяемый список того, что может улучшить продукт.",
    "An ordered, evolving list of what may improve a product.",
    "Владелец продукта меняет порядок после получения подтверждений от заказчика.",
    "The Product Owner reorders it after customer evidence.",
  ),
  g(
    "Program",
    "Программа",
    "Связанные проекты и изменения, координируемые для выгод, недоступных по отдельности.",
    "Related projects and change managed together for benefits unavailable separately.",
    "CRM, обучение и переработка процесса образуют программу.",
    "CRM, training, and process redesign form a program.",
  ),
  g(
    "Project",
    "Проект",
    "Временное предприятие для создания уникального продукта, услуги или результата.",
    "A temporary endeavor undertaken to create a unique product, service, or result.",
    "Проект завершается после передачи новой платформы владельцу.",
    "The project closes after the new platform is handed over.",
  ),
  g(
    "Project Brief",
    "Краткое описание проекта",
    "Ранний документ о проблеме, вариантах, ожидаемой ценности, масштабе и ограничениях.",
    "An early document outlining the problem, options, expected value, scale, and constraints.",
    "Краткое описание позволяет решить, стоит ли готовить экономическое обоснование.",
    "The brief supports the decision to develop a business case.",
  ),
  g(
    "Project Lifecycle",
    "Жизненный цикл проекта",
    "Последовательность фаз от возникновения идеи до закрытия и передачи результата.",
    "The sequence of phases from idea through closure and handover.",
    "Жизненный цикл включает инициацию, планирование, поставку результата и закрытие.",
    "The lifecycle includes initiation, planning, delivery, and closure.",
  ),
  g(
    "Quality",
    "Качество",
    "Степень соответствия результата требованиям и пригодности для ожидаемого использования.",
    "The degree to which an outcome meets requirements and is fit for intended use.",
    "Форма точна, доступна и выдерживает ожидаемую нагрузку.",
    "The form is accurate, accessible, and handles expected load.",
  ),
  g(
    "Quality Gate",
    "Контроль качества",
    "Проверяемый набор критериев и подтверждений перед переходом или выпуском.",
    "A verifiable set of criteria and evidence required before progression or release.",
    "Контрольная точка требует пройденных тестов, подтверждения владельца и плана отката.",
    "The gate requires passed tests, owner sign-off, and a rollback plan.",
  ),
  g(
    "RACI Matrix",
    "Матрица RACI",
    "Таблица распределения исполнителей, ответственных за итог, консультантов и информируемых участников по результатам.",
    "A table assigning Responsible, Accountable, Consulted, and Informed roles to outcomes.",
    "У каждого результата поставки один ответственный за итог.",
    "Each deliverable has one Accountable person.",
  ),
  g(
    "Release",
    "Релиз",
    "Согласованное предоставление набора изменений пользователям или в эксплуатацию.",
    "The coordinated delivery of a set of changes to users or operations.",
    "Выпуск проходит поэтапно с мониторингом и возможностью отката.",
    "The release is staged with monitoring and rollback.",
  ),
  g(
    "Requirements Volatility",
    "Изменчивость требований",
    "Частота и масштаб значимых изменений требований за период.",
    "The frequency and magnitude of material requirement changes over time.",
    "Высокая изменчивость требует коротких циклов проверки.",
    "High volatility calls for short validation loops.",
  ),
  g(
    "Residual Risk",
    "Остаточный риск",
    "Риск, остающийся после выполнения выбранного реагирования.",
    "Risk remaining after the selected response is implemented.",
    "После переключения на резерв остаётся риск ухудшения производительности.",
    "After failover, performance degradation risk remains.",
  ),
  g(
    "Resource",
    "Ресурс",
    "Человек, оборудование, материал, деньги или возможность, необходимые для работы.",
    "A person, equipment, material, money, or capability required for work.",
    "Среда тестирования — ограничивающий ресурс.",
    "The test environment is a constrained resource.",
  ),
  g(
    "Responsible",
    "Исполнитель",
    "Роль RACI, непосредственно выполняющая работу для результата.",
    "The RACI role that performs the work to produce an outcome.",
    "Аналитик отвечает за подготовку модели требований.",
    "The analyst is Responsible for the requirements model.",
  ),
  g(
    "Retrospective",
    "Ретроспектива",
    "Регулярный разбор способа работы с выбором конкретного эксперимента по улучшению.",
    "A regular review of how work is done that selects a concrete improvement experiment.",
    "Команда ограничивает один эксперимент до следующего спринта.",
    "The team limits itself to one experiment until the next Sprint.",
  ),
  g(
    "RICE",
    "RICE",
    "Приоритизация через охват × влияние × уверенность / трудозатраты.",
    "Prioritization using Reach × Impact × Confidence / Effort.",
    "Низкая уверенность уменьшает оценку сомнительной идеи.",
    "Low confidence reduces the score of a speculative idea.",
  ),
  g(
    "Risk Appetite",
    "Аппетит к риску",
    "Общий объём и тип риска, который организация готова принять ради целей.",
    "The amount and type of risk an organization is willing to pursue or retain.",
    "Компания принимает риск исследования, но не нарушения конфиденциальности.",
    "The company accepts discovery risk but not privacy violations.",
  ),
  g(
    "Risk Exposure",
    "Экспозиция риска",
    "Сочетание вероятности и влияния, используемое для сравнения рисков.",
    "A combination of probability and impact used to compare risks.",
    "Риск 4×5 получает экспозицию 20.",
    "A 4×5 risk has exposure 20.",
  ),
  g(
    "Risk Owner",
    "Владелец риска",
    "Человек, отвечающий за наблюдение риска, реагирование и эскалацию.",
    "The person accountable for monitoring a risk, its response, and escalation.",
    "Технический руководитель следит за условием предельной нагрузки API.",
    "The tech lead monitors the API capacity trigger.",
  ),
  g(
    "Risk Register",
    "Реестр рисков",
    "Живой список рисков с причинами, последствиями, экспозицией, владельцем, мерами и обзором.",
    "A living list of risks with causes, effects, exposure, owner, response, and review.",
    "Еженедельный обзор обновляет условия срабатывания и остаточную экспозицию.",
    "The weekly review updates triggers and residual exposure.",
  ),
  g(
    "Roadmap",
    "Дорожная карта",
    "Временная коммуникация направления, измеримых результатов и крупных ставок с неопределённостью.",
    "A time-oriented communication of direction, outcomes, and major bets with uncertainty.",
    "Дорожная карта показывает «сейчас», «далее» и «позже», а не ложные точные даты.",
    "The roadmap shows Now, Next, and Later rather than false precision.",
  ),
  g(
    "Rolling-wave Planning",
    "Планирование набегающей волной",
    "Детальный ближний план и укрупнённый дальний план, уточняемый по мере обучения.",
    "Detailed near-term planning with higher-level future planning refined as learning emerges.",
    "Следующие две недели детальны, следующий квартал — по контрольным точкам.",
    "The next two weeks are detailed; the next quarter is milestone-level.",
  ),
  g(
    "SAFe",
    "SAFe",
    "Коммерческая масштабная методика для координации бережливой и адаптивной поставки в крупных организациях.",
    "A commercial scaling framework for coordinating Lean-Agile delivery in large organizations.",
    "Несколько команд синхронизируют планирование в общем ритме.",
    "Multiple teams synchronize planning on a common cadence.",
  ),
  g(
    "Schedule",
    "Расписание",
    "Модель дат, длительностей, зависимостей, ресурсов и контрольных точек проекта.",
    "A model of project dates, durations, dependencies, resources, and milestones.",
    "График показывает критический путь и доступный временной резерв.",
    "The schedule shows the critical path and available float.",
  ),
  g(
    "Scrum",
    "Scrum",
    "Лёгкая методика, в которой команда создаёт ценность через спринты, проверку и адаптацию.",
    "A lightweight framework for creating value through Sprints, inspection, and adaptation.",
    "Каждый спринт создаёт пригодный инкремент и обновляет бэклог.",
    "Each Sprint creates a usable Increment and updates the backlog.",
  ),
  g(
    "Scrum Master",
    "Scrum-мастер",
    "Роль Scrum, отвечающая за эффективность команды и корректное применение методики.",
    "The Scrum accountability for team effectiveness and proper use of the framework.",
    "Scrum-мастер помогает устранить системную блокировку потока.",
    "The Scrum Master helps remove a systemic flow blocker.",
  ),
  g(
    "Scope Creep",
    "Неконтролируемое расширение объёма работ",
    "Добавление работы без явного решения, анализа влияния и обновления обязательств.",
    "Work added without an explicit decision, impact analysis, or updated commitments.",
    "Новый отчёт добавили, не меняя срок и доступную мощность.",
    "A new report was added without changing date or capacity.",
  ),
  g(
    "Sponsor",
    "Спонсор",
    "Старший владелец экономического обоснования, полномочий и ключевой поддержки проекта.",
    "The senior owner of the business case, authority, and executive support.",
    "Спонсор решает исключение, превышающее допустимое отклонение проекта.",
    "The sponsor decides exceptions beyond project tolerance.",
  ),
  g(
    "Sprint",
    "Спринт",
    "Фиксированный временной контейнер Scrum продолжительностью месяц или меньше.",
    "A fixed-length Scrum timebox of one month or less.",
    "Двухнедельный спринт завершается ценным инкрементом.",
    "A two-week Sprint ends with a valuable Increment.",
  ),
  g(
    "Sprint Backlog",
    "Бэклог спринта",
    "Цель спринта, выбранные элементы бэклога продукта и план их выполнения разработчиками.",
    "The Sprint Goal, selected Product Backlog items, and developers' delivery plan.",
    "Команда обновляет план ежедневно по мере обучения.",
    "Developers update the plan daily as they learn.",
  ),
  g(
    "Sprint Goal",
    "Цель спринта",
    "Единая цель, объясняющая ценность спринта и допускающая гибкость состава работы.",
    "The single objective explaining Sprint value while allowing scope flexibility.",
    "Цель — подтвердить поток самостоятельной активации.",
    "The goal is to validate the self-service activation flow.",
  ),
  g(
    "Sprint Review",
    "Обзор спринта",
    "Рабочая сессия проверки результата и адаптации бэклога продукта с заинтересованными сторонами.",
    "A working session to inspect outcomes and adapt the Product Backlog with stakeholders.",
    "Команда обсуждает данные использования, а не только демонстрирует возможности.",
    "The team discusses usage evidence, not only feature demos.",
  ),
  g(
    "Stage-Gate",
    "Этапно-контрольная модель",
    "Разделение инициативы на этапы с инвестиционным решением в каждой контрольной точке.",
    "Dividing an initiative into stages with an investment decision at each gate.",
    "После проверки прототипа проект масштабируют, перерабатывают или закрывают.",
    "After the prototype gate, the project is scaled, revised, or stopped.",
  ),
  g(
    "Start-to-Start",
    "Начало–начало",
    "Связь, при которой преемник не может начаться раньше предшественника.",
    "A relationship where the successor cannot start before the predecessor starts.",
    "Редактура главы начинается после начала написания.",
    "Chapter editing starts after writing starts.",
  ),
  g(
    "Status Report",
    "Статус-отчёт",
    "Сжатый отчёт об изменениях, прогнозе, рисках, решениях и необходимой помощи.",
    "A concise report of changes, forecast, risks, decisions, and help needed.",
    "Отчёт показывает новый прогноз и два решения спонсора.",
    "The report shows the new forecast and two sponsor decisions.",
  ),
  g(
    "Steering Committee",
    "Руководящий комитет",
    "Группа, принимающая межфункциональные решения и контролирующая стратегическое соответствие.",
    "A group making cross-functional decisions and overseeing strategic alignment.",
    "Комитет решает исключение по финансированию и компромисс по объёму работ.",
    "The committee decides a funding exception and scope trade-off.",
  ),
  g(
    "Story",
    "История",
    "Небольшая единица потребности или ценности, уточняемая через разговор и критерии.",
    "A small unit of need or value refined through conversation and criteria.",
    "История описывает восстановление доступа пользователем.",
    "The story describes a user recovering access.",
  ),
  g(
    "Story Point",
    "Баллы истории",
    "Относительная командная оценка размера работы с учётом сложности и неопределённости.",
    "A team-relative estimate of work size considering complexity and uncertainty.",
    "Команда оценивает элемент в 5 баллов относительно эталонов.",
    "The team estimates an item at five points against references.",
  ),
  g(
    "Success Criteria",
    "Критерии успеха",
    "Заранее определённые измеримые условия, по которым оценивается достижение цели.",
    "Predefined measurable conditions used to judge goal achievement.",
    "Активация растёт до 60% без увеличения обращений в поддержку.",
    "Activation reaches 60% without increasing support contacts.",
  ),
  g(
    "Swimlane",
    "Дорожка процесса",
    "Горизонтальная или вертикальная зона доски для класса работы, владельца или потока.",
    "A horizontal or vertical board lane for a work class, owner, or flow.",
    "Срочная дорожка имеет отдельное правило и лимит WIP.",
    "The expedite lane has its own policy and WIP limit.",
  ),
  g(
    "Tailoring",
    "Адаптация метода",
    "Осознанное изменение практик под контекст с сохранением назначения и контроля.",
    "Intentional adaptation of practices to context while preserving purpose and control.",
    "Малый проект объединяет два обзора, но сохраняет права принятия решений.",
    "A small project combines two reviews while retaining decision rights.",
  ),
  g(
    "Task",
    "Задача",
    "Конкретная единица работы, необходимая для более крупного результата.",
    "A concrete unit of work needed for a larger outcome.",
    "Настроить телеметрию для контроля выпуска — отдельная задача.",
    "Configure telemetry for the release gate is a task.",
  ),
  g(
    "Team Autonomy",
    "Автономность команды",
    "Степень самостоятельности команды в способе работы и локальных решениях.",
    "The degree of team independence over how work is done and local decisions.",
    "Команда выбирает решение внутри согласованных ограничений.",
    "The team chooses the solution within agreed constraints.",
  ),
  g(
    "Theme",
    "Тема",
    "Крупная смысловая группа инициатив или измеримых результатов для стратегической коммуникации.",
    "A broad grouping of initiatives or outcomes for strategic communication.",
    "Тема доверия объединяет безопасность, прозрачность и работу поддержки.",
    "The trust theme groups security, transparency, and support work.",
  ),
  g(
    "Tolerance",
    "Допуск",
    "Разрешённый диапазон отклонения, внутри которого уровень управления действует автономно.",
    "An allowed variance range within which a management level acts autonomously.",
    "Руководитель проекта управляет сроком в пределах ±5 дней без эскалации.",
    "The PM manages within a ±5-day schedule tolerance without escalation.",
  ),
  g(
    "Trigger",
    "Триггер риска",
    "Наблюдаемый сигнал, указывающий на приближение или наступление риска.",
    "An observable signal that a risk is approaching or occurring.",
    "Задержка P95 выше 800 мс запускает план масштабирования.",
    "P95 latency above 800 ms triggers the scaling plan.",
  ),
  g(
    "Uncertainty",
    "Неопределённость",
    "Недостаток знания о событиях, оценках, потребностях или причинных связях.",
    "Lack of knowledge about events, estimates, needs, or causal relationships.",
    "Неизвестно, примут ли клиенты новый процесс ценообразования.",
    "It is unknown whether customers will adopt the new pricing flow.",
  ),
  g(
    "User Story",
    "Пользовательская история",
    "Формулировка потребности пользователя, служащая началом разговора, а не полной спецификацией.",
    "A statement of user need that starts a conversation rather than serving as a full specification.",
    "Как клиент, я хочу восстановить доступ без звонка.",
    "As a customer, I want to recover access without calling support.",
  ),
  g(
    "Validation",
    "Валидация",
    "Получение подтверждений, что выбранное решение отвечает реальной потребности и цели.",
    "Gathering evidence that a chosen solution meets a real need and objective.",
    "Пилот показывает, используют ли операторы новый рабочий процесс.",
    "A pilot shows whether operators use the new workflow.",
  ),
  g(
    "Value",
    "Ценность",
    "Полезный эффект для заинтересованной стороны или организации относительно затрат, риска и альтернатив.",
    "A beneficial effect for a stakeholder or organization relative to cost, risk, and alternatives.",
    "Снижение ошибок создаёт ценность клиенту и операциям.",
    "Reducing errors creates value for customers and operations.",
  ),
  g(
    "Variance",
    "Отклонение",
    "Разница между базовым планом или ожиданием и фактическим либо прогнозным результатом.",
    "The difference between a baseline or expectation and actual or forecast performance.",
    "Отклонение по срокам показывает отставание относительно плана.",
    "Schedule variance shows delay against the plan.",
  ),
  g(
    "Vendor",
    "Поставщик",
    "Внешняя сторона, предоставляющая продукт или услугу по соглашению.",
    "An external party providing a product or service under an agreement.",
    "Поставщик отвечает за контрольную точку размещения и уровни обслуживания.",
    "The vendor owns the hosting milestone and service levels.",
  ),
  g(
    "Waterfall",
    "Каскадная модель",
    "Последовательная модель жизненного цикла с преимущественно поэтапным переходом между фазами.",
    "A sequential lifecycle model with primarily phase-by-phase progression.",
    "После утверждения дизайна начинается этап разработки.",
    "The build phase begins after design approval.",
  ),
  g(
    "Work Breakdown Structure",
    "Иерархическая структура работ",
    "Иерархическая декомпозиция полного объёма работ на управляемые элементы.",
    "A hierarchical decomposition of total scope into manageable components.",
    "Результат поставки разложен до рабочих пакетов с ясными границами.",
    "The deliverable is decomposed into bounded work packages.",
  ),
  g(
    "Work Item",
    "Рабочий элемент",
    "Отслеживаемая единица спроса или работы, проходящая через рабочий процесс.",
    "A trackable unit of demand or work moving through a workflow.",
    "Ошибка проходит статусы «Готово к работе», «В работе», «На проверке» и «Выполнено».",
    "A bug moves through Ready, In Progress, Review, and Done.",
  ),
  g(
    "Work Item Age",
    "Возраст рабочего элемента",
    "Время с начала активной работы над незавершённым элементом до текущего момента.",
    "Elapsed time since an unfinished item entered active work.",
    "Возраст элемента 14 дней превышает обычный SLE.",
    "An item age of 14 days exceeds the usual SLE.",
  ),
  g(
    "Work Package",
    "Пакет работ",
    "Нижний управляемый компонент WBS, который можно оценить, назначить и контролировать.",
    "The lowest manageable WBS component that can be estimated, assigned, and controlled.",
    "Пакет миграции имеет владельца, стоимость и условия приёмки.",
    "The migration work package has an owner, cost, and acceptance.",
  ),
];
export const glossary: Glossary[] = [
  ...glossarySeed.map(([term, ru, dr, de, er, ee]) => ({
    term,
    ru,
    definition: { ru: dr, en: de },
    example: { ru: er, en: ee },
    related: [],
  })),
  ...extendedGlossary,
];
