import {methodCombinations} from './method-combinations.ts';
import type { Bi, Method } from './catalog';
const bi=(ru:string,en:string):Bi=>({ru,en});
/** Original PMWORK implementation notes; these are tailoring advice, not additional standard requirements. */
const practices: Record<string,[string,string,string,string,string,string,string,string]> = {
 predictive:['Стабильные результаты; оценка до обязательства','Stable deliverables; estimate before commitment','Устав, WBS, базовый план, журнал изменений','Charter, WBS, baseline, change log','Обзор отклонений по контрольным точкам','Variance review at milestones','Фиксировать план до проверки зависимостей','Freezing a plan before checking dependencies'],
 waterfall:['Передача принятого результата следующей стадии','Accepted outputs handed to the next stage','Требования, проектное решение, протокол проверки','Requirements, design, verification record','Приёмка на границе стадии','Acceptance at stage boundaries','Откладывать интеграцию до финала','Deferring integration until the end'],
 agile:['Короткая обратная связь по работающему результату','Short feedback loops on working outcomes','Приоритетный backlog и проверяемые результаты','Ordered backlog and verifiable outcomes','Регулярная проверка результата с получателями','Regular outcome inspection with recipients','Называть отсутствие планирования гибкостью','Calling absence of planning agility'],
 hybrid:['Стабильные обязательства сверху, адаптация исполнения внутри','Stable outer commitments with adaptive delivery','Контрольные точки, backlog, правила изменения границ','Milestones, backlog, boundary-change rules','Обзоры этапов и короткие циклы выполнения','Stage reviews and short delivery cycles','Два несогласованных источника приоритетов','Two conflicting sources of priorities'],
 scrum:['Цель Sprint и пригодный к использованию Increment','Sprint Goal and usable Increment','Бэклог продукта, бэклог Sprint, инкремент','Product Backlog, Sprint Backlog, Increment','Sprint до месяца; проверка и адаптация внутри него','Sprint of one month or less; inspect and adapt within it','Считать Sprint обещанием неизменного списка задач','Treating a Sprint as a fixed task-list promise'],
 kanban:['Явные правила потока и контроль незавершённой работы','Explicit flow policies and WIP control','Определение потока, доска, SLE, данные движения','Workflow definition, board, SLE, flow data','Пополнение по доступной мощности; проверка стареющей работы','Replenish for available capacity; inspect aging work','Добавить доску без ограничения начатой работы','Adding a board without controlling started work'],
 scrumban:['Планирование цели сочетается с вытягиванием работы','Goal planning combined with pull-based work','Доска, лимиты WIP, цель цикла','Board, WIP limits, cycle goal','Пополнение по потребности; регулярная ретроспектива','Replenish as needed; regular retrospective','Сохранять Sprint-обязательства при бесконтрольном входящем потоке','Keeping Sprint commitments with uncontrolled arrivals'],
 lean:['Устранение потерь в полном потоке создания ценности','Reduce waste across the whole value stream','Карта потока, очередь улучшений, проверка эффекта','Value-stream map, improvement queue, effect check','Малые эксперименты с измерением до и после','Small experiments measured before and after','Ускорять один участок ценой очереди на следующем','Speeding one stage while creating a downstream queue'],
 xp:['Малая поставка поддерживается инженерной обратной связью','Small releases supported by engineering feedback','Автотесты, интегрированный код, короткие истории','Automated tests, integrated code, short stories','Непрерывная интеграция и частые малые релизы','Continuous integration and frequent small releases','Требовать частых релизов без защиты от регрессий','Demanding frequent releases without regression protection'],
 prince2:['Делегирование по этапам и допускам','Delegate through stages and tolerances','Обоснование, план этапа, журнал проблем','Business justification, stage plan, issue log','Решение о следующем этапе по актуальному обоснованию','Decide the next stage using current justification','Заполнять документы без проверки жизнеспособности','Completing documents without testing viability'],
 cpm:['Связи и длительности определяют раннее завершение','Links and durations determine earliest completion','Сетевая модель, критический путь, резервы','Network model, critical path, float','Пересчёт после изменения длительности или связи','Recalculate after duration or dependency changes','Принимать ресурсно неограниченный план за выполнимое обещание','Treating a resource-unconstrained plan as a feasible promise'],
 'critical-chain':['Ограничения ресурсов и буферы защищают завершение','Resource constraints and buffers protect completion','Ресурсно согласованный план и буферы','Resource-feasible schedule and buffers','Контроль расходования буфера относительно прогресса','Track buffer consumption against progress','Прятать локальные запасы и общий буфер одновременно','Hiding local safety while also adding a shared buffer'],
 'stage-gate':['Продолжение финансирования зависит от доказательств','Continued funding depends on evidence','Критерии ворот, доказательства, решение go/hold/stop','Gate criteria, evidence, go/hold/stop decision','Решение на границе инвестиционного этапа','Decision at investment-stage boundaries','Проводить ворота, на которых остановка невозможна','Running gates where stopping is impossible'],
 'lean-startup':['Проверять рискованное допущение до масштабирования','Test the riskiest assumption before scaling','Гипотеза, эксперимент, критерий решения','Hypothesis, experiment, decision criterion','Цикл проверки заканчивается решением продолжать или менять','A validation cycle ends with a persevere or change decision','Считать регистрации доказательством устойчивого спроса','Treating registrations as proof of sustained demand'],
 'design-thinking':['Понять пользовательскую ситуацию до выбора решения','Understand the user situation before choosing a solution','Наблюдения, формулировка проблемы, прототип','Observations, problem statement, prototype','Итерации исследования и проверки прототипов','Research and prototype-test iterations','Превращать эмпатию в догадки без наблюдений','Replacing observed user needs with guesses'],
 scaling:['Координировать общий результат и межкомандные зависимости','Coordinate shared outcomes and cross-team dependencies','Общие цели, карта зависимостей, интегрированный результат','Shared objectives, dependency map, integrated outcome','Совместные обзоры интеграции и ограничений','Joint reviews of integration and constraints','Увеличивать число церемоний вместо уменьшения зависимостей','Adding ceremonies instead of reducing dependencies'],
};
const operatingDetails:Record<string,[string,string,string,string]> = {
 predictive:['Спонсор утверждает базовый план; PM координирует; владельцы пакетов подтверждают оценки.','Sponsor approves the baseline; PM coordinates; work-package owners confirm estimates.','Отклонение контрольных точек, прогноз затрат, изменения согласованного объёма.','Milestone variance, cost forecast and changes to agreed scope.'],
 waterfall:['Владелец требований, проектировщики, исполнители и независимая приёмка согласуют передачи.','Requirements owner, designers, implementers and acceptance reviewers agree handoffs.','Дефекты передачи между стадиями и объём переделок после приёмки.','Handoff defects and rework after stage acceptance.'],
 agile:['Владелец продукта задаёт приоритет; команда выбирает способ поставки; пользователи проверяют результат.','Product ownership sets priorities; the team chooses delivery tactics; users inspect outcomes.','Время до обратной связи, полезность результата, частота поставки и дефекты.','Time to feedback, outcome usefulness, delivery frequency and defects.'],
 hybrid:['Спонсор управляет ограничениями; PM связывает этапы; продуктовая команда управляет backlog.','Sponsor owns constraints; PM connects stages; the product team manages the backlog.','Стабильность обязательств на этапах и поток внутри этапа.','Stage-commitment stability and flow within each stage.'],
 scrum:['Product Owner, Scrum Master и Developers несут разные зоны ответственности внутри Scrum Team.','Product Owner, Scrum Master and Developers hold distinct accountabilities within the Scrum Team.','Прогресс к Product Goal и Sprint Goal; качество пригодного Increment.','Progress toward Product and Sprint Goals; quality of the usable Increment.'],
 kanban:['Существующие владельцы сервиса согласуют правила; участники активно управляют работой в потоке.','Existing service owners agree policies; participants actively manage work in the flow.','WIP, throughput, возраст незавершённой работы и cycle time.','WIP, throughput, work-item age and cycle time.'],
 scrumban:['Команда и владелец приоритета договариваются о пополнении; фасилитатор помогает устранять блокеры.','Team and priority owner agree replenishment; a facilitator helps resolve blockers.','Возраст очередей, пропускная способность и достижение цели цикла.','Queue age, throughput and cycle-goal achievement.'],
 lean:['Владелец потока отвечает за целое; участники процесса проверяют локальные улучшения на общий эффект.','Value-stream ownership protects the whole; process participants check local changes for system effects.','Время ожидания, переделки, размер партии и время до ценности.','Waiting time, rework, batch size and time to value.'],
 xp:['Разработчики поддерживают инженерные практики; представитель заказчика уточняет ожидаемое поведение.','Developers maintain engineering practices; a customer representative clarifies expected behavior.','Время интеграции, сбои сборки, дефекты после релиза и скорость обратной связи тестов.','Integration time, build failures, escaped defects and test feedback time.'],
 prince2:['Совет проекта направляет; PM управляет этапом; владельцы командных работ отвечают за продукты.','Project board directs; PM manages the stage; team-work owners deliver products.','Допуски этапа, актуальность обоснования и готовность продуктов к приёмке.','Stage tolerances, current justification and product acceptance readiness.'],
 cpm:['Планировщик поддерживает сеть; владельцы работ подтверждают длительности и реальные зависимости.','Scheduler maintains the network; work owners validate durations and actual dependencies.','Длина критического пути, полный резерв и изменение прогнозной даты.','Critical-path length, total float and forecast finish-date movement.'],
 'critical-chain':['Владельцы ресурсов подтверждают доступность; координатор защищает буферы и порядок выполнения.','Resource owners confirm availability; coordination protects buffers and execution order.','Доля расходования буфера относительно выполненной цепи.','Buffer consumption relative to completed chain progress.'],
 'stage-gate':['Владельцы инвестиций принимают go/hold/stop; команда представляет доказательства готовности.','Investment owners decide go/hold/stop; the team supplies readiness evidence.','Достаточность доказательств и остающийся инвестиционный риск.','Evidence sufficiency and remaining investment risk.'],
 'lean-startup':['Владелец гипотезы задаёт критерий; команда проводит эксперимент; пользователи дают поведенческие данные.','Hypothesis owner sets the criterion; the team runs the experiment; users supply behavioral evidence.','Проверенное допущение, удержание или конверсия целевого поведения, стоимость проверки.','Validated assumption, retention or target-behavior conversion, experiment cost.'],
 'design-thinking':['Исследователь наблюдает; фасилитатор уточняет проблему; дизайнер и пользователь проверяют прототип.','Research observes; facilitation clarifies the problem; designer and user test the prototype.','Успешность пользовательской задачи и число неподтверждённых допущений решения.','User-task success and remaining untested solution assumptions.'],
 scaling:['Владельцы продуктов и команд согласуют общий результат; интеграционные владельцы разрешают связи.','Product and team owners align shared outcomes; integration owners resolve dependencies.','Сквозное время поставки, интеграционные дефекты и возраст межкомандных блокеров.','End-to-end lead time, integration defects and cross-team blocker age.'],
};
export function methodPractice(method:Method):Method {
 const p=practices[method.slug], detail=operatingDetails[method.slug];
 return {...method, combinations:methodCombinations[method.slug], roles:bi(detail[0],detail[1]),metrics:bi(detail[2],detail[3]),strengths:method.flow,poorFit:method.limitations,tailoring:bi(`Настройте этот механизм под свой проект: ${p[4].toLowerCase()}. Не теряйте принцип: ${p[0].toLowerCase()}.`,`Tailor this mechanism to the project: ${p[5].toLowerCase()}. Preserve the principle: ${p[1].toLowerCase()}.`),origin:bi(p[0],p[1]),principles:[bi(p[0],p[1])],artifacts:bi(p[2],p[3]),cadence:bi(p[4],p[5]),antiPatterns:bi(p[6],p[7]),
 prerequisites:bi(`Проверьте допущение: ${p[0].toLowerCase()}.`,`Check the assumption: ${p[1].toLowerCase()}.`),
 checklist:[bi(p[0],p[1]),bi(p[2],p[3]),bi(p[4],p[5])],
 };
}
