import type { Context } from '@/domain/method-fit';
import type { Locale } from '@/domain/schemas';
type Question = {ru:[string,string,string,string,string];en:[string,string,string,string,string]};
export const contextQuestions: Record<keyof Context,Question> = {
 uncertainty:{ru:['Насколько понятен способ достижения результата?','Решение уже проверено','Часть решения нужно проверить','Сначала нужны эксперименты','При высокой неопределённости планируйте проверки гипотез до крупных обязательств.'],en:['How well do you understand the solution?','Proven solution','Some validation needed','Experiments needed first','High uncertainty calls for hypothesis testing before major commitments.']},
 volatility:{ru:['Как часто меняются требования?','Почти никогда','Несколько раз за проект','Каждую неделю','При частых изменениях сокращайте горизонт детального планирования.'],en:['How often do requirements change?','Almost never','Several times per project','Every week','Frequent changes call for a shorter detailed planning horizon.']},
 feedback:{ru:['Как часто получатель может проверить результат?','Только в конце','Раз в месяц','Еженедельно или чаще','Доступность обратной связи определяет полезную длину цикла проверки.'],en:['How often can recipients review the result?','Only at the end','Monthly','Weekly or more often','Feedback availability determines a useful review-cycle length.']},
 frequency:{ru:['Как часто нужна отдельная поставка результата?','Один раз в конце','По этапам','Еженедельно или чаще','Частые поставки требуют небольших партий и регулярной проверки качества.'],en:['How often is a usable delivery needed?','Once at the end','At stage boundaries','Weekly or more often','Frequent delivery needs small batches and recurring quality checks.']},
 compliance:{ru:['Насколько строгие внешние требования?','Внутренние договорённости','Нужна формальная приёмка','Аудит и обязательное подтверждение','Строгие требования увеличивают потребность в документированных решениях и доказательствах.'],en:['How strict are external requirements?','Internal agreements','Formal acceptance needed','Audit and mandatory evidence','Strict requirements increase the need for documented decisions and evidence.']},
 dependencies:{ru:['Насколько работа зависит от других команд?','Команда работает самостоятельно','Несколько внешних передач','Много связанных команд и поставщиков','При плотных зависимостях нужны владельцы передач и общий обзор дат.'],en:['How dependent is work on other teams?','Self-contained team','Several external handoffs','Many teams and vendors','Dense dependencies need handoff owners and a shared date review.']},
 autonomy:{ru:['Какие решения команда принимает самостоятельно?','Почти всё согласует','Выбирает способ выполнения','Управляет работой в согласованных границах','Чем меньше полномочий, тем важнее доступность принимающего решения.'],en:['Which decisions can the team make independently?','Almost everything needs approval','Chooses execution tactics','Manages work within agreed boundaries','Limited authority increases the importance of available decision makers.']},
 scopeRigidity:{ru:['Можно ли менять состав результата?','Можно менять по обратной связи','Можно менять часть','Состав зафиксирован договором','Фиксированные границы требуют явного согласования изменений.'],en:['Can the scope change?','Can adapt to feedback','Some parts can change','Contractually fixed','Fixed scope requires explicit change approval.']},
 deadlineRigidity:{ru:['Насколько можно сдвинуть дату?','Дата ориентировочная','Небольшой сдвиг допустим','Сдвиг недопустим','Жёсткая дата требует раннего выбора между объёмом, ресурсами и риском.'],en:['How flexible is the deadline?','Indicative date','Small delay is acceptable','Cannot move','A fixed deadline requires early scope, resource and risk trade-offs.']},
 stakeholders:{ru:['Насколько сложно согласовать интересы участников?','Один доступный заказчик','Несколько согласующих','Много сторон с конфликтующими интересами','Сложное согласование требует владельцев решений и регулярной коммуникации.'],en:['How hard is stakeholder alignment?','One available customer','Several approvers','Many conflicting interests','Complex alignment needs decision owners and recurring communication.']},
};
export const defaultContext:Context={uncertainty:3,volatility:3,feedback:3,frequency:3,compliance:3,dependencies:3,autonomy:3,scopeRigidity:3,deadlineRigidity:3,stakeholders:3};
export function contextText(key:keyof Context,locale:Locale){return contextQuestions[key][locale];}
