import type {Locale,Workspace} from '@/domain/schemas';
export const starterPacks = [
 {id:'digital',type:'software',ru:['Цифровой продукт','Проверить ключевой пользовательский сценарий и выпустить рабочую версию','Приёмка основного сценария; отсутствие блокирующих дефектов','Проверка потребности; прототип; первая версия; приёмка','Пользователь, владелец продукта, разработчик, QA','Неясная потребность; интеграции; потеря данных','Еженедельная демонстрация; проверка рисков перед релизом','Устав; бэклог; критерии приёмки; журнал решений','Подбор подхода; CPM; уверенность в сроке'],en:['Digital product','Validate the core user journey and release a working version','Core journey accepted; no blocking defects','Need validation; prototype; first version; acceptance','User, product owner, developer, QA','Unclear need; integrations; data loss','Weekly demonstration; risk review before release','Charter; backlog; acceptance criteria; decision log','Approach fit; CPM; deadline confidence']},
 {id:'education',type:'education',ru:['Образовательный продукт','Провести пилотную программу и проверить освоение навыка','Занятия проведены; задания проверены; обратная связь собрана','Программа; материалы; набор группы; пилот; разбор','Методист, преподаватель, куратор, участник','Готовность материалов; расписание; поддержка участников','Готовность занятия еженедельно; разбор после пилота','Бриф; план вех; коммуникации; извлечённые уроки','Матрица выбора; мощность; риски'],en:['Educational product','Run a pilot curriculum and assess skill acquisition','Sessions delivered; exercises reviewed; feedback collected','Curriculum; materials; enrollment; pilot; review','Instructional designer, instructor, coordinator, learner','Material readiness; schedule; learner support','Weekly lesson-readiness review; post-pilot review','Brief; milestones; communication plan; lessons learned','Decision matrix; capacity; risks']},
 {id:'content',type:'marketing',ru:['Контент и личный бренд','Подготовить и опубликовать согласованную серию материалов','Материалы приняты редактором и опубликованы','Темы; сценарии; производство; проверка; публикация','Автор, редактор, монтажёр, продюсер','Доступность автора; права на материалы; переделки','Редакционный обзор раз в неделю; контроль перед публикацией','Бриф; доска работ; критерии готовности; статус','Мощность и WIP; приоритизация; матрица выбора'],en:['Content and personal brand','Prepare and publish an agreed content series','Editor accepts materials and publication is recorded','Topics; scripts; production; review; publication','Author, editor, video editor, producer','Author availability; asset rights; rework','Weekly editorial review; pre-publication check','Brief; work board; definition of done; status','Capacity & WIP; prioritization; decision matrix']},
 {id:'operations',type:'operations',ru:['Запуск операционного бизнеса','Проверить выполнение заказа от заявки до передачи клиенту','Пилотные заказы выполнены; затраты и проблемы записаны','Процесс; поставщики; пробный заказ; запуск; стабилизация','Операционный менеджер, закупщик, исполнитель, клиент','Срыв поставки; качество; превышение затрат','Ежедневный контроль пилота; недельный обзор экономики','План; бюджет; риски; поставщики; передача','Денежный риск; мощность; сценарий изменения'],en:['Operational business launch','Validate order fulfillment from request to customer handoff','Pilot orders fulfilled; costs and issues recorded','Process; suppliers; trial order; launch; stabilization','Operations manager, buyer, operator, customer','Supply delay; quality; cost overrun','Daily pilot review; weekly cost review','Plan; budget; risks; vendors; handover','Monetary risk; capacity; change scenario']},
 {id:'hardening',type:'software',ru:['Стабилизация и релиз ПО','Устранить блокирующие дефекты и выпустить проверенную сборку','Критические тесты пройдены; миграция и восстановление проверены','Baseline; исправления; регрессия; release candidate; выпуск','Разработчик, QA, ответственный за релиз, владелец данных','Регрессия; несовместимость миграции; откат','Ежедневный разбор блокеров; контроль кандидата на выпуск','Журнал проблем; quality gate; план релиза; передача','CPM; ответственность; уверенность в сроке'],en:['Software production hardening','Resolve blocking defects and ship a verified build','Critical tests pass; migration and recovery verified','Baseline; repairs; regression; release candidate; publication','Developer, QA, release owner, data owner','Regression; migration incompatibility; rollback','Daily blocker review; release-candidate gate','Issue log; quality gate; release plan; handover','CPM; ownership; deadline confidence']},
] as const;
export function starterText(id:string,locale:Locale){return starterPacks.find(p=>p.id===id)?.[locale]}
export const starterSections=['milestones','work','risks','assumptions','decisions','stakeholders','documents'] as const;
export type StarterSection=typeof starterSections[number];
const pieces=(value:string)=>value.split(';').map(x=>x.trim()).filter(Boolean);
export function applyStarterPackBundle(workspace:Workspace,packId:string,projectId:string,locale:Locale,selected:StarterSection[],at:string):Workspace{
 const pack=starterPacks.find(item=>item.id===packId),project=workspace.projects.find(item=>item.id===projectId);if(!pack||!project)return workspace;
 const copy=pack[locale],ids=(kind:string,index:number)=>`${projectId}-PACK-${kind}-${index+1}`,milestoneTitles=pieces(copy[3]),workTitles=milestoneTitles.map(title=>locale==='ru'?`Подготовить: ${title}`:`Prepare: ${title}`),riskTitles=pieces(copy[5]),roles=pieces(copy[4]),include=(name:StarterSection)=>selected.includes(name);
 const due=(index:number)=>{const date=new Date(`${project.targetDate||project.startDate}T00:00:00Z`);date.setUTCDate(date.getUTCDate()-Math.max(0,(milestoneTitles.length-index-1)*14));return date.toISOString().slice(0,10)};
 return {...workspace,
  projects:workspace.projects.map(item=>item.id===projectId?{...item,purpose:item.purpose||copy[1],definitionOfDone:item.definitionOfDone||copy[2],successMeasures:item.successMeasures.length?item.successMeasures:[copy[2]]}:item),
  milestones:include('milestones')?[...workspace.milestones,...milestoneTitles.map((title,index)=>({id:ids('M',index),projectId,title,date:due(index),owner:'',baselineDate:due(index),forecastDate:due(index),confidence:undefined,status:'planned' as const,progress:0,createdAt:at,updatedAt:at,history:[]}))]:workspace.milestones,
  workItems:include('work')?[...workspace.workItems,...workTitles.map((title,index)=>({id:ids('WI',index),projectId,title,description:locale==='ru'?'Адаптируйте объём, владельца и критерии приёмки перед началом.':'Adapt scope, ownership, and acceptance criteria before starting.',type:'deliverable' as const,status:index===0?'ready' as const:'backlog' as const,priority:index===0?'high' as const:'medium' as const,owner:'',contributors:[],labels:['starter-pack',pack.id],dueDate:due(index),milestoneId:include('milestones')?ids('M',index):undefined,dependencies:[],acceptanceCriteria:[copy[2]],done:false,blocked:false,riskIds:[],objectiveIds:[],order:workspace.workItems.length+index,createdAt:at,updatedAt:at,archived:false,estimateHistory:[]}))]:workspace.workItems,
  risks:include('risks')?[...workspace.risks,...riskTitles.map((title,index)=>({id:ids('R',index),projectId,title,category:locale==='ru'?'Стартовый риск':'Starter risk',description:locale==='ru'?'Уточните вероятность, влияние, триггер и денежный слой при наличии данных.':'Refine probability, impact, trigger, and the monetary layer when evidence exists.',probability:3,impact:3,owner:'',strategy:'mitigate' as const,actions:'',trigger:'',reviewDate:project.startDate,residualProbability:undefined,residualImpact:undefined,status:'open' as const}))]:workspace.risks,
  assumptions:include('assumptions')?[...workspace.assumptions,{id:ids('A',0),projectId,text:locale==='ru'?'Ключевой результат достижим выбранным способом':'The target outcome is achievable through the selected approach',rationale:locale==='ru'?'Стартовое допущение требует проверки до крупного обязательства.':'A starter assumption to validate before a major commitment.',owner:'',validationMethod:copy[2],validationDate:due(0),status:'untested',effectIfFalse:locale==='ru'?'Пересмотреть подход, объём и срок.':'Revisit approach, scope, and date.'}]:workspace.assumptions,
  decisions:include('decisions')?[...workspace.decisions,{id:ids('D',0),projectId,question:locale==='ru'?'Какой минимальный объём подтверждает результат?':'What minimum scope validates the outcome?',context:copy[1],alternatives:[],criteria:[copy[2]],decision:'',rationale:'',owner:project.owner,date:project.startDate,participants:[],consequences:locale==='ru'?'Определяет первый проверяемый выпуск.':'Defines the first testable release.',revisitTrigger:locale==='ru'?'Новые доказательства или изменение ограничения.':'New evidence or a changed constraint.',status:'pending'}]:workspace.decisions,
  stakeholders:include('stakeholders')?[...workspace.stakeholders,...roles.map((role,index)=>({id:ids('S',index),projectId,name:`${locale==='ru'?'Роль':'Role'}: ${role}`,role,influence:3,interest:3,attitude:'neutral' as const,expectations:'',communicationNeeds:copy[6],owner:'',strategy:''}))]:workspace.stakeholders,
  documents:include('documents')?[...workspace.documents,{id:ids('DOC',0),projectId,title:locale==='ru'?'Стартовый рабочий договор проекта':'Starter project operating agreement',type:'operating-agreement',body:`## ${locale==='ru'?'Результат':'Outcome'}\n${copy[1]}\n\n## Definition of Done\n${copy[2]}\n\n## ${locale==='ru'?'Ритм обзора':'Review cadence'}\n${copy[6]}\n\n## ${locale==='ru'?'Рекомендуемые документы':'Recommended documents'}\n${copy[7]}\n\n## ${locale==='ru'?'Инструменты':'Tools'}\n${copy[8]}`,relatedIds:[...(include('milestones')?milestoneTitles.map((_,i)=>ids('M',i)):[]),...(include('decisions')?[ids('D',0)]:[])],updatedAt:at}]:workspace.documents,
 };
}
