import type {Locale} from '@/domain/schemas';
export const starterPacks = [
 {id:'digital',type:'software',ru:['Цифровой продукт','Проверить ключевой пользовательский сценарий и выпустить рабочую версию','Приёмка основного сценария; отсутствие блокирующих дефектов','Проверка потребности; прототип; первая версия; приёмка','Пользователь, владелец продукта, разработчик, QA','Неясная потребность; интеграции; потеря данных','Еженедельная демонстрация; проверка рисков перед релизом','Устав; бэклог; критерии приёмки; журнал решений','Подбор подхода; CPM; уверенность в сроке'],en:['Digital product','Validate the core user journey and release a working version','Core journey accepted; no blocking defects','Need validation; prototype; first version; acceptance','User, product owner, developer, QA','Unclear need; integrations; data loss','Weekly demonstration; risk review before release','Charter; backlog; acceptance criteria; decision log','Approach fit; CPM; deadline confidence']},
 {id:'education',type:'education',ru:['Образовательный продукт','Провести пилотную программу и проверить освоение навыка','Занятия проведены; задания проверены; обратная связь собрана','Программа; материалы; набор группы; пилот; разбор','Методист, преподаватель, куратор, участник','Готовность материалов; расписание; поддержка участников','Готовность занятия еженедельно; разбор после пилота','Бриф; план вех; коммуникации; извлечённые уроки','Матрица выбора; мощность; риски'],en:['Educational product','Run a pilot curriculum and assess skill acquisition','Sessions delivered; exercises reviewed; feedback collected','Curriculum; materials; enrollment; pilot; review','Instructional designer, instructor, coordinator, learner','Material readiness; schedule; learner support','Weekly lesson-readiness review; post-pilot review','Brief; milestones; communication plan; lessons learned','Decision matrix; capacity; risks']},
 {id:'content',type:'marketing',ru:['Контент и личный бренд','Подготовить и опубликовать согласованную серию материалов','Материалы приняты редактором и опубликованы','Темы; сценарии; производство; проверка; публикация','Автор, редактор, монтажёр, продюсер','Доступность автора; права на материалы; переделки','Редакционный обзор раз в неделю; контроль перед публикацией','Бриф; доска работ; критерии готовности; статус','Мощность и WIP; приоритизация; матрица выбора'],en:['Content and personal brand','Prepare and publish an agreed content series','Editor accepts materials and publication is recorded','Topics; scripts; production; review; publication','Author, editor, video editor, producer','Author availability; asset rights; rework','Weekly editorial review; pre-publication check','Brief; work board; definition of done; status','Capacity & WIP; prioritization; decision matrix']},
 {id:'operations',type:'operations',ru:['Запуск операционного бизнеса','Проверить выполнение заказа от заявки до передачи клиенту','Пилотные заказы выполнены; затраты и проблемы записаны','Процесс; поставщики; пробный заказ; запуск; стабилизация','Операционный менеджер, закупщик, исполнитель, клиент','Срыв поставки; качество; превышение затрат','Ежедневный контроль пилота; недельный обзор экономики','План; бюджет; риски; поставщики; передача','Денежный риск; мощность; сценарий изменения'],en:['Operational business launch','Validate order fulfillment from request to customer handoff','Pilot orders fulfilled; costs and issues recorded','Process; suppliers; trial order; launch; stabilization','Operations manager, buyer, operator, customer','Supply delay; quality; cost overrun','Daily pilot review; weekly cost review','Plan; budget; risks; vendors; handover','Monetary risk; capacity; change scenario']},
 {id:'hardening',type:'software',ru:['Стабилизация и релиз ПО','Устранить блокирующие дефекты и выпустить проверенную сборку','Критические тесты пройдены; миграция и восстановление проверены','Baseline; исправления; регрессия; release candidate; выпуск','Разработчик, QA, ответственный за релиз, владелец данных','Регрессия; несовместимость миграции; откат','Ежедневный разбор блокеров; контроль кандидата на выпуск','Журнал проблем; quality gate; план релиза; передача','CPM; ответственность; уверенность в сроке'],en:['Software production hardening','Resolve blocking defects and ship a verified build','Critical tests pass; migration and recovery verified','Baseline; repairs; regression; release candidate; publication','Developer, QA, release owner, data owner','Regression; migration incompatibility; rollback','Daily blocker review; release-candidate gate','Issue log; quality gate; release plan; handover','CPM; ownership; deadline confidence']},
] as const;
export function starterText(id:string,locale:Locale){return starterPacks.find(p=>p.id===id)?.[locale]}
