export const templateBoundaries:Record<string,[string,string]>={
 'project-charter':['Не создавайте новый устав для каждой работы внутри уже согласованного проекта.','Do not create a new charter for every task inside an agreed project.'],
 'business-case-lite':['Для крупного необратимого вложения нужна более подробная проверка вариантов.','A large irreversible investment needs a fuller assessment of options.'],
 'business-case':['Для небольшого обратимого эксперимента подробное обоснование может стоить дороже самого шага.','For a small reversible experiment, a full case may cost more than the step itself.'],
 'project-brief':['Не заменяет согласование полномочий, бюджета и обязательств по поставке.','Does not replace agreement on authority, budget and delivery commitments.'],
 'project-plan':['Не фиксируйте дальние детали, пока ключевые допущения не проверены.','Avoid fixing distant details while key assumptions remain untested.'],
 'scope-statement':['Не нужен отдельный документ, если границы уже однозначно записаны в уставе.','A separate document is unnecessary when the charter already states clear boundaries.'],
 wbs:['Для пары независимых действий достаточно списка работ.','A work list is enough for a couple of independent actions.'],
 'requirements-register':['Не заводите вторую копию требований, если основной реестр уже поддерживается командой.','Do not create a second requirements copy when the team maintains an authoritative register.'],
 'backlog-item':['Не используйте запись работы вместо журнала долгосрочных идей без решения об исполнении.','Do not treat an uncommitted long-term idea as executable work.'],
 'user-story':['Для технической операции без пользовательского сценария подходит обычная задача.','A regular task fits a technical operation without a user journey.'],
 'acceptance-criteria':['Не подменяйте критериями подробную инструкцию реализации, если способ решения ещё открыт.','Do not turn criteria into implementation instructions when the solution is still open.'],
 'definition-ready':['Не вводите отдельный барьер, если команда уже получает достаточные входы без задержек.','Do not add a separate gate when sufficient inputs already arrive without delay.'],
 'definition-done':['Не заменяет специфичные критерии приёмки отдельного результата.','Does not replace acceptance criteria specific to an individual output.'],
 'milestone-plan':['Для ежедневного распределения мелких задач используйте Work.','Use Work for daily allocation of small tasks.'],
 roadmap:['Не используйте дальний ориентир как договорное обязательство по точной дате.','Do not use a distant intention as a contractual commitment to an exact date.'],
 'release-plan':['Для внутреннего изменения без отдельной поставки достаточно записи работы и проверки.','A work record and check suffice for an internal change without a separate release.'],
 'sprint-goal':['В потоке без Sprint используйте цель проекта или ближайшей поставки.','In a flow without Sprints, use the project or next-delivery outcome.'],
 'risk-register':['Для уже произошедшего события создайте проблему с планом восстановления.','For an event that has happened, create an issue with a recovery plan.'],
 'raid-log':['Не копируйте сюда параллельно поддерживаемые реестры; используйте ссылки на них.','Link to existing maintained registers rather than copying them here.'],
 'issue-log':['Для возможного будущего события используйте запись риска.','Use a risk record for a possible future event.'],
 'assumption-log':['Подтверждённый факт со стабильным источником не требует отдельного допущения.','A confirmed fact with a stable source does not need an assumption entry.'],
 'dependency-log':['Не связывайте работы только потому, что их выполняет один человек.','Do not link tasks merely because the same person performs them.'],
 'decision-log':['Обычное действие без выбора вариантов достаточно записать как работу.','Record a routine action without an option choice as work.'],
 'stakeholder-register':['Не собирайте персональные сведения, которые не нужны для взаимодействия по проекту.','Do not collect personal information unnecessary for project engagement.'],
 'stakeholder-matrix':['Для двух участников с ясными ролями достаточно прямой договорённости о взаимодействии.','For two participants with clear roles, a direct engagement agreement is enough.'],
 raci:['Не стройте матрицу для одиночной задачи с уже подтверждённым владельцем.','Do not build a matrix for a single task with an accepted owner.'],
 'communication-plan':['Для разового сообщения достаточно цели, получателя и нужного действия.','For a one-off message, purpose, recipient and required action are enough.'],
 'meeting-agenda':['Если требуется только прочитать статус, отправьте документ без встречи.','If only status reading is needed, send a document without a meeting.'],
 'meeting-minutes':['Не записывайте полный разговор, если нужны только решения и действия.','Do not transcribe the whole conversation when decisions and actions are sufficient.'],
 kickoff:['Не повторяйте запуск для каждого небольшого изменения внутри согласованной работы.','Do not repeat kickoff for every small change inside agreed work.'],
 'status-report':['При аварии нужен прямой сигнал и действие, а не ожидание очередного отчёта.','An emergency needs a direct signal and action rather than waiting for a report.'],
 'steering-pack':['Вопрос в пределах полномочий PM не требует отдельного пакета для спонсора.','A question within PM authority does not need a separate sponsor pack.'],
 'change-request':['Уточнение без изменения обязательств можно обработать в обычном рабочем обсуждении.','A clarification that changes no commitment can be handled in routine work discussion.'],
 'change-log':['Для единственного изменения достаточно его запроса с зафиксированным решением.','For one change, its request and recorded decision are sufficient.'],
 'quality-plan':['Не дублируйте обязательную систему качества организации; ссылайтесь на применимые проверки.','Reference applicable organizational quality checks instead of duplicating them.'],
 'acceptance-checklist':['Не используйте отметки вместо испытания результата в нужных условиях.','Do not substitute checkmarks for testing the output under required conditions.'],
 'capacity-plan':['Без сопоставимых единиц нагрузки и доступности числовое сравнение не имеет смысла.','A numerical comparison is meaningless without comparable demand and availability units.'],
 'resource-plan':['Не превращайте план ресурсов проекта в кадровое досье участника.','Do not turn a project resource plan into a personnel dossier.'],
 'budget-tracker':['Не заменяет бухгалтерский учёт и утверждённые финансовые процедуры организации.','Does not replace accounting or approved organizational financial procedures.'],
 'vendor-evaluation':['При обязательном единственном поставщике оцените риски договора вместо фиктивного конкурса.','For a mandatory sole supplier, assess contract risks instead of staging a false competition.'],
 'procurement-tracker':['Для немедленной мелкой покупки достаточно записи расхода.','An expense record suffices for an immediate minor purchase.'],
 retrospective:['Не откладывайте срочное устранение проблемы до ретроспективы.','Do not postpone urgent containment until the retrospective.'],
 'lessons-learned':['Совет без наблюдавшегося события лучше оставить гипотезой для проверки.','Keep advice without an observed event as a hypothesis to test.'],
 postmortem:['Для обычной рабочей ошибки без существенных последствий достаточно короткого разбора.','A brief review is enough for an ordinary mistake without material consequences.'],
 handover:['Не оформляйте передачу, пока получатель не определён и не может принять ответственность.','Do not finalize handover before a recipient is identified and can accept responsibility.'],
 'closure-report':['Не объявляйте завершение, пока решение об остановке или приёмке не принято.','Do not declare closure before acceptance or termination is authorized.'],
 'closure-checklist':['Не закрывайте оставшиеся обязательства только ради пустого списка.','Do not mark remaining commitments closed merely to empty the list.'],
};
