import type { Locale } from "@/domain/schemas";
const translations = {
  ru: {
    nav: {
      workspace: "Рабочее пространство",
      methods: "Методы",
      playbooks: "Практические сценарии",
      templates: "Шаблоны",
      tools: "Инструменты",
      knowledge: "Знания",
      glossary: "Глоссарий",
      about: "О проекте",
    },
    hero: {
      eyebrow: "Система управления проектами, программами, поставкой и операциями",
      title: "Понимайте, что происходит. Решайте, что делать дальше.",
      lead: "Ведите работу, принимайте решения, управляйте сроками, рисками и результатами. Выводы объяснимы, данные хранятся на вашем устройстве.",
      open: "Открыть рабочее пространство",
      choose: "Подобрать подход",
    },
    workspace: {
      overview: "Обзор",
      work: "Работа",
      board: "Доска",
      raid: "RAID",
      stakeholders: "Заинтересованные стороны",
      finance: "Финансы",
      documents: "Документы",
      setup: "Настройка",
      attention: "Что требует внимания",
      health: "Состояние проекта",
      milestones: "Ближайшие контрольные точки",
      active: "Активная работа",
      add: "Добавить",
      export: "Экспорт",
      import: "Импорт",
      search: "Поиск",
      saved: "Сохранено на устройстве",
      demo: "Демо",
      filter: "Фильтр",
      newItem: "Новая задача",
      newRisk: "Новый риск",
      newDecision: "Новое решение",
      delete: "Удалить",
      cancel: "Отмена",
      save: "Сохранить",
      empty: "Здесь пока нет данных",
      explain: "Почему это важно",
    },
  },
  en: {
    nav: {
      workspace: "Workspace",
      methods: "Methods",
      playbooks: "Playbooks",
      templates: "Templates",
      tools: "Tools",
      knowledge: "Knowledge",
      glossary: "Glossary",
      about: "About",
    },
    hero: {
      eyebrow: "Project, Program, Delivery & Operations Management",
      title: "Understand what is happening. Decide what to do next.",
      lead: "Manage work, make decisions, control schedule and risk, and learn from project evidence. No account or server required; data stays on your device.",
      open: "Open workspace",
      choose: "Choose an approach",
    },
    workspace: {
      overview: "Overview",
      work: "Work",
      board: "Board",
      raid: "RAID",
      stakeholders: "Stakeholders",
      finance: "Finance",
      documents: "Documents",
      setup: "Setup",
      attention: "What needs attention",
      health: "Project health",
      milestones: "Upcoming milestones",
      active: "Active work",
      add: "Add",
      export: "Export",
      import: "Import",
      search: "Search",
      saved: "Saved on this device",
      demo: "Demo",
      filter: "Filter",
      newItem: "New work item",
      newRisk: "New risk",
      newDecision: "New decision",
      delete: "Delete",
      cancel: "Cancel",
      save: "Save",
      empty: "No data here yet",
      explain: "Why it matters",
    },
  },
} as const;
export type UI = typeof translations.ru;
export const ui = (locale: Locale) => translations[locale] as UI;
export const locales = ["ru", "en"] as const;
