"use client";
import {useMemo,useState} from "react";
import {BookOpen,Copy,ExternalLink,FileDown,Search,Wrench} from "lucide-react";
import type {Locale} from "@/domain/schemas";
import {glossary,knowledgeDomains,methods,pick,playbooks,sources,templates} from "@/content/catalog";

type Kind="methods"|"templates"|"playbooks"|"knowledge"|"glossary";
export function CatalogPage({kind,locale}:{kind:Kind;locale:Locale}){const [query,setQuery]=useState("");const ru=locale==="ru";const meta={methods:[ru?"Библиотека методов":"Methods library",ru?"Выбирайте подход по контексту, а не по моде.":"Choose an approach by context, not fashion."],templates:[ru?"Рабочие шаблоны":"Practical templates",ru?"Готовые поля, guidance и anti-patterns — не пустые документы.":"Real fields, guidance, and anti-patterns—not empty documents."],playbooks:["PM playbooks",ru?"Проблема → диагностика → действие → стабилизация.":"Problem → diagnosis → action → stabilization."],knowledge:[ru?"База знаний":"Knowledge base",ru?"Коротко настолько, насколько возможно; полно настолько, насколько нужно.":"As concise as possible; as complete as necessary."],glossary:[ru?"Профессиональный глоссарий":"Professional glossary",ru?"Естественные RU/EN термины с практическим примером.":"Natural RU/EN terminology with a practical example."]}[kind];
 const data=useMemo(()=>{const q=query.toLowerCase();if(kind==="methods")return methods.filter(x=>(pick(x.title,locale)+pick(x.summary,locale)).toLowerCase().includes(q));if(kind==="templates")return templates.filter(x=>(pick(x.title,locale)+pick(x.purpose,locale)).toLowerCase().includes(q));if(kind==="playbooks")return playbooks.filter(x=>pick(x.title,locale).toLowerCase().includes(q));if(kind==="knowledge")return knowledgeDomains.filter(x=>pick(x,locale).toLowerCase().includes(q));return glossary.filter(x=>(x.term+x.ru+pick(x.definition,locale)).toLowerCase().includes(q));},[kind,locale,query]);
 return <><header className="catalog-hero"><p className="eyebrow">PMWORK · {kind}</p><h1>{meta[0]}</h1><p className="lead">{meta[1]}</p><div className="catalog-controls"><label className="field"><span className="sr-only">{ru?"Поиск":"Search"}</span><span className="search-input"><Search size={18}/><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder={ru?"Найти по названию или смыслу…":"Search by title or meaning…"}/></span></label><span className="pill">{data.length} {ru?"материалов":"items"}</span></div></header><section className="catalog-grid" aria-live="polite">
 {kind==="methods"&&(data as typeof methods).map(x=><details className="catalog-card" key={x.slug}><summary><span className="pill">{x.version}</span><h2>{pick(x.title,locale)}</h2><p>{pick(x.summary,locale)}</p></summary><h3>{ru?"Как течёт работа":"How work flows"}</h3><p>{pick(x.flow,locale)}</p><h3>{ru?"Лучший контекст":"Best fit"}</h3><p>{pick(x.bestFit,locale)}</p><h3>{ru?"Ограничения":"Limitations"}</h3><p>{pick(x.limitations,locale)}</p><h3>Anti-patterns</h3><p>{pick(x.antiPatterns,locale)}</p><h3>Tailoring</h3><p>{pick(x.tailoring,locale)}</p><h3>{ru?"Чек-лист внедрения":"Implementation checklist"}</h3><ol>{x.checklist.map(y=><li key={pick(y,locale)}>{pick(y,locale)}</li>)}</ol><div className="card-foot"><small>{ru?"Проверено":"Reviewed"}: {x.updatedAt}</small><span>{x.sourceIds.map(id=><a key={id} href={sources.find(s=>s.id===id)?.url} target="_blank" rel="noreferrer"><ExternalLink size={15}/><span className="sr-only">{id}</span></a>)}</span></div></details>)}
 {kind==="templates"&&(data as typeof templates).map(x=><article className="catalog-card" key={x.slug}><span className="pill">{x.category}</span><h2>{pick(x.title,locale)}</h2><p>{pick(x.purpose,locale)}</p><details><summary>{ru?"Поля и guidance":"Fields and guidance"}</summary><ul>{x.fields.map(f=><li key={pick(f,locale)}>{pick(f,locale)}</li>)}</ul><p><strong>{ru?"Когда использовать":"When to use"}:</strong> {pick(x.when,locale)}</p><p><strong>Anti-pattern:</strong> {pick(x.antiPattern,locale)}</p></details><div className="card-foot"><button className="button small" onClick={()=>{navigator.clipboard.writeText(`# ${pick(x.title,locale)}\n\n${x.fields.map(f=>`## ${pick(f,locale)}\n`).join("\n")}`)}}><Copy size={15}/>{ru?"Копировать":"Copy"}</button><button className="button small" onClick={()=>download(`${x.slug}.md`,`# ${pick(x.title,locale)}\n\n${x.fields.map(f=>`## ${pick(f,locale)}\n\n_${pick(x.guidance,locale)}_`).join("\n\n")}`)}><FileDown size={15}/>Markdown</button></div></article>)}
 {kind==="playbooks"&&(data as typeof playbooks).map(x=><article className="catalog-card" key={x.slug}><span className="pill">Diagnose → Act → Stabilize</span><h2>{pick(x.title,locale)}</h2><p><strong>{ru?"Диагностика":"Diagnose"}:</strong> {pick(x.diagnose[0]!,locale)}</p><details><summary>{ru?"Открыть playbook":"Open playbook"}</summary><h3>{ru?"Сразу":"Immediate"}</h3><ol>{x.immediate.map(y=><li key={pick(y,locale)}>{pick(y,locale)}</li>)}</ol><h3>{ru?"Следующий цикл":"Next working cycle"}</h3><p>{pick(x.next[0]!,locale)}</p><h3>{ru?"Стабилизировать":"Stabilize"}</h3><p>{pick(x.stabilize[0]!,locale)}</p><h3>{ru?"Предотвратить":"Prevent recurrence"}</h3><p>{pick(x.prevent[0]!,locale)}</p><h3>{ru?"Метрики":"Metrics"}</h3><ul>{x.metrics.map(y=><li key={pick(y,locale)}>{pick(y,locale)}</li>)}</ul><h3>Anti-patterns</h3><ul>{x.antiPatterns.map(y=><li key={pick(y,locale)}>{pick(y,locale)}</li>)}</ul></details></article>)}
 {kind==="knowledge"&&(data as typeof knowledgeDomains).map((x,i)=><article className="catalog-card" key={pick(x,locale)}><BookOpen size={22}/><p className="eyebrow">{String(i+1).padStart(2,"0")}</p><h2>{pick(x,locale)}</h2><p>{ru?"Раздел связывает понятия, практические решения, применимость, ограничения и связанные инструменты PMWORK.":"This domain connects concepts, practical decisions, applicability, limitations, and related PMWORK tools."}</p><div className="card-foot"><span className="pill">Foundation → Advanced</span></div></article>)}
 {kind==="glossary"&&(data as typeof glossary).map(x=><article className="catalog-card" key={x.term}><span className="pill">{x.term}</span><h2>{x.ru}</h2><p>{pick(x.definition,locale)}</p><p><strong>{ru?"Пример":"Example"}:</strong> {pick(x.example,locale)}</p></article>)}
 {!data.length&&<div className="panel"><Wrench/><h2>{ru?"Ничего не найдено":"No matches"}</h2><p className="muted">{ru?"Измените запрос или очистите поиск.":"Change or clear the search query."}</p></div>}
 </section></>}
function download(name:string,body:string){const blob=new Blob([body],{type:"text/markdown"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
