"use client";
import dynamic from "next/dynamic";
import type {ReactNode} from "react";
import type {Locale,Workspace,Scope} from "@/domain/schemas";
import {managementRoles,roleLabels,type ManagementRole} from "@/domain/management-role";
import {contextProject} from "@/domain/work-scope";
import {useUrlChoice,useUrlValue} from "./use-url-state";
import {registerForCreate} from "./workspace-types";
import {Brand} from "./brand";
import {ThemeToggle} from "./theme-toggle";
const Center=dynamic(()=>import("./management-center").then(module=>module.ManagementCenter));
const Today=dynamic(()=>import("./today-across-work").then(module=>module.TodayAcrossWork));
const Palette=dynamic(()=>import("./command-menu").then(module=>module.CommandMenu));
export function ContextWorkspaceShell({workspace,locale,onChange,onExport,onRestore,onCreateProject,palette,onClosePalette,children}:{workspace:Workspace;locale:Locale;onChange:(workspace:Workspace)=>void;onExport:()=>void;onRestore:()=>void;onCreateProject:()=>void;palette:boolean;onClosePalette:()=>void;children?:ReactNode}) {
  const ru=locale==="ru",[view,setView]=useUrlChoice("view",["overview","program","operations","setup"],workspace.managementRole==="program"?"program":"operations"),[selected]=useUrlValue("context");
  const scopes:Scope[]=[...workspace.programs.map(row=>({kind:"program" as const,id:row.id})),...workspace.operations.map(row=>({kind:"operation" as const,id:row.id}))];
  const active=scopes.find(scope=>scope.id===selected)??scopes.find(scope=>scope.kind===(view==="program"?"program":"operation"))??scopes[0];
  const titles={overview:"Today",program:ru?"Программы":"Programs",operations:ru?"Операции":"Operations",setup:ru?"Настройки":"Settings"};
  return <main className={`workspace-content density-${workspace.density} experience-${workspace.experience}`}><Brand/><h1>{roleLabels[locale][workspace.managementRole]}</h1><div className="button-row"><ThemeToggle/><button className="button" onClick={onExport}>{ru?"Скачать резервную копию":"Download backup"}</button><button className="button" onClick={onRestore}>{ru?"Восстановить":"Restore"}</button></div>{!scopes.length&&(workspace.managementRole==="project"||workspace.managementRole==="delivery")&&<button className="button primary" onClick={onCreateProject}>{ru?"Создать проект":"Create project"}</button>}<nav className="tabs" aria-label={ru?"Рабочие разделы":"Working views"}>{Object.entries(titles).map(([key,title])=><button key={key} aria-pressed={view===key} onClick={()=>setView(key)}>{title}</button>)}</nav>
    {view==="overview"?<Today workspace={workspace} locale={locale} onProject={()=>undefined} onEdit={()=>undefined} onView={setView}/>:view==="setup"?<section className="panel"><h2>{titles.setup}</h2><label className="field"><span>{ru?"Основная роль":"Primary role"}</span><select aria-label={ru?"Основная роль":"Primary role"} value={workspace.managementRole} onChange={event=>onChange({...workspace,managementRole:event.target.value as ManagementRole})}>{managementRoles.map(role=><option key={role} value={role}>{roleLabels[locale][role]}</option>)}</select></label><label className="field"><span>{ru?"Опыт":"Experience"}</span><select aria-label={ru?"Опыт":"Experience"} value={workspace.experience} onChange={event=>onChange({...workspace,experience:event.target.value as Workspace["experience"]})}>{["foundation","practitioner","advanced"].map((value,index)=><option key={value} value={value}>{(ru?["Основы","Практик","Продвинутый"]:["Foundation","Practitioner","Advanced"])[index]}</option>)}</select></label><label className="field"><span>{ru?"Плотность":"Density"}</span><select aria-label={ru?"Плотность":"Density"} value={workspace.density} onChange={event=>onChange({...workspace,density:event.target.value as Workspace["density"]})}><option value="comfortable">{ru?"Комфортная":"Comfortable"}</option><option value="compact">{ru?"Компактная":"Compact"}</option></select></label><fieldset><legend>{ru?"Дополнительные роли":"Additional role lenses"}</legend>{managementRoles.filter(role=>role!==workspace.managementRole).map(role=><label className="checkbox" key={role}><input type="checkbox" checked={workspace.roleLenses.includes(role)} onChange={event=>onChange({...workspace,roleLenses:event.target.checked?[...workspace.roleLenses,role]:workspace.roleLenses.filter(value=>value!==role)})}/>{roleLabels[locale][role]}</label>)}</fieldset></section>:<Center workspace={workspace} locale={locale} kind={view} onChange={onChange}/>}
    <details className="panel"><summary>{ru?"Добавить временный проект":"Add a temporary project"}</summary><p>{ru?"Для постоянного процесса конечная дата не нужна. Проект используйте для отдельного ограниченного изменения.":"An ongoing process needs no end date. Use a project for a separate, bounded change."}</p><button className="button" onClick={onCreateProject}>{ru?"Создать проект":"Create project"}</button></details>
    {palette&&active&&<Palette workspace={workspace} project={contextProject(workspace,active)} locale={locale} onClose={onClosePalette} onProject={()=>undefined} onView={destination=>{if(destination in titles){setView(destination);return;}if(active){const url=new URL(window.location.href);url.searchParams.set("view",active.kind==="program"?"program":"operations");url.searchParams.set("context",active.id);url.searchParams.set("register",destination);history.pushState(null,"",url);dispatchEvent(new Event("pmwork-url"));}}} onEdit={()=>undefined} onCreate={type=>{const url=new URL(window.location.href);url.searchParams.set("view",active.kind==="program"?"program":"operations");url.searchParams.set("context",active.id);url.searchParams.set("create",type);url.searchParams.set("register",registerForCreate(type));history.pushState(null,"",url);dispatchEvent(new Event("pmwork-url"));}}/>}{children}
  </main>;
}
