"use client";
import type { ViewProps } from "./workspace-views";
import { flowMetrics } from "@/domain/insights";
import { localDay } from "@/domain/work-views";

export function DeliveryCenter({workspace,project,locale,onView,onEdit,onCreate}:ViewProps) {
  const ru=locale==="ru", items=workspace.workItems.filter(row=>row.projectId===project.id&&!row.archived);
  const flow=flowMetrics(items), milestones=workspace.milestones.filter(row=>row.projectId===project.id);
  const pending=workspace.decisions.filter(row=>row.projectId===project.id&&row.status==="pending");
  const quality=workspace.qualityGates.filter(row=>row.projectId===project.id);
  const unknown=ru?"Недостаточно данных":"Insufficient evidence";
  const value=(n:number|null)=>n===null?unknown:n.toFixed(1);
  const cycle=flow.cycleSampleSize>=10;
  return <div className="management-center"><section className="panel"><h3>{ru?"Обещание → прогноз → поток → поставка → приёмка → результат":"Commitment → forecast → flow → delivery → acceptance → outcome"}</h3><p>{project.objective}</p><p className="muted">{ru?"Наблюдаемые длительности не являются прогнозом даты поставки. Velocity не используется для сравнения команд.":"Observed durations are not a delivery date forecast. Velocity is not used to compare teams."}</p></section>
    <section className="panel"><h3>{ru?"Текущие обязательства":"Current commitments"}</h3><div className="table-scroll" tabIndex={0} role="region" aria-label={ru?"Таблица обязательств":"Commitments table"}><table><caption>{ru?"Базовый срок, прогноз и факт по контрольным точкам":"Milestone baseline / forecast / actual"}</caption><thead><tr>{[ru?"Результат":"Deliverable",ru?"Базовый срок":"Baseline",ru?"Прогноз":"Forecast",ru?"Факт":"Actual",ru?"Владелец":"Owner"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{milestones.map(row=><tr key={row.id}><td><button className="button small" onClick={()=>onEdit("milestone",row.id)}>{row.title}</button></td><td>{row.baselineDate||unknown}</td><td>{row.forecastDate||unknown}</td><td>{row.actualDate||unknown}</td><td>{row.owner||"—"}</td></tr>)}</tbody></table></div>{!milestones.length&&<p>{ru?"Нет записанных обязательств поставки.":"No delivery commitments recorded."}</p>}<button className="button" onClick={()=>onCreate("milestone")}>{ru?"Добавить обязательство":"Add commitment"}</button></section>
    <section className="panel"><h3>{ru?"Поток и качество данных":"Flow and evidence quality"}</h3><dl className="management-metrics"><dt>WIP</dt><dd>{flow.wip}</dd><dt>{ru?"Блокеры":"Blockers"}</dt><dd>{flow.blocked}</dd><dt>{ru?"Поставлено за 7 / 14 / 28 дней":"Completed in 7 / 14 / 28 days"}</dt><dd>{flow.completed7} / {flow.completed14} / {flow.completed28}</dd><dt>{ru?"Медиана lead time, дни":"Median lead time, days"}</dt><dd>{value(flow.medianLeadDays)}</dd><dt>{ru?"Cycle time P50 / P80 / P90, дни":"Cycle time P50 / P80 / P90, days"}</dt><dd>{cycle?`${value(flow.medianCycleDays)} / ${value(flow.p80CycleDays)} / ${value(flow.p90CycleDays)}`:unknown} · n={flow.cycleSampleSize}</dd><dt>{ru?"Возраст WIP: известен / неизвестен":"WIP age: known / unknown"}</dt><dd>{flow.agingWipKnown} / {flow.agingWipUnknown}</dd></dl><p className="muted">{ru?"Для перцентилей нужно минимум 10 завершённых записей с наблюдаемыми startedAt и completedAt. Это минимальный порог PMWORK, а не гарантия статистической точности. Заблокированное время и повторная работа неизвестны без отдельных наблюдений.":"Percentiles require at least 10 completed records with observed startedAt and completedAt. This PMWORK minimum is not a guarantee of statistical precision. Blocked duration and rework remain unknown without separate observations."}</p></section>
    <section className="panel"><h3>{ru?"Блокеры и стареющая работа":"Blockers and aging work"}</h3><ul className="clean-list">{items.filter(row=>!row.done&&(row.blocked||flow.agingWip.some(age=>age.id===row.id))).slice(0,20).map(row=><li key={row.id}><button className="button small" onClick={()=>onEdit("work",row.id)}>{row.title}</button><p>{row.blockerReason||"—"} · {row.owner||"—"} · {flow.agingWip.find(age=>age.id===row.id)?.ageDays.toFixed(1)??unknown} {ru?"дней":"days"}</p></li>)}</ul><button className="button" onClick={()=>onView("planning")}>{ru?"Проверить зависимости":"Review dependencies"}</button></section>
    <section className="panel"><h3>{ru?"Готовность и решения":"Readiness and decisions"}</h3><p>{ru?"Критерии приёмки отсутствуют":"Acceptance criteria missing"}: {items.filter(row=>row.status!=="backlog"&&!row.acceptanceCriteria.length).length}</p><p>{ru?"Контроль качества":"Quality controls"}: {quality.length||unknown}</p><p>{ru?"Нерешённые вопросы":"Pending decisions"}: {pending.length}</p>{pending.slice(0,10).map(row=><p key={row.id}><button className="button small" onClick={()=>onEdit("decision",row.id)}>{row.question}</button> · {row.owner||"—"}</p>)}</section>
    <section className="panel"><h3>{ru?"Обзор поставки":"Delivery Review"}</h3><p>{ru?"Что обещали и поставили? Что изменилось и почему? Какое узкое место повторяется? Какое решение нужно? Что улучшить в следующем цикле?":"What did we promise and deliver? What changed and why? Which bottleneck recurs? Which decision is needed? What should improve next cycle?"}</p><p>{ru?"На дату":"As of"}: {localDay()}</p><button className="button" onClick={()=>onCreate("document")}>{ru?"Записать обзор в документ":"Record review in a document"}</button></section>
  </div>;
}
