"use client";
import { useState } from "react";
import type { Locale, Workspace } from "@/domain/schemas";
import { programSchema, operationSchema, type Program, type Operation } from "@/domain/management-entities";
import { managementSignals } from "@/domain/management-signals";
import { localDay } from "@/domain/work-views";
import { ProgramPlan } from "./program-plan";
import { useUrlValue } from "./use-url-state";
import {recordOperationReview} from "@/domain/operation-review";
import {completeControl} from "@/domain/operational-control";
import {EvidenceHistory} from "./evidence-history";
import {CollectionPager} from "./collection-pager";
import {usePagedRecords} from "./use-paged-records";
import { ScopedRegisters } from "./scoped-registers";

const uid = () => crypto.randomUUID();
const text = (fd: FormData, key: string) => String(fd.get(key) ?? "").trim();
const number = (fd: FormData, key: string) => text(fd,key) === "" ? undefined : Number(text(fd,key));
function Field({name,label,type="text",value,required=false}:{name:string;label:string;type?:string;value?:string|number;required?:boolean}) {
  return <label className="field"><span>{label}</span><input name={name} type={type} defaultValue={value} required={required} minLength={required&&type==="text"?2:undefined} step={type==="number"?"any":undefined}/></label>;
}
export function ManagementCenter({workspace,locale,onChange,kind}:{workspace:Workspace;locale:Locale;onChange:(next:Workspace)=>void;kind:"program"|"operations"}) {
  const ru=locale==="ru", [selected,setSelected]=useUrlValue("context"),[error,setError]=useState("");
  const collection=kind==="program"?workspace.programs:workspace.operations;
  const record=collection.find(row=>row.id===selected)??collection[0];
  const program=kind==="program"?record as Program|undefined:undefined;
  const operation=kind==="operations"?record as Operation|undefined:undefined;
  const [sourceEvidence,clearEvidence]=useUrlValue("evidence");
  const clearFocus=()=>clearEvidence("");
  const benefitRows=usePagedRecords(program?.benefits??[],sourceEvidence,clearFocus,record?.id??"");
  const metricRows=usePagedRecords(operation?.metrics??[],sourceEvidence,clearFocus,record?.id??"");
  const controlRows=usePagedRecords(operation?.controls??[],sourceEvidence,clearFocus,record?.id??"");
  const incidentRows=usePagedRecords(operation?.incidents??[],sourceEvidence,clearFocus,record?.id??"");
  const reviewRows=usePagedRecords(operation?.reviews.toReversed()??[],sourceEvidence,clearFocus,record?.id??"");
  const save=(next:Program|Operation)=>{
    try {
      if(kind==="program") {const parsed=programSchema.parse(next);onChange({...workspace,programs:[...workspace.programs.filter(row=>row.id!==parsed.id),parsed]});}
      else {const parsed=operationSchema.parse(next);onChange({...workspace,operations:[...workspace.operations.filter(row=>row.id!==parsed.id),parsed]});}
      setSelected(next.id);setError("");
    } catch {setError(ru?"Проверьте обязательные поля и даты. Изменение не сохранено.":"Check required fields and dates. The change was not saved.");}
  };
  const history=(summary:string)=>[...(record?.history??[]),{at:new Date().toISOString(),summary}];
  const create=(fd:FormData)=>{
    try { save(kind==="program"?programSchema.parse({id:uid(),name:text(fd,"name"),outcome:text(fd,"purpose"),owner:text(fd,"owner")}):operationSchema.parse({id:uid(),name:text(fd,"name"),purpose:text(fd,"purpose"),owner:text(fd,"owner")})); }
    catch {setError(ru?"Название и результат должны содержать минимум два символа.":"Name and outcome must contain at least two characters.");}
  };
  const signals=managementSignals(workspace,locale,localDay()).filter(signal=>signal.source.id===record?.id);
  return <div className="management-center">
    <p className="muted">{kind==="program"?(ru?"Координируйте связанные проекты ради общего результата и измеримых выгод. Портфель остаётся отдельным уровнем выбора инициатив.":"Coordinate related projects for a shared outcome and measurable benefits. Portfolio remains a separate initiative selection layer."):(ru?"Управляйте постоянным процессом: наблюдайте, исправляйте, улучшайте и стандартизируйте. Конечная дата не требуется.":"Run an ongoing process: observe, correct, improve and standardize. No end date is required.")}</p>
    <details className="panel"><summary>{kind==="program"?(ru?"Создать программу":"Create program"):(ru?"Создать процесс / сервис":"Create process / service")}</summary><form className="form-grid" action={create}><Field name="name" label={ru?"Название":"Name"} required/><Field name="purpose" label={kind==="program"?(ru?"Общий результат":"Shared outcome"):(ru?"Назначение":"Purpose")} required/><Field name="owner" label={ru?"Владелец":"Owner"}/><button className="button primary" type="submit">{ru?"Создать":"Create"}</button></form></details>
    {error&&<p role="alert">{error}</p>}
    {!record?<section className="panel"><h3>{ru?"Пока нет записей":"No records yet"}</h3><p>{ru?"Создайте рабочий контур выше. Неизвестное состояние не считается стабильным.":"Create an operating context above. Unknown status is not treated as stable."}</p></section>:<>
      <label className="field"><span>{kind==="program"?(ru?"Выбрать программу":"Select program"):(ru?"Выбрать процесс":"Select operation")}</span><select value={record.id} onChange={e=>setSelected(e.target.value)}>{collection.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
      <section className="panel" id={`evidence-${record.id}-${record.id}`}><h3>{ru?"Ситуация и основания сигналов":"Situation and signal evidence"}</h3><p>{program?.outcome??operation?.purpose}</p>{program&&<ul>{program.strategicObjectives.map((objective,index)=><li key={index}>{objective}</li>)}</ul>}<p>{ru?"Владелец":"Owner"}: {record.owner||(ru?"не назначен":"unassigned")}</p>{signals.length?<ul className="clean-list">{signals.slice(0,5).map(signal=><li key={signal.id}><strong>{signal.group.toUpperCase()} · {signal.title}</strong><p>{signal.why}</p><p>{signal.action}</p><details><summary>{ru?"Основание сигнала":"Signal evidence"}</summary><p>{signal.rule}</p><p>{ru?"На дату":"As of"}: {signal.asOf} · {signal.confidence==="known"?(ru?"Подтверждено":"Known"):(ru?"Недостаточно данных":"Insufficient evidence")}</p><p>{ru?"Недостающие данные":"Missing evidence"}: {signal.missingEvidence.join(", ")||"—"}</p><p>{ru?"Источник":"Source"}: {signal.source.id} / {signal.source.recordId??"—"}</p>{signal.source.kind&&signal.source.recordId&&<button className="button small" onClick={()=>{const next=new URL(window.location.href);next.searchParams.set("item",signal.source.recordId!);next.searchParams.set("kind",signal.source.kind!);next.searchParams.set("register",signal.source.register??"raid");window.history.pushState(null,"",next);dispatchEvent(new Event("pmwork-url"));}}>{ru?"Открыть исходную запись":"Open source record"}</button>}</details></li>)}</ul>:<p>{ru?"Нет сигналов по текущим записям. Проверьте полноту и актуальность данных.":"No signals in current records. Review evidence completeness and freshness."}</p>}</section>
      <details className="panel"><summary>{ru?"Основные данные":"Core details"}</summary><form key={record.id} className="form-grid" action={fd=>save({...record,name:text(fd,"name"),owner:text(fd,"owner"),currency:text(fd,"currency").toUpperCase(),...(program?{outcome:text(fd,"purpose"),sponsor:text(fd,"sponsor"),status:text(fd,"programStatus") as Program["status"],governanceCadence:text(fd,"cadence"),strategicObjectives:text(fd,"strategic").split("\n").map(value=>value.trim()).filter(Boolean)}:{purpose:text(fd,"purpose"),customer:text(fd,"customer"),scope:text(fd,"scope"),inputs:text(fd,"inputs"),outputs:text(fd,"outputs")}),history:history("Core details updated")})}><Field name="name" label={ru?"Название":"Name"} value={record.name} required/><Field name="owner" label={ru?"Владелец":"Owner"} value={record.owner}/><Field name="currency" label={ru?"Валюта бюджета — код ISO":"Budget currency — ISO code"} value={record.currency??"USD"} required/><Field name="purpose" label={ru?"Результат / назначение":"Outcome / purpose"} value={program?.outcome??operation?.purpose} required/>{program?<><Field name="sponsor" label={ru?"Спонсор":"Sponsor"} value={program.sponsor}/><label className="field"><span>{ru?"Состояние программы":"Program status"}</span><select name="programStatus" defaultValue={program.status}>{["planned","active","on-hold","completed"].map((value,index)=><option key={value} value={value}>{(ru?["Запланирована","Активна","Приостановлена","Завершена"]:["Planned","Active","On hold","Completed"])[index]}</option>)}</select></label><Field name="cadence" label={ru?"Ритм управления":"Governance cadence"} value={program.governanceCadence}/><label className="field wide"><span>{ru?"Стратегические цели — по строке":"Strategic objectives — one per line"}</span><textarea name="strategic" defaultValue={program.strategicObjectives.join("\n")}/></label></>:<><Field name="customer" label={ru?"Заказчик":"Customer"} value={operation?.customer}/><Field name="scope" label={ru?"Границы процесса":"Process scope"} value={operation?.scope}/><Field name="inputs" label={ru?"Входы":"Inputs"} value={operation?.inputs}/><Field name="outputs" label={ru?"Выходы":"Outputs"} value={operation?.outputs}/></>}<button className="button" type="submit">{ru?"Сохранить":"Save"}</button></form></details>
      {program&&<>
        <ScopedRegisters workspace={workspace} scope={{kind:"program",id:program.id}} locale={locale} onChange={onChange}/>
        <ProgramPlan program={program} workspace={workspace} locale={locale} onSave={save}/>
        <section className="panel"><h3>{ru?"Компоненты программы":"Program components"}</h3><p className="muted">{ru?"Общие записи проектов используются без копирования.":"Project records are shared without duplication."}</p>{workspace.projects.map(project=><label className="checkbox" key={project.id}><input type="checkbox" checked={program.projectIds.includes(project.id)} disabled={program.projectIds.includes(project.id)&&(program.dependencies.some(d=>d.fromProjectId===project.id||d.toProjectId===project.id)||program.benefits.some(b=>b.projectIds.includes(project.id))||program.resourceConflicts.some(r=>r.projectIds.includes(project.id)))} onChange={e=>save({...program,projectIds:e.target.checked?[...program.projectIds,project.id]:program.projectIds.filter(id=>id!==project.id),history:history("Program components updated")})}/>{project.name}</label>)}</section>
        <section className="panel"><h3>{ru?"Выгоды":"Benefits"}</h3>{benefitRows.rows.map(benefit=><details key={benefit.id} open={sourceEvidence===benefit.id||undefined} id={`evidence-${program.id}-${benefit.id}`}><summary>{benefit.name} · {benefit.owner||(ru?"Нет владельца":"No owner")}</summary><form className="form-grid" action={fd=>save({...program,benefits:program.benefits.map(row=>row.id===benefit.id?{...row,owner:text(fd,"owner"),unit:text(fd,"unit"),baseline:number(fd,"baseline"),target:number(fd,"target"),actual:number(fd,"actual"),measuredAt:text(fd,"measuredAt")||undefined,measurementPlan:text(fd,"plan"),projectIds:fd.getAll("components").map(String),reviewDate:text(fd,"review")||undefined}:row),history:history(`Benefit reviewed: ${benefit.name}`)})}><Field name="owner" label={ru?"Владелец выгоды":"Benefit owner"} value={benefit.owner}/><Field name="unit" label={ru?"Единица":"Unit"} value={benefit.unit}/>{(["baseline","target","actual"] as const).map(key=><Field key={key} name={key} label={ru?({baseline:"Исходное значение",target:"Целевое значение",actual:"Фактическое значение"}[key]):key} type="number" value={benefit[key]}/>)}<Field name="measuredAt" label={ru?"Дата фактического наблюдения":"Actual observation date"} type="date" value={benefit.measuredAt}/><Field name="plan" label={ru?"Способ измерения":"Measurement plan"} value={benefit.measurementPlan}/><Field name="review" label={ru?"Дата обзора":"Review date"} type="date" value={benefit.reviewDate}/><fieldset className="wide"><legend>{ru?"Какие компоненты создают эту выгоду":"Which components create this benefit"}</legend>{program.projectIds.map(id=><label className="checkbox" key={id}><input type="checkbox" name="components" value={id} defaultChecked={benefit.projectIds.includes(id)}/>{workspace.projects.find(project=>project.id===id)?.name}</label>)}</fieldset><button className="button" type="submit">{ru?"Сохранить обзор":"Save review"}</button></form></details>)}<CollectionPager {...benefitRows} locale={locale} label={ru?"Страницы выгод":"Benefit pages"}/><form className="form-grid" action={fd=>save({...program,benefits:[...program.benefits,{id:uid(),name:text(fd,"name"),owner:text(fd,"owner"),unit:"",measurementPlan:"",projectIds:[]}],history:history("Benefit added")})}><Field name="name" label={ru?"Новая выгода":"New benefit"} required/><Field name="owner" label={ru?"Владелец":"Owner"}/><button className="button" type="submit">{ru?"Добавить выгоду":"Add benefit"}</button></form></section>
        <section className="panel"><h3>{ru?"Межпроектные зависимости":"Cross-project dependencies"}</h3><div className="table-scroll" tabIndex={0} role="region" aria-label={ru?"Таблица зависимостей":"Dependency table"}><table><caption>{ru?"Доступная карта зависимостей":"Accessible dependency map"}</caption><thead><tr>{[ru?"Из":"From",ru?"В":"To",ru?"Передача":"Handoff",ru?"Срок":"Due",ru?"Действие":"Action"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{program.dependencies.map(d=><tr key={d.id} id={`evidence-${program.id}-${d.id}`}><td>{workspace.projects.find(p=>p.id===d.fromProjectId)?.name}</td><td>{workspace.projects.find(p=>p.id===d.toProjectId)?.name}</td><td>{d.description} · {ru?({open:"Открыта",blocked:"Заблокирована",resolved:"Разрешена"}[d.status]):d.status}</td><td>{d.dueDate??"—"}</td><td><button className="button small" onClick={()=>save({...program,dependencies:program.dependencies.map(row=>row.id===d.id?{...row,status:row.status==="resolved"?"open":"resolved"}:row),history:history(`Dependency status updated: ${d.description}`)})}>{d.status==="resolved"?(ru?"Открыть снова":"Reopen"):(ru?"Разрешить":"Resolve")}</button></td></tr>)}</tbody></table></div>{program.projectIds.length>=2?<form className="form-grid" action={fd=>{if(text(fd,"from")===text(fd,"to")){setError(ru?"Выберите два разных компонента.":"Select two different components.");return;}save({...program,dependencies:[...program.dependencies,{id:uid(),fromProjectId:text(fd,"from"),toProjectId:text(fd,"to"),description:text(fd,"description"),owner:text(fd,"owner"),dueDate:text(fd,"due")||undefined,status:"open"}],history:history("Dependency added")})}}>{["from","to"].map(name=><label className="field" key={name}><span>{name==="from"?(ru?"Из проекта":"From project"):(ru?"В проект":"To project")}</span><select name={name}>{program.projectIds.map(id=><option value={id} key={id}>{workspace.projects.find(p=>p.id===id)?.name}</option>)}</select></label>)}<Field name="description" label={ru?"Передача":"Handoff"} required/><Field name="owner" label={ru?"Владелец":"Owner"}/><Field name="due" label={ru?"Срок":"Due"} type="date"/><button className="button" type="submit">{ru?"Добавить зависимость":"Add dependency"}</button></form>:<p>{ru?"Свяжите минимум два проекта, чтобы создать межпроектную зависимость.":"Link at least two projects to create a cross-project dependency."}</p>}</section>
      </>}
      {operation&&<>
        <ScopedRegisters workspace={workspace} scope={{kind:"operation",id:operation.id}} locale={locale} onChange={onChange}/>
        <details className="panel"><summary>{ru?"Спрос и мощность":"Demand and capacity"}</summary><p>{ru?"Используйте одинаковые единицы и период, например обращения за неделю.":"Use the same unit and period, for example requests per week."}</p><form className="form-grid" action={fd=>save({...operation,demand:number(fd,"demand"),capacity:number(fd,"capacity"),demandUnit:text(fd,"unit"),history:history("Capacity reviewed")})}><Field name="demand" label={ru?"Спрос":"Demand"} type="number" value={operation.demand}/><Field name="capacity" label={ru?"Мощность":"Capacity"} type="number" value={operation.capacity}/><Field name="unit" label={ru?"Единица и период":"Unit and period"} value={operation.demandUnit} required/><button className="button" type="submit">{ru?"Сохранить":"Save"}</button></form></details>
        <section className="panel"><h3>{ru?"Операционные метрики":"Operating metrics"}</h3>{metricRows.rows.map(metric=><details key={metric.id} open={sourceEvidence===metric.id||undefined} id={`evidence-${operation.id}-${metric.id}`}><summary>{metric.name} · {metric.direction==="at-least"?"≥":"≤"} {metric.target} {metric.unit}</summary><p>{metric.observations.length?(ru?"Наблюдения":"Observations"):(ru?"Недостаточно данных":"Insufficient evidence")}: {metric.observations.length}</p><EvidenceHistory entries={metric.observations.toSorted((a,b)=>b.at.localeCompare(a.at)).map(row=>({id:row.at,text:`${row.at}: ${row.value} ${metric.unit}`}))} locale={locale} label={ru?"Страницы наблюдений":"Observation pages"}/><form className="form-grid" action={fd=>save({...operation,metrics:operation.metrics.map(row=>row.id===metric.id?{...row,observations:[...row.observations.filter(ob=>ob.at!==text(fd,"at")),{at:text(fd,"at"),value:Number(text(fd,"value"))}]}:row),history:history(`Observation recorded: ${metric.name}`)})}><Field name="at" label={ru?"Дата наблюдения":"Observation date"} type="date" value={localDay()} required/><Field name="value" label={ru?"Значение":"Value"} type="number" required/><button className="button" type="submit">{ru?"Записать измерение":"Record observation"}</button></form></details>)}<CollectionPager {...metricRows} locale={locale} label={ru?"Страницы метрик":"Metric pages"}/><details><summary>{ru?"Добавить метрику":"Add metric"}</summary><form className="form-grid" action={fd=>save({...operation,metrics:[...operation.metrics,{id:uid(),name:text(fd,"name"),unit:text(fd,"unit"),target:Number(text(fd,"target")),direction:text(fd,"direction") as "at-least"|"at-most",owner:text(fd,"owner"),observations:[]}],history:history("Metric added")})}><Field name="name" label={ru?"Метрика":"Metric"} required/><Field name="unit" label={ru?"Единица":"Unit"} required/><Field name="target" label={ru?"Цель":"Target"} type="number" required/><label className="field"><span>{ru?"Граница":"Limit"}</span><select name="direction"><option value="at-least">{ru?"Не менее":"At least"}</option><option value="at-most">{ru?"Не более":"At most"}</option></select></label><Field name="owner" label={ru?"Владелец":"Owner"}/><button className="button" type="submit">{ru?"Добавить метрику":"Add metric"}</button></form></details></section>
        <section className="panel"><h3>{ru?"Обязательные проверки":"Required controls"}</h3><ul className="clean-list">{controlRows.rows.map(control=><li key={control.id} id={`evidence-${operation.id}-${control.id}`}>{control.name} · {control.dueDate} · {control.owner||"—"}<p>{control.runbook}</p>{control.completions.length>0&&<details><summary>{ru?"История выполнения":"Completion history"} ({control.completions.length})</summary><EvidenceHistory entries={control.completions.toReversed().map((entry,i)=>({id:`${entry.dueDate}-${i}`,text:`${entry.dueDate} → ${entry.completedAt}`}))} locale={locale} label={ru?"Страницы выполнения":"Completion pages"}/></details>}{control.completedAt?<span>{ru?"Выполнено":"Completed"}: {control.completedAt}</span>:<button className="button small" onClick={()=>save({...operation,controls:operation.controls.map(row=>row.id===control.id?completeControl(row,localDay()):row),history:history(`Control completed: ${control.name}`)})}>{ru?"Отметить выполнение":"Record completion"}</button>}</li>)}</ul><CollectionPager {...controlRows} locale={locale} label={ru?"Страницы проверок":"Control pages"}/><details><summary>{ru?"Добавить проверку":"Add control"}</summary><form className="form-grid" action={fd=>save({...operation,controls:[...operation.controls,{id:uid(),name:text(fd,"name"),owner:text(fd,"owner"),dueDate:text(fd,"due"),runbook:text(fd,"runbook"),recurrence:text(fd,"recurrence") as "once"|"daily"|"weekly"|"monthly",completions:[]}],history:history("Control added")})}><Field name="name" label={ru?"Проверка":"Control"} required/><Field name="owner" label={ru?"Владелец":"Owner"}/><Field name="due" label={ru?"Срок":"Due"} type="date" required/><Field name="runbook" label={ru?"Рабочая инструкция":"Runbook"}/><label className="field"><span>{ru?"Повторение":"Recurrence"}</span><select name="recurrence">{["once","daily","weekly","monthly"].map((value,index)=><option key={value} value={value}>{(ru?["Однократно","Ежедневно","Еженедельно","Ежемесячно"]:["Once","Daily","Weekly","Monthly"])[index]}</option>)}</select></label><button className="button" type="submit">{ru?"Добавить проверку":"Add control"}</button></form></details></section>
        <section className="panel"><h3>{ru?"Инциденты":"Incidents"}</h3><ul className="clean-list">{incidentRows.rows.map(incident=><li key={incident.id} id={`evidence-${operation.id}-${incident.id}`}>{incident.title} · {incident.owner||"—"}<p>{incident.correctiveAction}</p>{incident.resolvedAt?<span>{ru?"Разрешён":"Resolved"}: {incident.resolvedAt}</span>:<button className="button small" onClick={()=>save({...operation,incidents:operation.incidents.map(row=>row.id===incident.id?{...row,resolvedAt:localDay()}:row),history:history(`Incident resolved: ${incident.title}`)})}>{ru?"Записать разрешение":"Record resolution"}</button>}</li>)}</ul><CollectionPager {...incidentRows} locale={locale} label={ru?"Страницы инцидентов":"Incident pages"}/><details><summary>{ru?"Открыть инцидент":"Open incident"}</summary><form className="form-grid" action={fd=>save({...operation,incidents:[...operation.incidents,{id:uid(),title:text(fd,"title"),owner:text(fd,"owner"),openedAt:localDay(),recurring:fd.has("recurring"),correctiveAction:text(fd,"action")}],history:history("Incident opened")})}><Field name="title" label={ru?"Инцидент":"Incident"} required/><Field name="owner" label={ru?"Владелец":"Owner"}/><Field name="action" label={ru?"Корректирующее действие":"Corrective action"}/><label className="checkbox"><input type="checkbox" name="recurring"/>{ru?"Повторяющийся":"Recurring"}</label><button className="button" type="submit">{ru?"Открыть инцидент":"Open incident"}</button></form></details></section>
        <section className="panel"><h3>{ru?"Операционный обзор":"Operations review"}</h3><p>{ru?"Что отклонилось? Что повторяется? Какие решения нужны? Что стандартизировать?":"What deviated? What recurs? Which decisions are needed? What should be standardized?"}</p><details><summary>{ru?"Записать операционный обзор":"Record operations review"}</summary><form className="form-grid" action={fd=>{try{onChange(recordOperationReview(workspace,operation.id,{id:uid(),at:localDay(),cadence:text(fd,"cadence") as "daily"|"weekly"|"monthly",findings:text(fd,"findings"),decision:text(fd,"decision"),nextAction:text(fd,"action"),owner:text(fd,"owner")},new Date().toISOString(),locale));}catch{setError(ru?"Обзор не сохранён. Проверьте данные и связанные записи.":"Review was not saved. Check evidence and linked records.");}}}><label className="field"><span>{ru?"Ритм обзора":"Review cadence"}</span><select name="cadence"><option value="daily">{ru?"Ежедневный":"Daily"}</option><option value="weekly">{ru?"Еженедельный":"Weekly"}</option><option value="monthly">{ru?"Ежемесячный":"Monthly"}</option></select></label><Field name="findings" label={ru?"Выводы на основании данных":"Evidence-based findings"} required/><Field name="decision" label={ru?"Открытый вопрос для решения":"Open decision question"}/><Field name="action" label={ru?"Следующее действие":"Next action"}/><Field name="owner" label={ru?"Владелец действия":"Action owner"}/><button className="button" type="submit">{ru?"Сохранить обзор и связанные записи":"Save review and linked records"}</button></form></details><ul className="clean-list">{reviewRows.rows.map(review=><li id={`evidence-${operation.id}-${review.id}`} key={review.id}>{review.at} · {ru?({daily:"Ежедневный",weekly:"Еженедельный",monthly:"Ежемесячный"}[review.cadence]):review.cadence}<p>{review.findings}</p><p>{review.decision} · {review.nextAction} · {review.owner}</p>{[[review.workItemId,"work"],[review.decisionId,"decision"]].filter(([id])=>id).map(([id,kind])=><button className="button small" key={id} onClick={()=>{const url=new URL(window.location.href);url.searchParams.set("item",id!);url.searchParams.set("kind",kind!);url.searchParams.set("register",kind==="work"?"work":"raid");window.history.pushState(null,"",url);dispatchEvent(new Event("pmwork-url"));}}>{kind==="work"?(ru?"Открыть действие":"Open action"):(ru?"Открыть решение":"Open decision")}</button>)}</li>)}</ul><CollectionPager {...reviewRows} locale={locale} label={ru?"Страницы обзоров":"Review pages"}/></section>
      </>}
      <details className="panel"><summary>{ru?"История":"History"} ({record.history.length})</summary><ul className="clean-list">{record.history.slice(-20).reverse().map((entry,i)=><li key={`${entry.at}-${i}`}><time>{entry.at}</time> · {entry.summary}</li>)}</ul></details>
    </>}
  </div>;
}
