"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {Locale,Workspace} from '@/domain/schemas';
import {loadWorkspace,saveWorkspace} from '@/data/storage';
import {scoreMarkovmade,type MarkovmadeInput} from '@/domain/markovmade';

const initial:MarkovmadeInput={impact:8,frequency:7,evidence:6,riskReduction:7,strategicFit:8,effort:3,complexity:3,regressionRisk:3};
export function MarkovmadeTool({locale}:{locale:Locale}){
 const ru=locale==='ru',[workspace,setWorkspace]=useState<Workspace|null>(null),[projectId,setProjectId]=useState(''),[candidate,setCandidate]=useState(''),[constraint,setConstraint]=useState(''),[metric,setMetric]=useState(''),[notYet,setNotYet]=useState(''),[scores,setScores]=useState(initial),[result,setResult]=useState<ReturnType<typeof scoreMarkovmade>|null>(null),[message,setMessage]=useState(''),[affected,setAffected]=useState('');
 const project=workspace?.projects.find(p=>p.id===projectId);
 const labels:Record<keyof MarkovmadeInput,[string,string]>={impact:['Ожидаемое влияние','Expected impact'],frequency:['Частота / охват','Frequency / reach'],evidence:['Уверенность в доказательствах','Evidence confidence'],riskReduction:['Снижение риска','Risk reduction'],strategicFit:['Стратегическое соответствие','Strategic fit'],effort:['Усилия','Effort'],complexity:['Сложность','Complexity'],regressionRisk:['Риск регрессии / необратимости','Regression / reversibility risk']};
 async function load(){try{const w=await loadWorkspace();setWorkspace(w);setProjectId(w?.projects[0]?.id??'');setMessage(w?ru?'Локальные проекты загружены. Проверьте входы и допущения.':'Local projects loaded. Review inputs and assumptions.':ru?'Сначала создайте проект.':'Create a project first.');}catch{setMessage(ru?'Не удалось прочитать локальные данные.':'Could not read local data.')}}
 function calculate(){try{if(!candidate.trim()||!constraint.trim()||!metric.trim())throw Error();setResult(scoreMarkovmade(scores));setMessage('');setAffected('');}catch{setResult(null);setMessage(ru?'Заполните действие, ограничение и validation metric; оценки — 0–10, усилия > 0.':'Enter the action, constraint, and validation metric; scores must be 0–10 and effort > 0.')}}
 const summary=()=>result?`${ru?'Главное ограничение':'Main constraint'}: ${constraint}\n${ru?'Лучшее вмешательство':'Best intervention'}: ${candidate}\n${ru?'Почему':'Why'}: ${result.score}/100; ${ru?'выгода':'benefit'} ${result.benefit.toFixed(1)} / ${ru?'стоимость':'cost'} ${result.cost.toFixed(1)}\n${ru?'Пока не делать':'What NOT to do yet'}: ${notYet||'—'}\n${ru?'Метрика проверки':'Validation metric'}: ${metric}\n${ru?'Следующие 3 действия':'Next 3 actions'}: 1) ${ru?'зафиксировать baseline':'record baseline'}; 2) ${ru?'провести обратимый тест':'run a reversible test'}; 3) ${ru?'сравнить результат и решить':'compare evidence and decide'}`:'';
 async function persist(kind?:'decision'|'work'|'assumption') {if(!result||!project)return;try{const current=await loadWorkspace();if(!current?.projects.some(p=>p.id===projectId))throw Error();const at=new Date().toISOString(),runId=`RUN-${crypto.randomUUID()}`,recordId=kind?`${kind==='decision'?'D':kind==='work'?'WI':'A'}-${crypto.randomUUID()}`:'';let next:Workspace={...current,toolRuns:[...current.toolRuns,{id:runId,projectId,tool:'markovmade',createdAt:at,source:'MARKOVMADE Priority Tool',assumptions:[ru?'Оценки заданы пользователем по шкале 0–10.':'User-supplied 0–10 scores.',ru?'Score — эвристика, не вероятность успеха.':'The score is a heuristic, not a success probability.'],inputs:{candidate,constraint,metric,notYet,...scores},outputSummary:summary(),confidence:result.confidence,dataQuality:result.confidence==='low'?(ru?'Низкая уверенность в доказательствах':'Low evidence confidence'):(ru?'Проверено только внутреннее согласование шкал':'Only internal scale consistency checked'),appliedRecordIds:recordId?[recordId]:[]}]};if(kind==='decision')next={...next,decisions:[...next.decisions,{id:recordId,projectId,question:candidate,context:constraint,alternatives:[candidate,notYet].filter(Boolean),criteria:Object.values(labels).map(x=>x[ru?0:1]),decision:'',rationale:summary(),owner:project.owner,date:at.slice(0,10),participants:[],consequences:metric,revisitTrigger:metric,status:'pending'}]};if(kind==='work')next={...next,workItems:[...next.workItems,{id:recordId,projectId,title:candidate,description:summary(),type:'task',status:'ready',priority:result.score>=75?'high':'medium',owner:project.owner,contributors:[],labels:['MARKOVMADE'],estimate:scores.effort,originalEstimate:scores.effort,currentEstimate:scores.effort,estimateHistory:[{value:scores.effort,timestamp:at}],dependencies:[],acceptanceCriteria:[metric],done:false,blocked:false,riskIds:[],objectiveIds:[],order:next.workItems.length,createdAt:at,updatedAt:at,archived:false}]};if(kind==='assumption')next={...next,assumptions:[...next.assumptions,{id:recordId,projectId,text:candidate,rationale:constraint,owner:project.owner,validationMethod:metric,validationDate:'',status:'untested',effectIfFalse:notYet}]};await saveWorkspace(next,true);setMessage(kind?(ru?'Сценарий сохранён и запись создана.':'Scenario saved and record created.'):(ru?'Сценарий сохранён локально.':'Scenario saved locally.'));setAffected(recordId);}catch{setMessage(ru?'Не удалось сохранить. Расчёт остаётся на экране.':'Could not save. The calculation remains on screen.')}}
 return <div className="panel decision-tool"><p className="eyebrow">MARKOVMADE · {ru?'авторская методика, не отраслевой стандарт':'authorial framework, not an industry standard'}</p><h2>{ru?'Какое вмешательство даст лучший проверяемый результат?':'Which intervention offers the best testable outcome?'}</h2><div className="button-row"><button className="button" onClick={load}>{ru?'Выбрать локальный проект':'Choose local project'}</button>{workspace&&<label>{ru?'Проект':'Project'}<select value={projectId} onChange={e=>setProjectId(e.target.value)}>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}</div><div className="form-grid"><label className="field wide">{ru?'Главное ограничение':'Main constraint'}<textarea value={constraint} onChange={e=>setConstraint(e.target.value)}/></label><label className="field wide">{ru?'Кандидатное действие':'Candidate action'}<textarea value={candidate} onChange={e=>setCandidate(e.target.value)}/></label><label className="field">{ru?'Что пока не делать':'What not to do yet'}<input value={notYet} onChange={e=>setNotYet(e.target.value)}/></label><label className="field">{ru?'Validation metric':'Validation metric'}<input value={metric} onChange={e=>setMetric(e.target.value)}/></label>{(Object.keys(scores) as (keyof MarkovmadeInput)[]).map(key=><label className="field" key={key}>{labels[key][ru?0:1]}<input type="number" min="0" max="10" step="1" value={scores[key]} onChange={e=>{setScores({...scores,[key]:Number(e.target.value)});setResult(null)}}/></label>)}</div><button className="button primary" onClick={calculate}>{ru?'Рассчитать приоритет':'Calculate priority'}</button><p role="status">{message}</p>{result&&<div className="result-box"><strong>{result.score}/100</strong><p>{ru?'Уверенность':'Confidence'}: {result.confidence} · {ru?'чувствительность':'sensitivity'} {result.sensitivity.min}–{result.sensitivity.max}{result.sensitivity.unstable?` · ${ru?'решение нестабильно':'unstable recommendation'}`:''}</p><pre className="tool-output">{summary()}</pre><div className="button-row"><button className="button" onClick={()=>persist()}>{ru?'Сохранить сценарий':'Save scenario'}</button><button className="button" onClick={()=>persist('decision')}>{ru?'Создать решение':'Create Decision'}</button><button className="button" onClick={()=>persist('work')}>{ru?'Создать работу':'Create Work Item'}</button><button className="button" onClick={()=>persist('assumption')}>{ru?'Создать проверку допущения':'Create validation task'}</button></div></div>}{affected&&project&&<Link className="button" href={`/${locale}/workspace/?project=${projectId}&view=${affected.startsWith('D-')||affected.startsWith('A-')?'raid':'work'}&item=${affected}`}>{ru?'Открыть созданную запись':'Open affected record'}</Link>}</div>;
}
