"use client";
import { useState } from 'react';
import Link from 'next/link';
import type { Method } from '@/content/catalog';
import type { Locale } from '@/domain/schemas';
export function MethodCompare({methods,locale}:{methods:Method[];locale:Locale}) {
 const ru=locale==='ru';const [selected,setSelected]=useState<string[]>([]);
 const fields:[keyof Method,string,string][]=[['origin','Допущения','Assumptions'],['flow','Поставка и планирование','Delivery and planning'],['cadence','Обратная связь','Feedback cadence'],['artifacts','Артефакты управления','Governance artifacts'],['bestFit','Когда подходит','Best fit'],['poorFit','Когда не подходит','Poor fit'],['strengths','Сильные стороны','Strengths'],['limitations','Риски и ограничения','Risks and limitations']];
 return <section className="public-container"><h2>{ru?'Как вы хотите выбрать подход?':'How would you like to choose an approach?'}</h2><div className="button-row"><Link className="button primary" href={`/${locale}/tools/?tool=fit`}>{ru?'Подобрать по контексту':'Choose by context'}</Link><a className="button" href="#method-comparison">{ru?'Сравнить методы':'Compare methods'}</a><a className="button" href="#catalog-results">{ru?'Посмотреть все':'View all'}</a></div><details id="method-comparison"><summary>{ru?'Сравнение 2–3 подходов':'Compare 2–3 approaches'}</summary><div className="button-row">{methods.map(m=><label key={m.slug}><input type="checkbox" checked={selected.includes(m.slug)} disabled={!selected.includes(m.slug)&&selected.length===3} onChange={()=>setSelected(selected.includes(m.slug)?selected.filter(id=>id!==m.slug):[...selected,m.slug])}/>{m.title[locale]}</label>)}</div>{selected.length>=2&&<div className="table-wrap"><table><caption>{ru?'Контекстное сравнение PMWORK':'PMWORK context comparison'}</caption><thead><tr><th>{ru?'Критерий':'Criterion'}</th>{selected.map(id=><th key={id}>{methods.find(m=>m.slug===id)?.title[locale]}</th>)}</tr></thead><tbody>{fields.map(([key,r,e])=><tr key={key}><th>{ru?r:e}</th>{selected.map(id=><td key={id}>{(methods.find(m=>m.slug===id)![key] as {ru:string;en:string})[locale]}</td>)}</tr>)}</tbody></table></div>}</details></section>;
}
