"use client";
import { formatDate } from "@/domain/format-date";
import { useState } from "react";
import { dependencyConflicts } from "@/domain/planning";
import { localDay } from "@/domain/work-views";
import type { ViewProps } from "./workspace-views";
export function PlanningTimeline({workspace,project,locale,onEdit,onCreate}: Pick<ViewProps,"workspace"|"project"|"locale"|"onEdit"|"onCreate">) {
  const ru=locale==="ru", [zoom,setZoom]=useState("project"), [full,setFull]=useState(false);
  const items=workspace.workItems.filter(x=>x.projectId===project.id&&!x.archived);
  const scheduled=items.filter(x=>x.startDate||x.dueDate);
  const milestones=workspace.milestones.filter(x=>x.projectId===project.id);
  const conflicts=dependencyConflicts(workspace,project.id);
  const dates=[project.startDate,project.targetDate,...scheduled.flatMap(x=>[x.startDate,x.dueDate]),...milestones.flatMap(x=>[x.baselineDate,x.date,x.actualDate])].filter((x):x is string=>!!x).map(Date.parse).filter(Number.isFinite);
  const start=Math.min(...dates), end=Math.max(start+86400000,...dates), days=Math.ceil((end-start)/86400000)+1;
  const position=(value:string)=>Math.max(0,Math.min(100,(Date.parse(value)-start)/86400000/days*100));
  const today=localDay(), marker=position(today), width=zoom==="day"?Math.min(12000,days*44):zoom==="week"?Math.min(6000,days*14):920;
  return <section className="panel planning-panel">
    <div className="section-line"><label className="view-control">{ru?"Масштаб":"Scale"}<select className="input" value={zoom} onChange={e=>setZoom(e.target.value)}><option value="project">{ru?"Весь проект":"Project"}</option><option value="week">{ru?"Недели":"Weeks"}</option><option value="day">{ru?"Дни":"Days"}</option></select></label><button className="button" onClick={()=>onCreate("milestone")}>{ru?"Добавить контрольную точку":"Add milestone"}</button></div>
    {conflicts.length>0&&<div className="notice" role="status"><strong>{ru?"Конфликты зависимостей":"Dependency conflicts"} · {conflicts.length}</strong>{conflicts.map(c=><p key={c.id}><button className="work-title-button" onClick={()=>onEdit("dependency",c.id)}>{c.from} → {c.to} · {c.type}: {c.missing?(ru?"связанная работа недоступна":"linked work unavailable"):`${c.days} ${ru?"дн. нарушения связи":"days of timing conflict"}`}</button></p>)}</div>}
    <div className="mobile-planning-agenda"><h3>{ru ? "Ближайшая работа и контрольные точки" : "Upcoming work and milestones"}</h3>{[...scheduled.map(x=>({id:x.id,title:x.title,date:x.dueDate||x.startDate!,kind:"work" as const})),...milestones.map(x=>({id:x.id,title:x.title,date:x.date,kind:"milestone" as const}))].sort((a,b)=>a.date.localeCompare(b.date)).map(x=><button className="mobile-work-card" key={x.id} onClick={()=>onEdit(x.kind,x.id)}><small>{formatDate(x.date,locale)}</small><strong>{x.title}</strong></button>)}<button className="button" onClick={()=>setFull(!full)}>{full?(ru?"Скрыть timeline":"Hide timeline"):(ru?"Открыть полный timeline":"Open full timeline")}</button></div>
    {scheduled.length||milestones.length?<div className={`timeline-scroll ${full ? "mobile-expanded" : ""}`}><div className="date-timeline" style={{minWidth:width}}><div className="timeline-dates"><span>{formatDate(new Date(start).toISOString(),locale)}</span><span>{formatDate(new Date(end).toISOString(),locale)}</span></div>
      {scheduled.map(x=><div className="date-timeline-row" key={x.id}><button className="work-title-button" onClick={()=>onEdit("work",x.id)}><small>{x.id}</small> {x.title}<span className="timeline-date-label">{formatDate(x.startDate,locale)} → {formatDate(x.dueDate,locale)}</span></button><div className="date-track">{Date.parse(today)>=start&&Date.parse(today)<=end&&<span className="today-marker" style={{left:`${marker}%`}} title={ru?"Сегодня":"Today"}/>}<button className={`date-bar ${x.blocked||conflicts.some(c=>c.to===x.id)?"conflict":""}`} style={{left:`${position(x.startDate||x.dueDate!)}%`,width:`${Math.max(.6,position(x.dueDate||x.startDate!)-position(x.startDate||x.dueDate!)+100/days)}%`}} onClick={()=>onEdit("work",x.id)} aria-label={`${x.title}: ${x.startDate||"—"} → ${x.dueDate||"—"}`}>{x.blocked?(ru?"Блокер":"Blocked"):x.id}</button></div></div>)}
      {milestones.map(m=><div className="date-timeline-row" key={m.id}><button className="work-title-button" onClick={()=>onEdit("milestone",m.id)}>{m.title}<span className="timeline-date-label">{ru?'Обещано':'Baseline'}: {formatDate(m.baselineDate,locale)} · {ru?'Прогноз':'Forecast'}: {formatDate(m.date,locale)} · {ru?'Факт':'Actual'}: {formatDate(m.actualDate,locale)} · {m.progress}%</span></button><div className="date-track">{m.baselineDate&&<span className="baseline-marker" style={{left:`${position(m.baselineDate)}%`}} title={`${ru?'Обещано':'Baseline'}: ${m.baselineDate}`}>│</span>}{m.actualDate&&<span className="actual-marker" style={{left:`${position(m.actualDate)}%`}} title={`${ru?'Факт':'Actual'}: ${m.actualDate}`}>✓</span>}<button className="milestone-marker" style={{left:`${position(m.date)}%`}} aria-label={`${m.title} ${m.date}`} onClick={()=>onEdit("milestone",m.id)}>◆</button></div></div>)}
    </div></div>:<div className="empty-state"><h3>{ru?"Нет запланированной работы":"No scheduled work"}</h3><p>{ru?"Задайте начало и срок работы, чтобы увидеть её на шкале.":"Set work start and due dates to see it on the timeline."}</p><button className="button" onClick={()=>onCreate("work")}>{ru?"Добавить работу":"Add work"}</button></div>}
    <p className="muted compact">{ru?"Календарные дни. Связь FS допускает начало в день окончания предшественника; лаг добавляет дни. Вертикальная линия — сегодня. Работа без дат: ":"Calendar days. FS permits a same-day finish/start; lag adds days. Vertical line: today. Unscheduled work: "}{items.length-scheduled.length}.</p>
  </section>;
}
