"use client";
import {useState} from 'react';
import Link from 'next/link';
import {loadWorkspace,saveWorkspace} from '@/data/storage';
import type {Locale,Workspace} from '@/domain/schemas';
import type {Playbook} from '@/content/catalog';
import {WorkspaceMore} from './workspace-more';
export function PlaybookAction({playbook,locale}:{playbook:Playbook;locale:Locale}){
 const ru=locale==='ru',[workspace,setWorkspace]=useState<Workspace|null>(null),[open,setOpen]=useState(false),[project,setProject]=useState(''),[title,setTitle]=useState(playbook.title[locale]),[message,setMessage]=useState(''),[created,setCreated]=useState('');
 async function prepare(){try{const w=await loadWorkspace();setWorkspace(w);setProject(w?.projects[0]?.id??'');setOpen(true)}catch{setMessage(ru?'Не удалось прочитать проекты. Откройте рабочее пространство для восстановления.':'Could not read projects. Open the workspace to recover data.')}}
 async function apply(){try{const w=await loadWorkspace(),p=w?.projects.find(p=>p.id===project);if(!w||!p||title.trim().length<2)throw Error();const id=crypto.randomUUID();await saveWorkspace({...w,issues:[...w.issues,{id,projectId:project,title:title.trim(),description:playbook.diagnose[0][locale],impact:3,urgency:3,owner:p.owner,plan:playbook.next[0][locale],dueDate:'',escalation:'',relatedWorkIds:[],status:'open'}]});setCreated(id);setOpen(false);setMessage(ru?'Создана проблема. Уточните влияние, срочность и срок в записи.':'Issue created. Refine impact, urgency and due date in the record.')}catch{setMessage(ru?'Не удалось создать запись. Проверьте проект и название, затем повторите.':'Could not create record. Check the project and title, then retry.')}}
 return <><button className="button small" onClick={prepare}>{ru?'Применить к проблеме проекта':'Apply to a project issue'}</button>{message&&<p role="status">{message}</p>}{created&&<Link className="button small" href={`/${locale}/workspace/?project=${project}&view=raid&item=${created}`}>{ru?'Открыть проблему':'Open issue'}</Link>}{open&&<WorkspaceMore title={playbook.title[locale]} onClose={()=>setOpen(false)}>{workspace?.projects.length?<><label>{ru?'Проект':'Project'}<select aria-label={ru?'Проект':'Project'} value={project} onChange={e=>setProject(e.target.value)}>{workspace.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>{ru?'Название проблемы':'Issue title'}<input value={title} onChange={e=>setTitle(e.target.value)}/></label><p>{playbook.next[0][locale]}</p><p>{ru?'Создаётся отдельная запись со средними оценками 3/5 для уточнения. План не изменяется.':'Creates a separate record with midpoint 3/5 estimates for review. The project plan is unchanged.'}</p><button className="button primary" onClick={apply}>{ru?'Создать проблему':'Create issue'}</button></>:<Link href={`/${locale}/workspace/`}>{ru?'Сначала создайте проект':'Create a project first'}</Link>}</WorkspaceMore>}</>
}
