"use client";
import {useState} from 'react';
import Link from 'next/link';
import {loadWorkspace,saveWorkspace} from '@/data/storage';
import type {Locale,Workspace} from '@/domain/schemas';
import type {Playbook} from '@/content/catalog';
import {WorkspaceMore} from './workspace-more';
import {workspaceScopes,scopeKey,contextProject,contextWorkspace,applyContextWorkspace} from "@/domain/work-scope";
export function PlaybookAction({playbook,locale}:{playbook:Playbook;locale:Locale}){
 const ru=locale==='ru',[workspace,setWorkspace]=useState<Workspace|null>(null),[open,setOpen]=useState(false),[project,setProject]=useState(''),[title,setTitle]=useState(playbook.title[locale]),[message,setMessage]=useState(''),[created,setCreated]=useState('');
 async function prepare(){try{const w=await loadWorkspace();setWorkspace(w);setProject(w?scopeKey(workspaceScopes(w)[0]??{kind:'project',id:''}):'');setOpen(true)}catch{setMessage(ru?'Не удалось прочитать проекты. Откройте рабочее пространство для восстановления.':'Could not read projects. Open the workspace to recover data.')}}
 async function apply(){try{const w=await loadWorkspace(),scope=w&&workspaceScopes(w).find(scope=>scopeKey(scope)===project);if(!w||!scope||title.trim().length<2)throw Error();const p=contextProject(w,scope),adapted=contextWorkspace(w,scope);const id=crypto.randomUUID();await saveWorkspace(applyContextWorkspace(w,{...adapted,issues:[...w.issues,{id,projectId:project,title:title.trim(),description:playbook.diagnose[0][locale],impact:3,urgency:3,owner:p.owner,plan:playbook.next[0][locale],dueDate:'',escalation:'',relatedWorkIds:[],status:'open'}]},scope));setCreated(id);setOpen(false);setMessage(ru?'Создана проблема. Уточните влияние, срочность и срок в записи.':'Issue created. Refine impact, urgency and due date in the record.')}catch{setMessage(ru?'Не удалось создать запись. Проверьте контекст и название, затем повторите.':'Could not create record. Check the context and title, then retry.')}}
 return <><button className="button small" onClick={prepare}>{ru?'Применить к рабочей проблеме':'Apply to a work issue'}</button>{message&&<p role="status">{message}</p>}{created&&<Link className="button small" href={`/${locale}/workspace/?${new URLSearchParams({...project.startsWith("@program/")?{view:"program",context:project.slice(9),register:"raid"}:project.startsWith("@operation/")?{view:"operations",context:project.slice(11),register:"raid"}:{project,view:"raid"},item:created,kind:"issue"})}`}>{ru?'Открыть проблему':'Open issue'}</Link>}{open&&<WorkspaceMore title={playbook.title[locale]} onClose={()=>setOpen(false)}>{workspace&&workspaceScopes(workspace).length?<><label>{ru?'Рабочий контекст':'Working context'}<select aria-label={ru?'Рабочий контекст':'Working context'} value={project} onChange={e=>setProject(e.target.value)}>{workspaceScopes(workspace).map(scope=><option value={scopeKey(scope)} key={scopeKey(scope)}>{contextProject(workspace,scope).name}</option>)}</select></label><label>{ru?'Название проблемы':'Issue title'}<input value={title} onChange={e=>setTitle(e.target.value)}/></label><p>{playbook.next[0][locale]}</p><p>{ru?'Создаётся отдельная запись со средними оценками 3/5 для уточнения. План не изменяется.':'Creates a separate record with midpoint 3/5 estimates for review. The project plan is unchanged.'}</p><button className="button primary" onClick={apply}>{ru?'Создать проблему':'Create issue'}</button></>:<Link href={`/${locale}/workspace/`}>{ru?'Сначала создайте рабочий контекст':'Create a working context first'}</Link>}</WorkspaceMore>}</>
}
