"use client";
import type { Program } from "@/domain/management-entities";
import type { Locale, Workspace } from "@/domain/schemas";
import { projectFinancials } from "@/domain/finance";

export function ProgramPlan({program,workspace,locale,onSave}:{program:Program;workspace:Workspace;locale:Locale;onSave:(program:Program)=>void}) {
  const ru=locale==="ru", text=(fd:FormData,key:string)=>String(fd.get(key)??"").trim();
  const history=(summary:string)=>[...program.history,{at:new Date().toISOString(),summary}];
  const currencyGroups=new Map<string,ReturnType<typeof projectFinancials>[]>();
  for(const project of workspace.projects.filter(row=>program.projectIds.includes(row.id))) {
    const group=currencyGroups.get(project.currency)??[];group.push(projectFinancials(workspace,project.id));currencyGroups.set(project.currency,group);
  }
  const sum=(rows:ReturnType<typeof projectFinancials>[],key:"planned"|"forecast"|"actual")=>rows.some(row=>row[key]===null)?(ru?"Недостаточно данных":"Insufficient evidence"):rows.reduce((total,row)=>total+row[key]!,0).toLocaleString(locale);
  const dates=[...program.milestones].sort((a,b)=>(a.forecast??a.baseline??"9999").localeCompare(b.forecast??b.baseline??"9999")||a.id.localeCompare(b.id));
  return <>
    <section className="panel"><h3>{ru?"Дорожная карта программы":"Program roadmap"}</h3>{dates.length?<ol className="program-roadmap">{dates.map(row=><li key={row.id}><time>{row.forecast??row.baseline??"—"}</time><strong>{row.name}</strong><span>{row.owner||"—"}</span></li>)}</ol>:<p>{ru?"Нет контрольных точек. Следующий общий результат пока неизвестен.":"No milestones recorded. The next shared outcome is unknown."}</p>}<div className="table-scroll" tabIndex={0} role="region" aria-label={ru?"Таблица дорожной карты":"Roadmap table"}><table><caption>{ru?"Базовый срок, прогноз и факт":"Baseline, forecast and actual"}</caption><thead><tr>{[ru?"Контрольная точка":"Milestone",ru?"Базовый срок":"Baseline",ru?"Прогноз":"Forecast",ru?"Факт":"Actual"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{dates.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.baseline??"—"}</td><td>{row.forecast??"—"}</td><td>{row.actual??"—"}</td></tr>)}</tbody></table></div><details><summary>{ru?"Добавить контрольную точку":"Add milestone"}</summary><form className="form-grid" action={fd=>onSave({...program,milestones:[...program.milestones,{id:crypto.randomUUID(),name:text(fd,"name"),owner:text(fd,"owner"),baseline:text(fd,"baseline")||undefined,forecast:text(fd,"forecast")||undefined}],history:history(ru?"Добавлена контрольная точка программы":"Program milestone added")})}><label className="field"><span>{ru?"Название":"Name"}</span><input name="name" required minLength={2}/></label><label className="field"><span>{ru?"Владелец":"Owner"}</span><input name="owner"/></label><label className="field"><span>{ru?"Базовый срок":"Baseline date"}</span><input type="date" name="baseline"/></label><label className="field"><span>{ru?"Прогноз":"Forecast date"}</span><input type="date" name="forecast"/></label><button className="button" type="submit">{ru?"Добавить контрольную точку":"Add milestone"}</button></form></details></section>
    <section className="panel"><h3>{ru?"Общие ресурсы и конфликты":"Shared resources and conflicts"}</h3><ul className="clean-list">{program.resourceConflicts.map(row=><li key={row.id}><strong>{row.resource}</strong><p>{row.projectIds.map(id=>workspace.projects.find(p=>p.id===id)?.name).join(" · ")}</p>{row.resolution?<p>{row.resolution}</p>:<form className="form-grid" action={fd=>onSave({...program,resourceConflicts:program.resourceConflicts.map(conflict=>conflict.id===row.id?{...conflict,resolution:text(fd,"resolution")}:conflict),history:history(ru?"Разрешён конфликт ресурса":"Resource conflict resolved")})}><label className="field"><span>{ru?"Решение по ресурсу":"Resource decision"}</span><input name="resolution" required/></label><button className="button small" type="submit">{ru?"Сохранить решение":"Save decision"}</button></form>}</li>)}</ul><details><summary>{ru?"Зарегистрировать конфликт":"Register conflict"}</summary><form className="form-grid" action={fd=>onSave({...program,resourceConflicts:[...program.resourceConflicts,{id:crypto.randomUUID(),resource:text(fd,"resource"),projectIds:fd.getAll("projects").map(String),owner:text(fd,"owner"),resolution:""}],history:history(ru?"Зарегистрирован конфликт ресурса":"Resource conflict registered")})}><label className="field"><span>{ru?"Общий ресурс":"Shared resource"}</span><input name="resource" required/></label><label className="field"><span>{ru?"Владелец решения":"Decision owner"}</span><input name="owner"/></label><fieldset><legend>{ru?"Затронутые компоненты":"Affected components"}</legend>{program.projectIds.map(id=><label className="checkbox" key={id}><input name="projects" value={id} type="checkbox"/>{workspace.projects.find(p=>p.id===id)?.name}</label>)}</fieldset><button className="button" type="submit">{ru?"Добавить конфликт":"Add conflict"}</button></form></details></section>
    <section className="panel"><h3>{ru?"Финансы компонентов":"Component financial roll-up"}</h3><p className="muted">{ru?"Валюты показываются отдельно. Отсутствующий прогноз не заменяется фактическими затратами.":"Currencies stay separate. Missing forecasts are never replaced by actual costs."}</p>{[...currencyGroups].map(([currency,rows])=><p key={currency}>{currency} · {ru?"План":"Planned"}: {sum(rows,"planned")} · {ru?"Прогноз":"Forecast"}: {sum(rows,"forecast")} · {ru?"Факт":"Actual"}: {sum(rows,"actual")}</p>)}{!currencyGroups.size&&<p>{ru?"Нет связанных компонентов":"No linked components"}</p>}</section>
  </>;
}
