"use client";
import {useState} from 'react';
import {useDialogFocus} from './use-dialog-focus';
import {ContextFields} from './context-fields';
import {defaultContext} from '@/content/project-context';
import {starterPacks,starterText} from '@/content/starter-packs';
import {scoreApproaches,governanceLevel} from '@/domain/method-fit';
import {displayLabel} from '@/content/workspace-i18n';
import type {Locale} from '@/domain/schemas';
export function ProjectSetup({locale,onClose,onSubmit}:{locale:Locale;onClose:()=>void;onSubmit:(fd:FormData)=>void}){
 const ru=locale==='ru',ref=useDialogFocus(),[step,setStep]=useState(1),[context,setContext]=useState(defaultContext),[pack,setPack]=useState(''),[objective,setObjective]=useState('');const example=starterText(pack,locale),fit=scoreApproaches(context)[0];
 return <div className="dialog-backdrop"><section className="dialog" ref={ref} role="dialog" aria-modal="true" aria-label={ru?'Создать проект':'Create project'} tabIndex={-1}><div className="page-title"><h2>{ru?'Создать проект':'Create project'}</h2><button className="button" onClick={onClose}>{ru?'Закрыть':'Close'}</button></div><p role="status">{step}/3 · {step===1?(ru?'Основа проекта':'Project basics'):step===2?(ru?'Контекст':'Context'):(ru?'Рекомендуемая настройка':'Recommended setup')}</p><form action={onSubmit} onKeyDown={e=>{if(e.key==='Enter'&&step<3&&(e.target as HTMLElement).tagName!=='TEXTAREA')e.preventDefault()}}>
 <fieldset hidden={step!==1} className="setup-fields"><legend>{ru?'Какой результат нужен?':'What outcome is needed?'}</legend><div className="form-grid"><label className="field">{ru?'Название':'Title'}<input name="title" required minLength={2}/></label><label className="field">{ru?'Пример проекта (необязательно)':'Project example (optional)'}<select value={pack} onChange={e=>{setPack(e.target.value);const p=starterText(e.target.value,locale);if(p)setObjective(p[1])}}><option value="">{ru?'Свой проект':'Custom project'}</option>{starterPacks.map(p=><option key={p.id} value={p.id}>{p[locale][0]}</option>)}</select></label><input type="hidden" name="projectType" value={starterPacks.find(p=>p.id===pack)?.type??'general'}/><label className="field wide">{ru?'Измеримый результат':'Measurable outcome'}<textarea name="objective" value={objective} onChange={e=>setObjective(e.target.value)} required/></label><label className="field">{ru?'Целевая дата':'Target date'}<input name="dueDate" type="date"/></label><label className="field">{ru?'Владелец':'Owner'}<input name="owner"/></label><label className="field">{ru?'Спонсор (при необходимости)':'Sponsor (if relevant)'}<input name="sponsor"/></label></div>{example&&<details><summary>{ru?'Посмотреть пример: данные для адаптации':'Inspect example: adapt to your project'}</summary>{example.slice(2).map((line,i)=><p key={i}>{line}</p>)}</details>}</fieldset>
 <fieldset hidden={step!==2} className="setup-fields"><legend>{ru?'Ответы определят подход и частоту контроля':'Answers shape approach and review cadence'}</legend><p>{ru?'Можно оставить средние значения и уточнить позже.':'You can retain midpoint values and refine later.'}</p><ContextFields value={context} onChange={setContext} locale={locale}/></fieldset>
 <fieldset hidden={step!==3} className="setup-fields"><legend>{ru?'Рабочий профиль':'Operating profile'}</legend><h3>{displayLabel(locale,'approach',fit.approach)}</h3><p>{displayLabel(locale,'governance',governanceLevel(context).toLowerCase())} · {fit.score}/100</p><p>{ru?'Оценка отражает близость ответов к профилю подхода. Результат проекта зависит также от исполнения и ограничений.':'Score reflects proximity to an approach profile. Outcomes also depend on execution and constraints.'}</p><p>{context.volatility>=4?(ru?'Планируйте подробно на 1–2 недели: изменчивость ≥ 4.':'Plan in detail for 1–2 weeks: volatility ≥ 4.'):(ru?'Планируйте до следующей контрольной точки: изменчивость < 4.':'Plan to the next milestone: volatility < 4.')}</p><p>{ru?'Начните с результата, контрольной точки и ближайшей работы с владельцем. Подробные реестры поставщиков нужны при внешних поставках; EVM — при измеряемом освоенном объёме.':'Start with an outcome, milestone and next work item with an owner. Detailed vendor records are useful for external supply; EVM needs measurable earned value.'}</p><p>{ru?'Создание сохранит этот профиль. Демонстрационные записи не добавляются.':'Creation saves this profile. Example records are not added.'}</p></fieldset>
 <div className="button-row">{step>1&&<button type="button" className="button" onClick={()=>setStep(step-1)}>{ru?'Назад':'Back'}</button>}{step<3?<button type="button" className="button primary" onClick={e=>{e.preventDefault();const form=e.currentTarget.form!;if(step===1&&!Array.from(form.querySelectorAll('fieldset')[0].querySelectorAll('input,textarea')).every(el=>(el as HTMLInputElement).reportValidity()))return;setStep(step+1);ref.current?.scrollTo({top:0})}}>{step===2?(ru?'Показать рекомендации':'Show recommendations'):(ru?'Далее':'Next')}</button>:<button key="create-project" className="button primary" type="submit">{ru?'Создать':'Create'}</button>}</div></form></section></div>
}
