"use client";
import {useRef,useState} from 'react';
import {saveScenario} from '@/domain/tool-scenario';
import {loadWorkspace,saveWorkspace} from '@/data/storage';
import type {Locale,Workspace} from '@/domain/schemas';
export function ProjectDataSource({locale,onLoad,scenario}:{locale:Locale;onLoad:(w:Workspace,id:string)=>string;scenario?:{tool:string;result:string;inputs:Record<string,unknown>}}){
const saving=useRef(false),[savedKey,setSavedKey]=useState('');
const ru=locale==='ru',[workspace,setWorkspace]=useState<Workspace|null>(null),[project,setProject]=useState(''),[message,setMessage]=useState('');
const scenarioKey=JSON.stringify([project,scenario]);
async function save(){if(!scenario||saving.current||savedKey===scenarioKey)return;saving.current=true;try{const current=await loadWorkspace();const destination=current?.projects.find(p=>p.id===project);if(!current||!destination)throw Error();await saveWorkspace(saveScenario(current,project,scenario.tool,scenario.result,{...scenario.inputs,...(scenario.tool==='evm'?{currency:destination.currency}:{})},locale));setSavedKey(scenarioKey);setMessage(ru?'Сценарий сохранён в документах проекта.':'Scenario saved in project documents.')}catch{setMessage(ru?'Сценарий не сохранён. Расчёт остаётся на экране; проверьте локальное хранилище.':'Scenario was not saved. The calculation remains on screen; check local storage.')}finally{saving.current=false;}}
return <div className="project-data-source"><button className="button small" onClick={async()=>{try{const w=await loadWorkspace();setWorkspace(w);setProject(w?.projects[0]?.id??'');if(!w?.projects.length)setMessage(ru?'Создайте проект или вводите данные вручную.':'Create a project or enter values manually.')}catch{setMessage(ru?'Не удалось прочитать проекты. Откройте Workspace и проверьте данные.':'Could not read projects. Open Workspace and check data.')}}}>{ru?'Выбрать данные проекта':'Choose project data'}</button>{workspace?.projects.length?<><label>{ru?'Проект':'Project'}<select value={project} onChange={e=>setProject(e.target.value)}>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="button small" onClick={()=>{try{setMessage(onLoad(workspace,project))}catch{setMessage(ru?'Данных недостаточно или связи несовместимы. Проверьте даты, единицы и зависимости; доступен ручной ввод.':'Insufficient data or incompatible links. Check dates, units and dependencies; manual input is available.')}}}>{ru?'Использовать данные проекта':'Use project data'}</button>{scenario&&<button className="button small" disabled={savedKey===scenarioKey} onClick={save}>{ru?"Сохранить сценарий в проект":"Save scenario to project"}</button>}</>:null}{message&&<p role="status">{message}</p>}</div>
}
