"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {Locale,Workspace} from '@/domain/schemas';
import {loadWorkspace,saveWorkspace} from '@/data/storage';
import {capacityPlan,dailyHistory,deadlineConfidence,decisionMatrix,estimateCalibration,ownershipCoverage,riskEMV} from '@/domain/decision-tools';
export type ProjectTool='deadline'|'emv'|'capacity'|'matrix'|'ownership'|'change'|'calibration';
export function ProjectTools({locale,tool}:{locale:Locale;tool:ProjectTool}){
 const ru=locale==='ru',today=new Date().toISOString().slice(0,10);
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[projectId,setProjectId]=useState(''),[message,setMessage]=useState(''),[result,setResult]=useState('');
 const [samples,setSamples]=useState(''),[remaining,setRemaining]=useState(10),[target,setTarget]=useState('');
 const [probability,setProbability]=useState(25),[impact,setImpact]=useState(1000),[residualProbability,setResidualProbability]=useState(10),[residualImpact,setResidualImpact]=useState(500);
 const [riskRows,setRiskRows]=useState<{probability:number;impact:number;residualProbability:number;residualImpact:number}[]>([]);
 const weekDate=new Date(today+'T00:00:00Z');weekDate.setUTCDate(weekDate.getUTCDate()-(weekDate.getUTCDay()+6)%7);
 const [week,setWeek]=useState(weekDate.toISOString().slice(0,10));
 const [capacity,setCapacity]=useState(0),[planned,setPlanned]=useState(0),[wip,setWip]=useState(0),[throughput,setThroughput]=useState(0),[days,setDays]=useState(5);
 const [alternatives,setAlternatives]=useState(ru?'Внутренняя команда\nПодрядчик':'Internal team\nVendor'),[criteria,setCriteria]=useState(ru?'Стоимость\nСрок':'Cost\nTime'),[weights,setWeights]=useState('50,50'),[scores,setScores]=useState('8,5\n5,9');
 const [scope,setScope]=useState(''),[delay,setDelay]=useState(0),[cost,setCost]=useState(0),[hours,setHours]=useState(0),[dependency,setDependency]=useState(''),[quality,setQuality]=useState(''),[risk,setRisk]=useState('');
 const project=workspace?.projects.find(p=>p.id===projectId);
 async function load(){try{const w=await loadWorkspace();setWorkspace(w);setProjectId(w?.projects[0]?.id??'');setMessage(w?.projects.length?(ru?'Выберите проект и загрузите его значения.':'Choose a project and load its values.'):(ru?'Сначала создайте проект. Ручной ввод доступен.':'Create a project first. Manual input is available.'));}catch{setMessage(ru?'Не удалось прочитать данные. Откройте рабочее пространство и проверьте резервную копию.':'Could not read data. Open the workspace and check your backup.')}}
 function useData(){if(!workspace||!project)return;const items=workspace.workItems.filter(x=>x.projectId===projectId&&!x.archived);setRemaining(items.filter(x=>!x.done).length);setTarget(project.targetDate);const history=dailyHistory(workspace,projectId,today);setSamples(history?.join(',')??'');setWip(items.filter(x=>x.status==='in-progress'||x.status==='review').length);setCapacity(workspace.teamMembers.filter(x=>x.projectId===projectId).reduce((s,x)=>s+x.weeklyCapacity,0));setPlanned(workspace.capacityAllocations.filter(x=>x.projectId===projectId&&x.week===week).reduce((s,x)=>s+x.planned,0));setThroughput(history?history.reduce((a,b)=>a+b,0)/history.length:0);setMessage(ru?'Загружены доступные записи. Для истории нужны 28 полных дней и ≥ 10 завершений с датой; подтвердите, что все завершения занесены. Плановая нагрузка требует ручной проверки выбранной недели. Денежные оценки риска вводятся отдельно от шкалы 1–5.':'Available records loaded. History needs 28 full days and ≥ 10 dated completions; confirm all completions were recorded. Verify planned workload for the selected week manually. Monetary risk estimates are separate from the 1–5 scale.');setResult('')}
 const number=(label:string,value:number,change:(v:number)=>void,min=0)=><label className="field">{label}<input type="number" step="any" min={min} value={value} onChange={e=>{change(Number(e.target.value));setResult('')}}/></label>;
 const parse=(s:string)=>{if(!s.trim()||s.split(',').some(v=>!v.trim()))throw Error();return s.split(',').map(Number)};
 function calculate(){try{let text='';if(tool==='deadline'){const r=deadlineConfidence(parse(samples),remaining,today,target);text=`${ru?'Доля сценариев к целевой дате':'Scenario proportion by target'}: ${(r.proportion*100).toFixed(1)}%\np50: ${r.p50}\np80: ${r.p80}\np90: ${r.p90}\n${r.sampleSize} ${ru?'дней наблюдений':'observed days'} · ${r.iterations} ${ru?'симуляций':'simulations'}`;}if(tool==='emv'){const r=riskEMV(riskRows.length?riskRows:[{probability,impact,residualProbability,residualImpact}]);text=`EMV: ${r.total.toFixed(2)}\n${ru?'Остаточная экспозиция':'Residual exposure'}: ${r.residual.toFixed(2)}\n${ru?'Если риск произойдёт':'If the risk occurs'}: ${r.allOccur.toFixed(2)}\n${ru?'Сценарий резерва 1× / 1,5× остаточной EMV':'Reserve scenario 1× / 1.5× residual EMV'}: ${r.residual.toFixed(2)} / ${(r.residual*1.5).toFixed(2)}`;}if(tool==='capacity'){const r=capacityPlan(capacity,planned,wip,throughput,days);text=`${ru?'Перегрузка, ч/нед':'Overload, h/week'}: ${r.overload}\n${ru?'План / доступные часы':'Planned / available hours'}: ${r.utilization===null?'—':(r.utilization*100).toFixed(0)+'%'}\n${ru?'Время по закону Литтла, календарных дней':'Little’s Law time, calendar days'}: ${r.impliedDays?.toFixed(1)??'—'}\n${ru?'Ориентир WIP при целевом времени':'WIP reference at desired time'}: ${r.wipTarget?.toFixed(1)??'—'}`;}if(tool==='matrix'){const names=alternatives.split('\n').filter(Boolean),cs=criteria.split('\n').filter(Boolean),ws=parse(weights),ss=scores.split('\n').map(parse);if(names.length!==ss.length||cs.length!==ws.length)throw Error();const r=decisionMatrix(ws,ss);text=r.ranking.map(x=>`${names[x.index]}: ${x.score.toFixed(2)} / 10 (${x.contributions.map(c=>c.toFixed(2)).join(' + ')})`).join('\n')+'\n'+(r.close?(ru?'Близкие альтернативы: разница ≤ 0,5.':'Close alternatives: difference ≤ 0.5.'):'')+'\n'+r.sensitivity.map(s=>`${cs[s.criterion]} × ${s.factor}: ${names[s.winner]}`).join('\n');}if(tool==='change'){if(!scope.trim()||![delay,cost,hours].every(Number.isFinite))throw Error();text=`${scope}\n${ru?'Срок, дней':'Schedule, days'}: ${delay>=0?'+':''}${delay}\n${ru?'Бюджет':'Budget'}: ${cost>=0?'+':''}${cost} ${project?.currency??''}\n${ru?'Нагрузка, ч':'Workload, hours'}: ${hours>=0?'+':''}${hours}\n${ru?'Зависимости':'Dependencies'}: ${dependency}\n${ru?'Качество':'Quality'}: ${quality}\n${ru?'Риск':'Risk'}: ${risk}`;}setResult(text);setMessage('')}catch{setResult('');setMessage(ru?'Проверьте входные данные. Прогнозу нужны ≥ 14 полных дневных наблюдений с ненулевой суммой. В матрице число весов и оценок должно совпадать с критериями; оценки 0–10.':'Check inputs. Forecast needs ≥ 14 complete daily observations with positive total. Matrix weights and score columns must match criteria; scores are 0–10.')}}
 async function save(){if(!project||!result)return;try{const current=await loadWorkspace();if(!current?.projects.some(p=>p.id===projectId))throw Error();const id=crypto.randomUUID();if(tool==='matrix')await saveWorkspace({...current,decisions:[...current.decisions,{id,projectId,question:ru?'Сравнение вариантов':'Alternative comparison',context:result,alternatives:alternatives.split('\n'),criteria:criteria.split('\n'),decision:'',rationale:'',owner:project.owner,date:today,participants:[],consequences:'',revisitTrigger:ru?'Изменение критериев или весов':'Changed criteria or weights',status:'pending'}]});else await saveWorkspace({...current,changes:[...current.changes,{id,projectId,change:scope,requester:project.owner,reason:result,scopeImpact:scope,scheduleImpact:String(delay),costImpact:String(cost),riskImpact:risk,qualityImpact:quality,alternatives:ru?'Сохранить текущий план':'Keep current baseline',recommendation:'',decision:'',approver:project.sponsor,status:'assessing'}]});setMessage(ru?'Запись создана. Откройте проект для согласования.':'Record created. Open the project for approval.');setResult('')}catch{setMessage(ru?'Не удалось сохранить запись. Повторите попытку; расчёт остаётся на экране.':'Could not save the record. Retry; the calculation remains on screen.')}}
 const questions:Record<ProjectTool,string>={deadline:ru?'Успеем ли завершить оставшуюся работу к дате?':'Can remaining work finish by the target date?',emv:ru?'Какова ожидаемая денежная потеря от риска?':'What monetary loss is expected from a risk?',capacity:ru?'Помещается ли план в доступную мощность?':'Does the plan fit available capacity?',matrix:ru?'Какой вариант лучше по выбранным критериям?':'Which alternative best fits the criteria?',ownership:ru?'Где не хватает ясной ответственности?':'Where is ownership unclear?',change:ru?'Что изменится при принятии нового объёма?':'What changes if the proposed scope is accepted?',calibration:ru?'Насколько оценки отличаются от фактических затрат?':'How do estimates differ from actual effort?'};
 return <div className="panel decision-tool"><h2>{questions[tool]}</h2><p>{ru?'Используйте перед обязательством по срокам, распределением работы или согласованием решения. Все допущения можно изменить вручную.':'Use before a delivery commitment, work allocation or approval. Assumptions can be changed manually.'}</p><div className="button-row"><button className="button" onClick={load}>{ru?'Выбрать локальный проект':'Choose local project'}</button>{workspace&&<><label>{ru?'Проект':'Project'}<select value={projectId} onChange={e=>{setProjectId(e.target.value);setResult('')}}>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="button" onClick={useData}>{ru?'Использовать данные проекта':'Use project data'}</button></>}</div><p role="status">{message}</p>
 <div className="form-grid">{tool==='deadline'&&<><label className="field wide">{ru?'Завершения по полным календарным дням, включая нули, через запятую':'Completions per full calendar day, including zeros, comma separated'}<textarea value={samples} placeholder="0,1,2,0,0,1,1,0,2,1,0,0,1,2" onChange={e=>{setSamples(e.target.value);setResult('')}}/></label>{number(ru?'Осталось элементов':'Remaining items',remaining,setRemaining)}<label className="field">{ru?'Целевая дата':'Target date'}<input type="date" min={today} value={target} onChange={e=>{setTarget(e.target.value);setResult('')}}/></label></>}
 {tool==='emv'&&<>{number(ru?'Вероятность, %':'Probability, %',probability,setProbability)}{number(ru?'Потеря при событии, валюта проекта':'Loss if event occurs, project currency',impact,setImpact)}{number(ru?'Остаточная вероятность, %':'Residual probability, %',residualProbability,setResidualProbability)}{number(ru?'Остаточная потеря':'Residual loss',residualImpact,setResidualImpact)}<div className="wide"><button className="button" onClick={()=>{try{riskEMV([{probability,impact,residualProbability,residualImpact}]);setRiskRows([...riskRows,{probability,impact,residualProbability,residualImpact}]);setResult('')}catch{setMessage(ru?'Проверьте вероятность 0–100 и неотрицательную потерю.':'Check probability 0–100 and non-negative loss.')}}}>{ru?'Добавить риск в расчёт':'Add risk to calculation'}</button>{riskRows.length>0&&<><p>{ru?'Расчёт использует добавленные строки:':'Calculation uses added rows:'} {riskRows.length}</p><ul>{riskRows.map((row,i)=><li key={i}>{i+1}: {row.probability}% × {row.impact} <button className="button small" onClick={()=>{setRiskRows(riskRows.filter((_,j)=>j!==i));setResult('')}}>{ru?'Убрать':'Remove'} {i+1}</button></li>)}</ul></>}</div></>}
 {tool==='capacity'&&<><label className="field">{ru?'Неделя начинается':'Week starts'}<input type="date" value={week} onChange={e=>{setWeek(e.target.value);setResult('')}}/></label>{number(ru?'Доступно, ч/нед':'Available, h/week',capacity,setCapacity)}{number(ru?'Запланировано, ч/нед':'Planned, h/week',planned,setPlanned)}{number(ru?'Начато элементов (WIP)':'Started items (WIP)',wip,setWip)}{number(ru?'Завершений за календарный день':'Completions per calendar day',throughput,setThroughput)}{number(ru?'Целевое время, календарных дней':'Desired time, calendar days',days,setDays,1)}</>}
 {tool==='matrix'&&<>{[[ru?'Варианты, по строке':'Alternatives, one per line',alternatives,setAlternatives],[ru?'Критерии, по строке':'Criteria, one per line',criteria,setCriteria],[ru?'Веса через запятую':'Weights, comma separated',weights,setWeights],[ru?'Оценки 0–10: строка на вариант, столбец на критерий. Больше = лучше.':'Scores 0–10: one row per alternative, column per criterion. Higher = better.',scores,setScores]].map(([label,value,set])=><label className="field" key={label as string}>{label as string}<textarea value={value as string} onChange={e=>{(set as (s:string)=>void)(e.target.value);setResult('')}}/></label>)}</>}
 {tool==='change'&&<><label className="field wide">{ru?'Предлагаемое изменение объёма':'Proposed scope change'}<textarea value={scope} onChange={e=>{setScope(e.target.value);setResult('')}}/></label>{number(ru?'Изменение срока, дней':'Schedule delta, days',delay,setDelay,-3650)}{number(ru?'Изменение бюджета':'Budget delta',cost,setCost,-1e12)}{number(ru?'Изменение нагрузки, ч':'Workload delta, hours',hours,setHours,-1e6)}{[[ru?'Зависимости':'Dependencies',dependency,setDependency],[ru?'Качество':'Quality',quality,setQuality],[ru?'Риски':'Risks',risk,setRisk]].map(([label,value,set])=><label className="field" key={label as string}>{label as string}<input value={value as string} onChange={e=>{(set as (s:string)=>void)(e.target.value);setResult('')}}/></label>)}</>}
 </div>
 {tool==='ownership'&&workspace&&<><p>{ru?'Правила: активная запись без владельца; текстовое имя вне команды или с несколькими совпадениями; более половины ≥ 3 критичных работ у одного участника.':'Rules: active record without owner; text owner outside team or matching multiple members; more than half of ≥ 3 critical items owned by one member.'}</p><ul>{ownershipCoverage(workspace,projectId).map((x,i)=><li key={i}><Link href={`/${locale}/workspace/?project=${projectId}&view=${x.kind==='work'?'work':x.kind==='team'?'people':x.kind==='milestone'?'planning':'raid'}&item=${x.id}`}>{x.title}</Link> · {({unassigned:ru?'Нет владельца':'Unassigned',external:ru?'Внешнее имя: проверить':'External name: verify',ambiguous:ru?'Несколько совпадений':'Ambiguous name',concentration:ru?'Концентрация критичных работ':'Critical ownership concentration'})[x.reason]}</li>)}</ul></>}
 {tool==='calibration'&&workspace&&(()=>{const r=estimateCalibration(workspace,projectId);return <p>{ru?'Выборка':'Sample'}: {r.count}. {r.medianRatio===null?(ru?'Нужно минимум 10 завершённых работ с положительной исходной оценкой и фактом.':'At least 10 completed items with positive original estimate and actual effort required.'):`${ru?'Медиана факт/оценка':'Median actual/estimate'}: ${r.medianRatio.toFixed(2)}; ${ru?'медианная абсолютная ошибка':'median absolute error'}: ${(r.medianAbsoluteError!*100).toFixed(1)}%.`} {ru?'Используйте только сопоставимые единицы. Записи без зафиксированной исходной оценки исключены.':'Use comparable units only. Records without a recorded original estimate are excluded.'}</p>})()}
 {!['ownership','calibration'].includes(tool)&&<button className="button primary" onClick={calculate}>{ru?'Рассчитать':'Calculate'}</button>}
 {result&&<><pre className="tool-output" role="status">{result}</pre>{(tool==='matrix'||tool==='change')&&project&&<button className="button" onClick={save}>{ru?'Создать запись для согласования':'Create record for approval'}</button>}</>}
 <details><summary>{ru?'Допущения, ограничения и следующий шаг':'Assumptions, limitations and next action'}</summary><p>{tool==='deadline'?(ru?'Повторная выборка дневной пропускной способности с фиксированным seed. Даты — календарные; предполагаются стабильная команда, сопоставимый размер работ и полный журнал. Изменение объёма и зависимости не моделируются. Сравните сценарий с меньшим объёмом; проверьте критические зависимости в Плане.':'Seeded daily-throughput bootstrap. Calendar dates; assumes stable team, comparable item sizes and complete history. Scope changes and dependencies are not modeled. Compare reduced scope; review critical dependencies in Plan.'):tool==='emv'?(ru?'EMV = вероятность × денежное влияние. Резервные множители — сценарии, а не процентили. Для одиночного крупного риска средняя потеря может сильно отличаться от требуемой ликвидности. Зафиксируйте источник оценки и план реагирования.':'EMV = probability × monetary impact. Reserve multipliers are scenarios, not percentiles. A single large risk may need liquidity far above its expected loss. Record the estimate source and response plan.'):tool==='capacity'?(ru?'Часы нагрузки сравниваются только с часами мощности. WIP ≈ дневная пропускная способность × целевое время при стабильном потоке. Это ориентир для эксперимента; points не переводятся в часы. Уменьшите начатую работу и проверьте результат через цикл.':'Workload hours are compared only with capacity hours. WIP ≈ daily throughput × desired time under stable flow. This is an experiment reference; points are not converted to hours. Reduce started work and review after a cycle.'):tool==='matrix'?(ru?'Сумма вес × оценка / сумма весов. Проверяется изменение каждого веса на ±20% с повторной нормализацией. Оценки субъективны: при смене победителя уточните важнейший критерий до решения.':'Sum of weight × score / total weight. Each weight is varied ±20% and renormalized. Scores are judgments: if the winner changes, clarify the sensitive criterion before deciding.'):(ru?'Сценарий содержит введённые предположения. Он не пересчитывает базовый план автоматически. Проверьте зависимости и получите согласование до изменения обязательств.':'The scenario contains entered assumptions. It does not automatically rewrite the baseline. Review dependencies and obtain approval before changing commitments.')}</p></details>
 {project&&<Link className="button small" href={`/${locale}/workspace/?project=${projectId}&view=${tool==='change'?'control':tool==='matrix'?'raid':'planning'}`}>{ru?'Открыть проект':'Open project'}</Link>}
 </div>
}
