"use client";
import {useState} from "react";
import Link from "next/link";
import type {Locale} from "@/domain/schemas";
import {managementRoles,roleLabels,type ManagementRole} from "@/domain/management-role";
import {sources} from "@/content/catalog";

const guides={
  project:{term:["Контроль изменений","Change control"],question:["Объём растёт, а срок остался прежним","Scope grows while the deadline stays fixed"],meaning:["Новый запрос меняет обязательства. Сначала нужно согласовать последствия.","A new request changes commitments. Agree its consequences before changing the plan."],why:["Выбрать: принять запрос, сократить другую работу или изменить срок и бюджет.","Choose whether to accept it, remove other work, or change the date and budget."],action:["Запишите изменение, альтернативы и влияние на сроки, стоимость, качество и риски. Назначьте утверждающего. После решения обновите прогноз; базовый план меняйте отдельно с причиной.","Record the change, alternatives and effects on schedule, cost, quality and risks. Assign an approver. Update the forecast after the decision; change the baseline separately with a reason."],mistake:["Молча заменить базовый план новым прогнозом.","Silently replacing the baseline with a new forecast."],view:"control",source:"pmbok8"},
  program:{term:["Реализация выгод","Benefits realization"],question:["Компоненты завершены, но общая выгода не измерена","Components are finished, but the shared benefit is unmeasured"],meaning:["Поставка компонентов ещё не доказывает полезное изменение для получателя.","Delivering components does not yet prove a useful change for their recipient."],why:["Понять, какой компонент или переход в эксплуатацию требует вмешательства.","Identify which component or transition into operation needs intervention."],action:["Запишите исходное и целевое значения, единицу, владельца измерения и дату обзора. Свяжите выгоду с компонентами. В обзоре сохраните факт и проверьте другие причины изменения.","Record baseline, target, unit, measurement owner and review date. Link the benefit to its components. Record the actual result and check other explanations for the change."],mistake:["Считать процент выполненных задач процентом реализации выгоды.","Treating task completion as benefit realization."],view:"program",source:"program5"},
  delivery:{term:["Возраст незавершённой работы","Work item age"],question:["Работы начаты, но поставка застряла","Work has started, but delivery is stuck"],meaning:["Время с начала незавершённой работы помогает увидеть ожидание и стареющие обязательства.","Time since unfinished work started helps reveal waiting and aging commitments."],why:["Выбрать, какой блокер снять прежде, чем начинать новую работу.","Choose which blocker to remove before starting more work."],action:["Проверьте даты начала, активную работу, блокеры и зависимости. Назначьте действие по старейшему существенному блокеру. Сравните результат в следующем обзоре. При недостаточной выборке не обещайте дату по перцентилю.","Check start dates, active work, blockers and dependencies. Assign an action to the oldest material blocker. Review the result next cycle. Do not promise a percentile date from an insufficient sample."],mistake:["Сравнивать команды по скорости или скрывать недостающие даты.","Ranking teams by velocity or hiding missing dates."],view:"delivery",source:"kanban2025"},
  operations:{term:["Операционный контроль","Operational control"],question:["Инцидент повторяется, обязательные проверки пропущены","An incident recurs and required checks are overdue"],meaning:["Постоянному процессу нужны наблюдения, коррекция и проверка устойчивости изменений.","An ongoing process needs observation, correction and verification that improvements hold."],why:["Отделить восстановление сервиса от устранения повторяющейся причины.","Separate restoring the service from removing the recurring cause."],action:["Зафиксируйте инцидент и владельца восстановления. Проверьте пропущенные контроли и рабочую инструкцию. Запишите корректирующее действие в работу, ожидаемый результат и дату проверки. После проверки обновите инструкцию.","Record the incident and recovery owner. Check overdue controls and the runbook. Create corrective work with an expected result and review date. Update the runbook after verification."],mistake:["Закрывать повторяющийся инцидент без проверки корректирующего действия.","Closing a recurring incident without verifying the corrective action."],view:"operations",source:"kanban2025"},
} as const;
export function RoleKnowledge({locale}:{locale:Locale}) {
  const [role,setRole]=useState<ManagementRole>("project"),ru=locale==="ru",index=ru?0:1,guide=guides[role],source=sources.find(row=>row.id===guide.source);
  return <section className="public-container"><h2>{ru?"Начните с управленческой проблемы":"Start with a management problem"}</h2><div className="tabs" role="group" aria-label={ru?"Роль в базе знаний":"Knowledge role"}>{managementRoles.map(value=><button key={value} aria-pressed={value===role} onClick={()=>setRole(value)}>{roleLabels[locale][value]}</button>)}</div><article className="panel"><h3>{guide.question[index]}</h3><p><strong>{guide.term[index]}</strong> · {guide.meaning[index]}</p><p><strong>{ru?"Какое решение принять":"Decision to make"}</strong>: {guide.why[index]}</p><p>{guide.action[index]}</p><details><summary>{ru?"Типичная ошибка и основание":"Common mistake and basis"}</summary><p>{guide.mistake[index]}</p><p>{ru?"Авторский практический сценарий PMWORK. Рекомендации требуют проверки в вашем контексте; это не цитата из стандарта.":"An original PMWORK practice scenario. Verify recommendations in your context; this is not a quotation from a standard."}</p>{source&&<p><a href={source.url}>{source.title} · {source.version}</a> · {ru?"Публичный источник проверен":"Public source checked"}: {source.checked}</p>}</details><Link className="button" href={`/${locale}/workspace/?view=${guide.view}`}>{ru?"Применить в рабочем пространстве":"Apply in the workspace"}</Link></article></section>;
}
