"use client";
import {DocumentPreview} from "./document-preview";
import { templateDocument, type TemplateDepth } from "@/domain/template-document";
import { useState, useSyncExternalStore } from 'react';
import Link from 'next/link';
import type { Locale,Workspace } from '@/domain/schemas';
import type { Template } from '@/content/catalog';
import { loadWorkspace,saveWorkspace } from '@/data/storage';
import { WorkspaceMore } from './workspace-more';
import {workspaceScopes,scopeKey,contextProject,contextWorkspace,applyContextWorkspace} from "@/domain/work-scope";
const contextLink=(key:string,register:string,id:string,locale:string)=>{const scope:Record<string,string>=key.startsWith("@program/")?{view:"program",context:key.slice(9),register}:key.startsWith("@operation/")?{view:"operations",context:key.slice(11),register}:{project:key,view:register};return `/${locale}/workspace/?${new URLSearchParams({...scope,item:id,kind:"document"})}`;};
const subscribeHydration=()=>()=>{},getHydratedSnapshot=()=>true,getServerHydratedSnapshot=()=>false;
export function TemplateApply({template,locale}:{template:Template;locale:Locale}) {
 const ru=locale==='ru';const hydrated=useSyncExternalStore(subscribeHydration,getHydratedSnapshot,getServerHydratedSnapshot);const [depth,setDepth]=useState<TemplateDepth>('standard');const [workspace,setWorkspace]=useState<Workspace|null>(null),[project,setProject]=useState(''),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[created,setCreated]=useState<{id:string;project:string;body:string;at:string}|null>(null);
 async function prepare(){try{const data=await loadWorkspace();setWorkspace(data);setProject(data?scopeKey(workspaceScopes(data)[0]??{kind:'project',id:''}):'');setOpen(true);}catch{setMessage(ru?'Не удалось прочитать локальные данные. Восстановите копию в рабочем пространстве.':'Local data could not be read. Restore a backup in Workspace.');}}
 async function apply(){try{const current=await loadWorkspace();const scope=current&&workspaceScopes(current).find(scope=>scopeKey(scope)===project);if(!current||!scope)throw Error();const adapted=contextWorkspace(current,scope);const at=new Date().toISOString(),id=`DOC-${crypto.randomUUID()}`;await saveWorkspace(applyContextWorkspace(current,{...adapted,documents:[...current.documents,{id,projectId:project,title:template.title[locale],type:`template:${template.slug}`,body:templateDocument(template,adapted,project,locale,depth),relatedIds:[],updatedAt:at}],activities:[...current.activities,{id:crypto.randomUUID(),projectId:project,at,type:'template',message:`${template.title[locale]} → ${id}`}]},scope));setCreated({id,project,at,body:templateDocument(template,adapted,project,locale,depth)});setOpen(false);setMessage(`${ru?'Создано в':'Created in'} ${contextProject(current,scope).name}`);}catch{setMessage(ru?'Не удалось применить шаблон':'Could not apply template');}}
 async function undo(){if(!created)return;try{const current=await loadWorkspace();if(!current)return;if(current.documents.find(d=>d.id===created.id)?.body!==created.body || current.documents.find(d=>d.id===created.id)?.updatedAt!==created.at){setMessage(ru?'Документ изменён после создания. Автоматическая отмена остановлена, чтобы сохранить правки.':'Document changed since creation. Automatic undo stopped to preserve edits.');return;}const scope=workspaceScopes(current).find(scope=>scopeKey(scope)===created.project);if(!scope)throw Error();await saveWorkspace(applyContextWorkspace(current,{...contextWorkspace(current,scope),documents:current.documents.filter(d=>d.id!==created.id),activities:[...current.activities,{id:crypto.randomUUID(),projectId:created.project,at:new Date().toISOString(),type:'template-undo',message:created.id}]},scope));setCreated(null);setMessage(ru?'Применение отменено':'Application undone');}catch{setMessage(ru?'Не удалось отменить':'Could not undo');}}
 return <><button className="button primary small" disabled={!hydrated} onClick={prepare}>{ru?'Использовать':'Use template'}</button>{message&&<p role="status">{message}</p>}{created&&<div className="button-row"><Link className="button small" href={contextLink(created.project,"documents",created.id,locale)}>{ru?'Открыть':'Open'}</Link><button className="button small" onClick={undo}>{ru?'Отменить':'Undo'}</button></div>}{open&&<WorkspaceMore title={template.title[locale]} onClose={()=>setOpen(false)}>{workspace&&workspaceScopes(workspace).length?<><label>{ru?'Рабочий контекст':'Working context'}<select aria-label={ru?'Рабочий контекст':'Working context'} className="input" value={project} onChange={e=>setProject(e.target.value)}>{workspaceScopes(workspace).map(scope=><option key={scopeKey(scope)} value={scopeKey(scope)}>{contextProject(workspace,scope).name}</option>)}</select></label><label>{ru?'Глубина':'Depth'}<select aria-label={ru?'Глубина':'Depth'} className="input" value={depth} onChange={e=>setDepth(e.target.value as TemplateDepth)}><option value="minimal">{ru?'Минимальная':'Minimal'}</option><option value="standard">{ru?'Стандартная':'Standard'}</option><option value="detailed">{ru?'Подробная':'Detailed'}</option></select></label><h3>{ru?'Предпросмотр':'Preview'}</h3><DocumentPreview body={templateDocument(template,contextWorkspace(workspace,workspaceScopes(workspace).find(scope=>scopeKey(scope)===project)!),project,locale,depth)}/><div className="document-apply-bar"><button className="button primary" onClick={apply}>{ru?'Применить':'Apply'}</button></div></>:<><p>{ru?'Сначала создайте рабочий контекст в рабочем пространстве.':'Create a working context in Workspace first.'}</p><Link className="button primary" href={`/${locale}/workspace/`}>{ru?'Открыть рабочее пространство':'Open Workspace'}</Link></>}</WorkspaceMore>}</>;
}
