"use client";
import { useState } from 'react';
import Link from 'next/link';
import type { Locale,Workspace } from '@/domain/schemas';
import type { Template } from '@/content/catalog';
import { loadWorkspace,saveWorkspace } from '@/data/storage';
import { WorkspaceMore } from './workspace-more';
export function TemplateApply({template,locale}:{template:Template;locale:Locale}) {
 const ru=locale==='ru';const [workspace,setWorkspace]=useState<Workspace|null>(null),[project,setProject]=useState(''),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[created,setCreated]=useState<{id:string;project:string}|null>(null);
 async function prepare(){try{const data=await loadWorkspace();setWorkspace(data);setProject(data?.projects[0]?.id??'');setOpen(true);}catch{setMessage(ru?'Не удалось прочитать локальные данные. Восстановите копию в Workspace.':'Local data could not be read. Restore a backup in Workspace.');}}
 async function apply(){try{const current=await loadWorkspace();if(!current||!current.projects.some(p=>p.id===project))throw Error();const at=new Date().toISOString(),id=`DOC-${crypto.randomUUID()}`;await saveWorkspace({...current,documents:[...current.documents,{id,projectId:project,title:template.title[locale],type:`template:${template.slug}`,body:`# ${template.title[locale]}\n\n${template.fields.map(f=>`## ${f[locale]}\n\n${template.guidance[locale]}`).join('\n\n')}`,relatedIds:[],updatedAt:at}],activities:[...current.activities,{id:crypto.randomUUID(),projectId:project,at,type:'template',message:`${template.title[locale]} → ${id}`}]});setCreated({id,project});setOpen(false);setMessage(`${ru?'Создано в':'Created in'} ${current.projects.find(p=>p.id===project)!.name}`);}catch{setMessage(ru?'Не удалось применить шаблон':'Could not apply template');}}
 async function undo(){if(!created)return;try{const current=await loadWorkspace();if(!current)return;await saveWorkspace({...current,documents:current.documents.filter(d=>d.id!==created.id),activities:[...current.activities,{id:crypto.randomUUID(),projectId:created.project,at:new Date().toISOString(),type:'template-undo',message:created.id}]});setCreated(null);setMessage(ru?'Применение отменено':'Application undone');}catch{setMessage(ru?'Не удалось отменить':'Could not undo');}}
 return <><button className="button primary small" onClick={prepare}>{ru?'Использовать':'Use template'}</button>{message&&<p role="status">{message}</p>}{created&&<div className="button-row"><Link className="button small" href={`/${locale}/workspace/?project=${created.project}&view=documents&item=${created.id}`}>{ru?'Открыть':'Open'}</Link><button className="button small" onClick={undo}>{ru?'Отменить':'Undo'}</button></div>}{open&&<WorkspaceMore title={template.title[locale]} onClose={()=>setOpen(false)}>{workspace?.projects.length?<><label>{ru?'Проект':'Project'}<select className="input" value={project} onChange={e=>setProject(e.target.value)}>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="button primary" onClick={apply}>{ru?'Применить':'Apply'}</button></>:<><p>{ru?'Сначала создайте проект в Workspace.':'Create a project in Workspace first.'}</p><Link className="button primary" href={`/${locale}/workspace/`}>{ru?'Создать проект':'Create project'}</Link></>}</WorkspaceMore>}</>;
}
