"use client";
import { acrossProjectSignals } from "@/domain/across-work-signals";
import { managementSignals } from "@/domain/management-signals";
import { localDay } from "@/domain/work-views";
import type { ViewProps } from "./workspace-views";

export function TodayAcrossWork({workspace,locale,onView,onProject,onEdit}:ViewProps) {
  const ru=locale==="ru", asOf=localDay();
  const projectSignals=acrossProjectSignals(workspace,locale,asOf).map(({project,signal})=>({id:`${project.id}-${signal.id}`,title:`${project.name} · ${signal.title}`,why:signal.why,action:signal.action,owner:signal.source?.owner??"",priority:signal.severity==="critical"?100:signal.severity==="high"?80:40,group:signal.category==="decision"?"decide":signal.category==="review"||signal.category==="control"?"check":"act",dueDate:signal.dueDate,open:()=>{onProject(project.id);onView(signal.view);if(signal.source)onEdit(signal.source.kind,signal.source.id);},rule:signal.evidence.rule,missingEvidence:signal.evidence.missing}));
  const otherSignals=managementSignals(workspace,locale,asOf).map(signal=>({...signal,open:()=>{const next=new URL(window.location.href);next.searchParams.set("context",signal.source.id);for(const key of ["item","kind","register"])next.searchParams.delete(key);if(signal.source.kind&&signal.source.recordId){next.searchParams.set("item",signal.source.recordId);next.searchParams.set("kind",signal.source.kind);if(signal.source.register)next.searchParams.set("register",signal.source.register);}history.pushState(null,"",next);dispatchEvent(new Event("pmwork-url"));onView(signal.source.collection==="programs"?"program":"operations");}}));
  const signals=[...projectSignals,...otherSignals].sort((a,b)=>b.priority-a.priority||(a.dueDate??"9999").localeCompare(b.dueDate??"9999")||a.id.localeCompare(b.id));
  const top=signals[0];
  return <div className="management-center"><section className="panel priority-focus"><p className="eyebrow">{ru?"Главное по всей работе":"Top priority across all work"}</p>{top?<><h3>{top.title}</h3><p>{top.why}</p><p>{top.action}</p><p>{ru?"Владелец":"Owner"}: {top.owner||(ru?"не назначен":"unassigned")}</p><button className="button primary" onClick={top.open}>{ru?"Открыть источник":"Open source"}</button><details><summary>{ru?"Почему это главное":"Why this ranks first"}</summary><p>{ru?"Приоритет правила, срок, затем стабильный ID. Это правила PMWORK, а не вероятность успеха.":"Rule priority, due date, then stable ID. These are PMWORK rules, not success probabilities."}</p><p>{top.rule}</p><p>{ru?"На дату":"As of"}: {asOf}</p><p>{ru?"Недостающие данные":"Missing evidence"}: {top.missingEvidence.join(", ")||"—"}</p></details></>:<><h3>{ru?"Нет срочных сигналов по текущим записям":"No immediate signals in current records"}</h3><p>{ru?"Проверьте полноту и актуальность данных. Отсутствие сигнала не означает Healthy.":"Review evidence completeness and freshness. Absence of a signal does not imply Healthy."}</p></>}</section>{["decide","act","check"].map(group=>{const rows=signals.slice(1).filter(signal=>signal.group===group);return rows.length?<section className="panel" key={group}><h3>{group.toUpperCase()} ({rows.length})</h3><ul className="clean-list">{rows.slice(0,10).map(signal=><li key={signal.id}><button className="button small" onClick={signal.open}>{signal.title}</button><p>{signal.why}</p></li>)}</ul></section>:null;})}<p className="muted">{ru?"STABLE: состояние не выводится из отсутствующих данных.":"STABLE: status is never inferred from missing evidence."}</p></div>;
}
