"use client";
import { useId } from "react";
import { X } from "lucide-react";
import type { Locale,Workspace,WorkItem } from "@/domain/schemas";
import { governanceLevel,scoreApproaches,type Context } from "@/domain/method-fit";
import type { CreateType } from "./workspace-types";

const titles:Record<CreateType,{ru:string;en:string}>={work:{ru:"Новый рабочий элемент",en:"New work item"},risk:{ru:"Новый риск",en:"New risk"},issue:{ru:"Новая проблема",en:"New issue"},decision:{ru:"Новое решение",en:"New decision"},assumption:{ru:"Новое допущение",en:"New assumption"},milestone:{ru:"Новая контрольная точка",en:"New milestone"},stakeholder:{ru:"Новый stakeholder",en:"New stakeholder"},budget:{ru:"Новая статья бюджета",en:"New budget line"},document:{ru:"Новый документ",en:"New document"},team:{ru:"Новый участник команды",en:"New team member"},change:{ru:"Новый запрос на изменение",en:"New change request"},meeting:{ru:"Новая встреча",en:"New meeting"},vendor:{ru:"Новый поставщик",en:"New vendor"},objective:{ru:"Новый outcome / KPI",en:"New outcome / KPI"},iteration:{ru:"Новая итерация",en:"New iteration"},project:{ru:"Создать проект",en:"Create project"}};
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID().slice(0,8)}`;
const text=(fd:FormData,key:string)=>String(fd.get(key)??"").trim();
const number=(fd:FormData,key:string,fallback=0)=>{const raw=fd.get(key);if(raw===null||raw==="")return fallback;const parsed=Number(raw);return Number.isFinite(parsed)?parsed:fallback};
const lines=(value:string)=>value.split(/\n|,/).map(x=>x.trim()).filter(Boolean);

export function WorkspaceDialog({type,locale,workspace,projectId,onClose,onCommit}:{type:CreateType;locale:Locale;workspace:Workspace;projectId:string;onClose:()=>void;onCommit:(workspace:Workspace,projectId?:string)=>void}){
  const ru=locale==="ru",prefix=useId(),today=new Date().toISOString().slice(0,10),label=titles[type][locale];
  const field=(name:string,labelText:string,kind:"text"|"textarea"|"date"|"number"="text",required=false)=>{const id=`${prefix}-${name}`;return <div className={`field ${kind==="textarea"?"wide":""}`}><label htmlFor={id}>{labelText}</label>{kind==="textarea"?<textarea id={id} name={name} required={required}/>:<input id={id} name={name} type={kind} required={required}/>}</div>};
  const submit=(fd:FormData)=>{
    const at=new Date().toISOString(),title=text(fd,"title"),owner=text(fd,"owner"),description=text(fd,"description"),due=text(fd,"dueDate")||today;let next={...workspace};
    const activity=(message:string)=>({id:uid("ACT"),projectId,at,type,message});
    if(type==="project"){
      if(!title)return;const read=(key:keyof Context)=>number(fd,key,3);const context:Context={uncertainty:read("uncertainty"),volatility:read("volatility"),feedback:read("feedback"),frequency:read("frequency"),compliance:read("compliance"),dependencies:read("dependencies"),autonomy:read("autonomy"),scopeRigidity:read("scopeRigidity"),deadlineRigidity:read("deadlineRigidity"),stakeholders:read("stakeholders")};const fit=scoreApproaches(context)[0]!.approach.toLowerCase();const approach=fit==="adaptive"?"adaptive":fit==="predictive"?"predictive":fit==="flow"?"flow":"hybrid";const governance=governanceLevel(context).toLowerCase() as "lightweight"|"standard"|"controlled";const id=uid("project");
      next={...workspace,projects:[...workspace.projects,{id,name:title,status:"active",owner,sponsor:text(fd,"sponsor"),approach,governance,type:(text(fd,"projectType")||"general") as Workspace["projects"][number]["type"],startDate:today,targetDate:due,purpose:description,objective:text(fd,"objective"),successMeasures:lines(text(fd,"successMeasures")),health:{schedule:"unknown",scope:"unknown",budget:"unknown",risks:"unknown",blockers:"green",capacity:"unknown",alignment:"unknown"},demo:false,currency:text(fd,"currency")||"USD",scopeIn:text(fd,"scopeIn"),scopeOut:text(fd,"scopeOut"),constraints:text(fd,"constraints"),definitionOfDone:text(fd,"definitionOfDone")}],projectSettings:[...workspace.projectSettings,{projectId:id,enabledTypes:["initiative","epic","feature","story","task","subtask","bug","spike","deliverable"],wipLimits:{"in-progress":3,review:2},governance,probabilityScale:5,impactScale:5}],activities:[...workspace.activities,{id:uid("ACT"),projectId:id,at,type:"project",message:ru?"Проект создан":"Project created"}]};onCommit(next,id);onClose();return;
    }
    if(type==="work")next={...workspace,workItems:[...workspace.workItems,{id:uid("WI"),projectId,title,description,type:(text(fd,"workType")||"task") as WorkItem["type"],status:"backlog",priority:(text(fd,"priority")||"medium") as WorkItem["priority"],owner,contributors:[],labels:lines(text(fd,"labels")),startDate:text(fd,"startDate")||undefined,dueDate:due||undefined,estimate:number(fd,"estimate",0)||undefined,dependencies:[],acceptanceCriteria:lines(text(fd,"acceptance")),done:false,blocked:false,riskIds:[],objectiveIds:[],order:workspace.workItems.length,createdAt:at,updatedAt:at,archived:false}],activities:[...workspace.activities,activity(`${ru?"Создан item":"Created item"}: ${title}`)]};
    if(type==="risk")next={...workspace,risks:[...workspace.risks,{id:uid("R"),projectId,title,category:text(fd,"category")||"General",description,probability:Math.max(1,Math.min(5,number(fd,"probability",3))),impact:Math.max(1,Math.min(5,number(fd,"impact",3))),owner,strategy:"mitigate",actions:text(fd,"actions"),trigger:text(fd,"trigger"),reviewDate:due,status:"open"}],activities:[...workspace.activities,activity(`${ru?"Создан риск":"Created risk"}: ${title}`)]};
    if(type==="issue")next={...workspace,issues:[...workspace.issues,{id:uid("I"),projectId,title,description,impact:Math.max(1,Math.min(5,number(fd,"impact",3))),urgency:Math.max(1,Math.min(5,number(fd,"urgency",3))),owner,plan:text(fd,"actions"),dueDate:due,escalation:text(fd,"escalation"),relatedWorkIds:[],status:"open"}],activities:[...workspace.activities,activity(`${ru?"Создан issue":"Created issue"}: ${title}`)]};
    if(type==="decision")next={...workspace,decisions:[...workspace.decisions,{id:uid("D"),projectId,question:title,context:description,alternatives:lines(text(fd,"alternatives")),criteria:lines(text(fd,"criteria")),decision:"",rationale:"",owner,date:due,participants:[],consequences:text(fd,"consequences"),revisitTrigger:"",status:"pending"}],activities:[...workspace.activities,activity(`${ru?"Запрошено решение":"Decision requested"}: ${title}`)]};
    if(type==="assumption")next={...workspace,assumptions:[...workspace.assumptions,{id:uid("A"),projectId,text:title,rationale:description,owner,validationMethod:text(fd,"method"),validationDate:due,status:"untested",effectIfFalse:text(fd,"consequences")}],activities:[...workspace.activities,activity(`${ru?"Добавлено допущение":"Assumption added"}: ${title}`)]};
    if(type==="milestone")next={...workspace,milestones:[...workspace.milestones,{id:uid("M"),projectId,title,date:due,status:"planned",progress:0}],activities:[...workspace.activities,activity(`${ru?"Добавлен milestone":"Milestone added"}: ${title}`)]};
    if(type==="stakeholder")next={...workspace,stakeholders:[...workspace.stakeholders,{id:uid("S"),projectId,name:title,role:description,influence:Math.max(1,Math.min(5,number(fd,"influence",3))),interest:Math.max(1,Math.min(5,number(fd,"interest",3))),attitude:"neutral",expectations:text(fd,"expectations"),communicationNeeds:text(fd,"communication"),owner,strategy:text(fd,"strategy")}],activities:[...workspace.activities,activity(`${ru?"Добавлен stakeholder":"Stakeholder added"}: ${title}`)]};
    if(type==="budget")next={...workspace,budgets:[...workspace.budgets,{id:uid("B"),projectId,category:title,planned:number(fd,"planned"),actual:number(fd,"actual"),committed:number(fd,"committed"),forecast:number(fd,"forecast")||undefined}],activities:[...workspace.activities,activity(`${ru?"Добавлена статья бюджета":"Budget line added"}: ${title}`)]};
    if(type==="document")next={...workspace,documents:[...workspace.documents,{id:uid("DOC"),projectId,title,type:text(fd,"documentType")||"note",body:description,relatedIds:[],updatedAt:at}],activities:[...workspace.activities,activity(`${ru?"Создан документ":"Document created"}: ${title}`)]};
    if(type==="team")next={...workspace,teamMembers:[...workspace.teamMembers,{id:uid("TM"),projectId,name:title,role:description,responsibility:text(fd,"responsibility"),weeklyCapacity:number(fd,"capacity",40),timezone:text(fd,"timezone")||"UTC",skills:lines(text(fd,"skills"))}],activities:[...workspace.activities,activity(`${ru?"Добавлен участник":"Team member added"}: ${title}`)]};
    if(type==="change")next={...workspace,changes:[...workspace.changes,{id:uid("CR"),projectId,change:title,requester:owner,reason:description,scopeImpact:text(fd,"scopeImpact"),scheduleImpact:text(fd,"scheduleImpact"),costImpact:text(fd,"costImpact"),riskImpact:text(fd,"riskImpact"),qualityImpact:text(fd,"qualityImpact"),alternatives:text(fd,"alternatives"),recommendation:text(fd,"recommendation"),decision:"",approver:text(fd,"approver"),status:"assessing"}],activities:[...workspace.activities,activity(`${ru?"Создан change request":"Change request created"}: ${title}`)]};
    if(type==="meeting")next={...workspace,meetings:[...workspace.meetings,{id:uid("MEET"),projectId,title,date:due,attendees:lines(text(fd,"attendees")),agenda:lines(description),notes:"",outputs:[]}],activities:[...workspace.activities,activity(`${ru?"Запланирована встреча":"Meeting scheduled"}: ${title}`)]};
    if(type==="vendor")next={...workspace,vendors:[...workspace.vendors,{id:uid("V"),projectId,name:title,scope:description,owner,deliverables:lines(text(fd,"deliverables")),milestones:[],cost:number(fd,"cost"),status:"active",riskIds:[],dependencyIds:[],reviewNotes:text(fd,"notes")}],activities:[...workspace.activities,activity(`${ru?"Добавлен поставщик":"Vendor added"}: ${title}`)]};
    if(type==="objective")next={...workspace,objectives:[...workspace.objectives,{id:uid("O"),projectId,description:title,type:(text(fd,"objectiveType")||"outcome") as Workspace["objectives"][number]["type"],baseline:text(fd,"baseline"),target:text(fd,"target"),measure:description,dueDate:due,owner,deliverableIds:[],status:"tracking"}],activities:[...workspace.activities,activity(`${ru?"Добавлен outcome":"Outcome added"}: ${title}`)]};
    if(type==="iteration")next={...workspace,iterations:[...workspace.iterations,{id:uid("IT"),projectId,title,goal:description,startDate:text(fd,"startDate")||today,endDate:due,capacity:number(fd,"capacity"),workItemIds:[],status:"planned"}],activities:[...workspace.activities,activity(`${ru?"Добавлена итерация":"Iteration added"}: ${title}`)]};
    onCommit(next);onClose();
  };
  return <div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby={`${prefix}-heading`}><div className="page-title"><h2 id={`${prefix}-heading`}>{label}</h2><button className="button small" onClick={onClose} aria-label={ru?"Закрыть":"Close"}><X size={18}/></button></div><form action={submit} className="form-grid">
    {field("title",type==="decision"?(ru?"Вопрос":"Question"):type==="objective"?(ru?"Outcome / KPI":"Outcome / KPI"):(ru?"Название":"Title"),"text",true)}
    {!["budget","team","milestone"].includes(type)&&field("description",type==="meeting"?(ru?"Повестка — один вопрос на строку":"Agenda — one question per line"):(ru?"Контекст / описание":"Context / description"),"textarea")}
    {["work","risk","issue","decision","assumption","stakeholder","team","vendor","objective","project"].includes(type)&&field("owner",type==="project"?(ru?"Руководитель проекта":"Project lead"):(ru?"Владелец":"Owner"))}
    {["work","risk","issue","decision","assumption","milestone","objective","iteration","project","meeting"].includes(type)&&field("dueDate",type==="project"?(ru?"Целевая дата":"Target date"):(ru?"Срок / дата review":"Due / review date"),"date")}
    {type==="work"&&<><div className="field"><label htmlFor={`${prefix}-workType`}>{ru?"Тип":"Type"}</label><select id={`${prefix}-workType`} name="workType"><option value="task">Task</option><option value="story">Story</option><option value="feature">Feature</option><option value="deliverable">Deliverable</option><option value="bug">Bug</option><option value="spike">Spike</option></select></div><div className="field"><label htmlFor={`${prefix}-priority`}>{ru?"Приоритет":"Priority"}</label><select id={`${prefix}-priority`} name="priority"><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option><option value="low">Low</option></select></div>{field("startDate",ru?"Начало":"Start","date")}{field("estimate",ru?"Оценка effort":"Effort estimate","number")}{field("acceptance",ru?"Критерии приёмки — по строке":"Acceptance criteria — one per line","textarea")}</>}
    {type==="risk"&&<>{field("category",ru?"Категория":"Category")}{field("probability","Probability 1–5","number")}{field("impact","Impact 1–5","number")}{field("trigger","Trigger")}{field("actions",ru?"Response actions":"Response actions","textarea")}</>}
    {type==="issue"&&<>{field("impact","Impact 1–5","number")}{field("urgency","Urgency 1–5","number")}{field("actions",ru?"Recovery plan":"Recovery plan","textarea")}{field("escalation",ru?"Эскалация":"Escalation")}</>}
    {type==="decision"&&<>{field("alternatives",ru?"Альтернативы — по строке":"Alternatives — one per line","textarea")}{field("criteria",ru?"Критерии — по строке":"Criteria — one per line","textarea")}{field("consequences",ru?"Последствие отсутствия решения":"Consequence of no decision","textarea")}</>}
    {type==="assumption"&&<>{field("method",ru?"Как проверить":"Validation method")}{field("consequences",ru?"Что будет, если неверно":"Effect if false","textarea")}</>}
    {type==="stakeholder"&&<>{field("influence",ru?"Влияние 1–5":"Influence 1–5","number")}{field("interest",ru?"Интерес 1–5":"Interest 1–5","number")}{field("expectations",ru?"Ожидания":"Expectations")}{field("communication",ru?"Коммуникация":"Communication")}{field("strategy",ru?"Стратегия вовлечения":"Engagement strategy")}</>}
    {type==="budget"&&<>{field("planned","Planned","number")}{field("actual","Actual","number")}{field("committed","Committed","number")}{field("forecast","Forecast","number")}</>}
    {type==="team"&&<>{field("responsibility",ru?"Ответственность":"Responsibility")}{field("capacity",ru?"Часов в неделю":"Hours per week","number")}{field("timezone",ru?"Часовой пояс":"Timezone")}{field("skills",ru?"Навыки через запятую":"Skills, comma separated")}</>}
    {type==="document"&&field("documentType",ru?"Тип документа":"Document type")}
    {type==="meeting"&&field("attendees",ru?"Участники через запятую":"Attendees, comma separated")}
    {type==="vendor"&&<>{field("deliverables",ru?"Deliverables через запятую":"Deliverables, comma separated")}{field("cost",ru?"Стоимость":"Cost","number")}{field("notes",ru?"Контрольные заметки":"Review notes","textarea")}</>}
    {type==="objective"&&<><div className="field"><label htmlFor={`${prefix}-objectiveType`}>{ru?"Тип":"Type"}</label><select id={`${prefix}-objectiveType`} name="objectiveType"><option value="outcome">Outcome</option><option value="benefit">Benefit</option><option value="kpi">KPI</option><option value="output">Output</option><option value="objective">Objective</option></select></div>{field("baseline","Baseline")}{field("target","Target")}</>}
    {type==="iteration"&&<>{field("startDate",ru?"Начало":"Start","date")}{field("capacity","Capacity","number")}</>}
    {type==="change"&&<>{field("scopeImpact","Scope impact")}{field("scheduleImpact","Schedule impact")}{field("costImpact","Cost impact")}{field("riskImpact","Risk impact")}{field("qualityImpact","Quality impact")}{field("alternatives",ru?"Альтернативы":"Alternatives","textarea")}{field("recommendation",ru?"Рекомендация":"Recommendation","textarea")}{field("approver","Approver")}</>}
    {type==="project"&&<><div className="field"><label htmlFor={`${prefix}-projectType`}>{ru?"Тип проекта":"Project type"}</label><select id={`${prefix}-projectType`} name="projectType"><option value="software">Software / Product</option><option value="marketing">Marketing</option><option value="operations">Operations</option><option value="education">Education</option><option value="agency">Client / Agency</option><option value="transformation">Transformation</option><option value="infrastructure">Infrastructure</option><option value="research">Research</option><option value="general">General</option></select></div>{field("sponsor","Sponsor")}{field("objective",ru?"Измеримый outcome":"Measurable outcome","textarea",true)}{field("successMeasures",ru?"Метрики успеха — по строке":"Success measures — one per line","textarea")}{field("scopeIn","Scope in","textarea")}{field("scopeOut","Scope out","textarea")}{field("constraints",ru?"Ограничения":"Constraints","textarea")}{field("definitionOfDone","Definition of Done","textarea")}{field("currency",ru?"Валюта, ISO код":"Currency, ISO code")}<p className="wide muted">{ru?"Контекст 1–5: rule engine прозрачно выберет рабочий подход и уровень governance.":"Context 1–5: the rule engine transparently selects an operating approach and governance level."}</p>{(["uncertainty","volatility","feedback","frequency","compliance","dependencies","autonomy","scopeRigidity","deadlineRigidity","stakeholders"] as (keyof Context)[]).map(k=><div className="field" key={k}><label htmlFor={`${prefix}-${k}`}>{k}</label><input id={`${prefix}-${k}`} name={k} type="range" min="1" max="5" defaultValue="3"/></div>)}</>}
    <div className="button-row wide"><button type="button" className="button" onClick={onClose}>{ru?"Отмена":"Cancel"}</button><button className="button primary" type="submit">{ru?"Создать":"Create"}</button></div>
  </form></section></div>;
}
