"use client";
import { Download, Upload } from "lucide-react";
import { ContextFields } from "./context-fields";
import { defaultContext } from "@/content/project-context";
import { enumLabels } from "@/content/workspace-i18n";
import type { Locale, Workspace } from "@/domain/schemas";

export function WorkspaceSettingsView({workspace,project,locale,onChange,snapshots,onExport,onImport,onRestore}:{workspace:Workspace;project:Workspace["projects"][number];locale:Locale;onChange:(workspace:Workspace)=>void;snapshots:{key:string;at:string}[];onExport:()=>void;onImport:()=>void;onRestore:(key:string)=>void;}) {
  const ru=locale==="ru",settings=workspace.projectSettings.find(x=>x.projectId===project.id),updateLimit=(column:string,value:number)=>onChange({...workspace,projectSettings:settings?workspace.projectSettings.map(x=>x.projectId===project.id?{...x,wipLimits:{...x.wipLimits,[column]:Math.max(1,value)}}:x):[...workspace.projectSettings,{projectId:project.id,enabledTypes:["initiative","epic","feature","story","task","subtask","bug","spike","deliverable"],wipLimits:{[column]:Math.max(1,value)},governance:project.governance,probabilityScale:5,impactScale:5}]});
  return <div className="dashboard-grid">
    <details className="panel span-12"><summary>{ru?"Контекст проекта и рекомендации":"Project context and recommendations"}</summary><p>{ru?"Ответы меняют рекомендации на экране «Сейчас». Сохранённый подход проекта изменяется отдельно в карточке проекта.":"Answers change Today recommendations. Change the recorded project approach separately in the project editor."}</p><ContextFields locale={locale} value={settings?.context??defaultContext} onChange={context=>onChange({...workspace,projectSettings:[...workspace.projectSettings.filter(x=>x.projectId!==project.id),{projectId:project.id,enabledTypes:["task"],wipLimits:{},governance:project.governance,probabilityScale:5,impactScale:5,...settings,context}]})}/></details>
    <section className="panel span-6"><h3>{ru?"Это я в этом проекте":"This is me in this project"}</h3><select className="input" aria-label={ru?"Это я в этом проекте":"This is me in this project"} value={workspace.projectSettings.find(s=>s.projectId===project.id)?.localMemberId??""} onChange={e=>{const existing=workspace.projectSettings.find(s=>s.projectId===project.id);onChange({...workspace,projectSettings:[...workspace.projectSettings.filter(s=>s.projectId!==project.id),{projectId:project.id,enabledTypes:["task"],wipLimits:{},governance:project.governance,probabilityScale:5,impactScale:5,...existing,localMemberId:e.target.value||undefined}]})}}><option value="">{ru?"Не выбрано":"Not selected"}</option>{workspace.teamMembers.filter(m=>m.projectId===project.id).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><p className="muted">{ru?"Локальная настройка для представления «Моя работа».":"A local preference for the My work view."}</p></section>
    <section className="panel span-6"><h3>{ru?"Уровень подсказок":"Guidance level"}</h3><p className="muted">{workspace.experience==="foundation"?(ru?"Пошаговые объяснения и упрощённая первичная навигация.":"Step-by-step explanations and simplified primary navigation."):workspace.experience==="advanced"?(ru?"Контрольные данные и действия без лишнего учебного слоя.":"Control data and actions with minimal teaching layer."):(ru?"Сбалансированные подсказки для регулярной проектной работы.":"Balanced guidance for regular project delivery.")}</p><select className="input" aria-label={ru?"Уровень подсказок":"Guidance level"} value={workspace.experience} onChange={e=>onChange({...workspace,experience:e.target.value as Workspace["experience"]})}>{Object.entries(enumLabels[locale].experience).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></section>
    <section className="panel span-6"><h3>{ru?"Плотность интерфейса":"Interface density"}</h3><p className="muted">{ru?"Независима от уровня подсказок.":"Independent from guidance level."}</p><select className="input" aria-label={ru?"Плотность интерфейса":"Interface density"} value={workspace.density} onChange={e=>onChange({...workspace,density:e.target.value as Workspace["density"]})}><option value="comfortable">{ru?"Комфортная":"Comfortable"}</option><option value="compact">{ru?"Компактная":"Compact"}</option></select></section>
    <section className="panel span-6"><h3>{ru?"Локальные данные":"Local data"}</h3><p className="muted">{ru?"Данные сохраняются на этом устройстве. Перед очисткой браузера скачайте резервную копию.":"Data is stored on this device. Download a backup before clearing the browser."}</p><div className="button-row"><button className="button" onClick={onExport}><Download size={16}/>{ru?"Скачать резервную копию":"Download backup"}</button><button className="button" onClick={onImport}><Upload size={16}/>{ru?"Восстановить":"Restore"}</button></div></section>
    <section className="panel span-6"><h3>{ru?"Лимиты незавершённой работы (WIP)":"WIP limits"}</h3><div className="form-grid"><label className="field"><span>{ru?"В работе":"In progress"}</span><input type="number" min="1" value={settings?.wipLimits["in-progress"]??3} onChange={e=>updateLimit("in-progress",Number(e.target.value))}/></label><label className="field"><span>{ru?"На проверке":"Review"}</span><input type="number" min="1" value={settings?.wipLimits.review??2} onChange={e=>updateLimit("review",Number(e.target.value))}/></label></div><p className="muted">{ru?"Лимит должен отражать доступную мощность системы, а не желаемое количество задач.":"A limit should reflect system capacity, not desired task count."}</p></section>
    <section className="panel span-6"><h3>{ru?"Автоматические снимки данных":"Automatic snapshots"}</h3>{snapshots.length?<ul className="clean-list">{snapshots.map(s=><li key={s.key}><div className="section-line"><time>{new Date(s.at).toLocaleString(locale)}</time><button className="button small" onClick={()=>onRestore(s.key)}>{ru?"Восстановить":"Restore"}</button></div></li>)}</ul>:<p className="muted">{ru?"Первый снимок создаётся после сохранения.":"The first snapshot is created after saving."}</p>}</section>
  </div>;
}
